### ISSUE TITLE
Browsing to Watch Lists -> Ports gives me an error 500

### ISSUE THREAD

**Issue by RvdE** [FreshPorts/freshports#106]
When clicking on Watch Lists -> Ports (https://www.freshports.org/watch.php) I get an error 500. I've tried setting my watch list to default (which I seemed to have forgotten), recreating it (and setting it to default), but that doesn't remedy it.

Not sure if it's only happening for me, but my username is 'Tremere'.

**Comment by kiela** [comment]
I have the same issue, username: 'kiela'.

**Comment by dlangille** [comment]
and me too.

**Comment by dlangille** [comment]
Now I get a login prompt.  What about you two?

**Comment by RvdE** [comment]
Works fine again. Thanks for fixing it.

**Comment by kiela** [comment]
Works 🎉
