### ISSUE TITLE
Distilator is obsoleted by Portscout

### ISSUE THREAD

**Issue by scassiba** [FreshPorts/freshports#11]
Clicking on [Distfiles Availability](http://people.freebsd.org/~ehaupt/distilator/) results in a big message saying "This service has been discontinued."

[Portscout](http://portscout.freebsd.org/) is the canonical replacement and should be used instead.

**Comment by dlangille** [comment]
Thank you...

**Comment by dlangille** [comment]
See also https://github.com/FreshPorts/freshports/pull/13

**Comment by dlangille** [comment]
Closed as fixed by #13
