### ISSUE TITLE
Add an option to sort results by last updated

### ISSUE THREAD

**Issue by debdrup** [FreshPorts/freshports#116]
It would be great if it was possible to specify last updated as an option in "Sort By" on the search.php page.
It should be possible given that there's a value for last updated displayed on the page.

It's not really critical, just a nice-to-have. :)

**Comment by dlangille** [comment]
Please test this at https://dev.freshports.org

There is a new item in the 'Sort by' drop down list.

**Comment by debdrup** [comment]
Yep, it's working: https://dev.freshports.org/search.php?stype=shortdescription&method=match&query=IRC&num=10&orderby=lastupdate&orderbyupdown=desc&search=Search&format=html&branch=head :)

**Comment by dlangille** [comment]
Now in production.
