### ISSUE TITLE
Please provide license and logo to gsequencer binary

### ISSUE THREAD

**Issue by joelkraehemann** [FreshPorts/freshports#118]
The following command shows correct about dialog of GSequencer.

`AGS_LICENSE_FILENAME=/usr/local/share/licenses/gsequencer-2.1.76/GPLv3 AGS_LOGO_FILENAME=/usr/local/share/gsequencer/images/ags.png gsequencer`

It should be configured during build by passing as C macros from CPPFLAGS.

![Screenshot from 2019-06-14 20-01-09](https://user-images.githubusercontent.com/12599056/59529005-1c4ae680-8ee0-11e9-910d-d53e1414c9c9.png)

**Comment by dlangille** [comment]
This seems to be asking for a change to a port.  FreshPorts isn't the place for that.  FreeBSD.org is.

re https://www.freshports.org/about.php

Instead, try https://bugs.freebsd.org/

Sorry.
