### ISSUE TITLE
FreeBSD12 linux-oracle-jdk18-8.241 arm error

### ISSUE THREAD

**Issue by 4593645** [FreshPorts/freshports#135]
`root@rpi-b:/usr/ports/java/linux-oracle-jdk18 # make install clean`
`===>  linux-oracle-jdk18-8.241 is only for amd64 i386, while you are running`
`armv6.`
`*** Error code 1`

`Stop.`
`make: stopped in /usr/ports/java/linux-oracle-jdk18`
`root@rpi-b:/usr/ports/java/linux-oracle-jdk18 # brandelf -l`
`known ELF types are: FreeBSD(9) Linux(3) Solaris(6) SVR4(0) `
`root@rpi-b:/usr/ports/java/linux-oracle-jdk18 # `

**Comment by dlangille** [comment]
This appears to be an issue with a package.  That belongs on https://bugs.freebsd.org/

Thank you.

**Comment by dlangille** [comment]
Also, "linux-oracle-jdk18-8.241 is only for amd64 i386,"

You cannot build it on an armv6 host.
