### ISSUE TITLE
Allow for an easy account deletion procedure

### ISSUE THREAD

**Issue by lsalvadore** [FreshPorts/freshports#139]
At https://www.freshports.org/faq.php we read
"How do I delete my account?"
"You can't. But you can unsubscribe from all of the reports and you'll never hear from us again."

I am not a lawyer, but I fear that this might be an issue at least with European users: I think that the GDPR requires accounts deletion for anyone asking such operation.

**Comment by dlangille** [comment]
I have created a working solution at https://dev.freshports.org/

@lsalvadore if you would like to create a new account there and try deleting please

**Comment by lsalvadore** [comment]
I am sorry, but I am unable to complete the new account creation procedure: the activation e-mail does not arrive. I inserted as username "salvadore" and as e-mail address "salvadore@FreeBSD.org".

**Comment by dlangille** [comment]
I see the email leaving my mail server and hitting fastmail.com

My prediction: greylisting.

It reached fastmail.com at Apr 10 14:49:35 which is about 25 minutes ago.

**Comment by dlangille** [comment]
If the email has not arrived by now, I can intervene with the account.

**Comment by lsalvadore** [comment]
No mail yet. Could you please intervene? Thanks.

**Comment by lsalvadore** [comment]
It worked, thanks!

**Comment by dlangille** [comment]
Good. Thank you.  I'll commit this soon.

**Comment by dlangille** [comment]
This isn't in prod yet, but will go into the next release.
