### ISSUE TITLE
"This port is required by" not updated after the dependency is removed in the ports tree

### ISSUE THREAD

**Issue by woodsb02** [FreshPorts/freshports#14]
When a port dependency is removed in the ports tree, the FreshPorts page for the dependent port does not remove the port which previously depended on it from the "This port is required by" list.

This was recently noticed when graphics/mapnik was updated to no longer depend on devel/py-icu:
https://svnweb.freebsd.org/ports/head/graphics/mapnik/Makefile?r1=410719&r2=410718&pathrev=410719

After this commit, the FreshPorts page http://www.freshports.org/graphics/mapnik was correctly updated to no longer show a dependency on devel/py-icu.

However, the FreshPorts page http://www.freshports.org/devel/py-icu still incorrectly showed that "this port is required by: graphics/mapnik".

After discussion with Dan Langille on IRC, it was determined that this was caused by a cache issue on the FreshPorts server. The cache for devel/py-icu was not invalidated.

`[dan@supernews:/usr/local/www/freshports.org/dynamic/caching/cache/ports/devel/py-icu] $ ls -lt
total 58
-rw-rw-r--  1 www  www  28699 Feb  8 21:30 Detail.PageSize500.PageNum1.html
-rw-rw-r--  1 www  www  28626 Oct 30 18:09 Detail.PageSize100.PageNum1.html
[dan@supernews:/usr/local/www/freshports.org/dynamic/caching/cache/ports/devel/py-icu] $ rm Detail.PageSize*
[dan@supernews:/usr/local/www/freshports.org/dynamic/caching/cache/ports/devel/py-icu] $ `

**Comment by dlangille** [comment]
I am positive I fixed this a few weeks back.  see https://news.freshports.org/2016/07/25/when-dependencies-change-both-ports-need-to-be-updated/
