### ISSUE TITLE
rss does not display properly

### ISSUE THREAD

**Issue by ronaldklop** [FreshPorts/freshports#146]
Using theoldreader,com for RSS. The feeds from freshports do not display correctly.
- newlines do not display.
- If there is something like <changelog> in the text it is not displayed as the browser sees it as an invalid html tag. So it should be htmlspecialchar'ed on the server.

/classes/newsfeed.php sets "$item->descriptionHtmlSyndicated = true;", but the description from SVN is plain text.
If you disable htmlSyndicated than https://github.com/flack/UniversalFeedCreator/blob/master/lib/Element/FeedHtmlField.php will properly htmlspecialchar the description.

Is there a reason to enable htmlSyndicated for the plain text commit message?
Otherwise I would like to propose to set descriptionHtmlSyndicated=false.

**Comment by dlangille** [comment]
I just set `$item->descriptionHtmlSyndicated = false`on https://dev.freshports.org/ - how is that?

**Comment by dlangille** [comment]
@ronaldklop how is that looking now?

**Comment by ronaldklop** [comment]
My RSS reader does not display it differently. UniversalFeedCreator does generate html comaptiblecontent with true and false for descriptionHtmlSyndicated. So I do not see what the purpose of this option is. To make the plain text of a commit message html compatible the following patch is needed AFAIK.
So we first need to convert the plain text into html before giving to the FeedCreator. The FeedCreator expects HTML as input. Which is also allowed for the description by the specs of RSS.

diff --git a/classes/newsfeed.php b/classes/newsfeed.php
index 2e9859ae..de1dae4f 100644
--- a/classes/newsfeed.php
+++ b/classes/newsfeed.php
@@ -309,7 +309,7 @@ ORDER BY CL.commit_date DESC, CL.id ASC, E.name, category, version LIMIT 20";
 
                $item->title = $myrow['category'] . '/' . $myrow["port"] . ' - ' . freshports_PackageVersion($myrow['version'], $myrow['revision'], $myrow['epoch']);
                $item->link  = $link;
-               $item->description = trim($description);
+               $item->description = nl2br(htmlspecialchars(trim($description)));
 
                //optional
                //item->descriptionTruncSize = 500;

**Comment by dlangille** [comment]
Changed.  How's it look now?

**Comment by ronaldklop** [comment]
Perfect!

**Comment by dlangille** [comment]
Thank you. This should hit production soon.
