### ISSUE TITLE
Please add a link to Repology

### ISSUE THREAD

**Issue by thierry-FreeBSD** [FreshPorts/freshports#148]
Just an idea: from a port page, try to add a link towards the corresponding page at Repology.

E.g. from https://www.freshports.org/www/firefox/ add a link to https://repology.org/project/firefox/versions

This could let us see if a port is lagging, and even suggest to rename some ports.

**Comment by dlangille** [comment]
Should this be done for every port?  Is the pattern always like this:

www.freshports.org/A/B -> repology.org/project/B/versions

**Comment by thierry-FreeBSD** [comment]
This is usually the case for "regular" ports, but unfortunately FreeBSD has some special namings.

E.g. math/py-cvxopt -> python:cvxopt
https://repology.org/project/python:cvxopt/versions
but https://repology.org/project/cvxopt/versions redirect to the same page, because this is the common name.

Same thing for devel/p5-Term-ReadLine-Gnu: it is known as perl:term-readline-gnu by Repology,

Same thing for PHP ports: e.g. all our mail/phpxx-imap are known by Repology as php:imap, whatever the PHP version.

But this could be done brutally to begin with, and then refined little by little for the special cases.

**Comment by dlangille** [comment]
Sounds like we need a `ports_repology` mapping table:

```
port_name text not null,
repology_name text not null
```

With a unique index on `port_name`

**Comment by dlangille** [comment]
Do not interpret the following as reasons not to implement the idea.

This is a big project.

Manually maintaining data is foreign to existing design goals.  Few people want to do that work. Fewer still will persist at that task.  The whole idea behind FreshPorts is to make everything automated and required little, if any, actual manual work.  This practice has existed for 20 years.

* If the system creates a link which is a 404 users will tell us. That creates work. I also don't like creating 404s to other websites. It is not polite.
* The system could check the link to see if it is a 404. If it is, don't show it.
* Users will then say: why is there no repology link?
* We need to allow users to suggest a repology link.
* We need to review those links
* Now we need people to review the input
* We are now displaying user input on the webpage
* That's an attack vector

Just creating the link to repology is easy.  We can do that and all 39,400 ports will have that link. I suspect many of those links will be 404s.

Creating a workflow for that which avoids malicious input and then getting people to review that input is not easy.

**Comment by thierry-FreeBSD** [comment]
OK, I can understand that.

This is not a must-have feature, just a nice-to-have, and there is no hurry!

**Comment by AMDmi3** [comment]
You don't need any kind of mapping tables, Repology does it on its own.

https://repology.org/tools/project-by?repo=freebsd&name_type=srcname&target_page=project_versions

Where `<NAME>` is e.g. `www/firefox`.

**Comment by thierry-FreeBSD** [comment]
Great, this is very useful!
