### ISSUE TITLE
More descriptive meta description tags

### ISSUE THREAD

**Issue by davidschlachter** [FreshPorts/freshports#157]
Currently [all meta description tags](https://github.com/FreshPorts/freshports/blob/master/include/freshports_page.php#L31) are set to: "FreshPorts - new ports, applications". If these tags are the same on many different pages, search engines will [ignore them](https://support.google.com/webmasters/answer/35624#meta-descriptions) and try to figure out a relevant description on their own, poorly:

![screenshot-2020-06-24_001](https://user-images.githubusercontent.com/8271268/85573370-d43ac580-b603-11ea-8d3b-2b2152ef446b.png)

I suggest that for pages for individual ports, the meta description tag be set to the port description:

![screenshot-2020-06-24_000](https://user-images.githubusercontent.com/8271268/85572894-6393a900-b603-11ea-85e4-c76134a5a5d5.png)

**Comment by dlangille** [comment]
This **should** be easy to do. I'll have to look at what gets cached / not cached.

**Comment by dlangille** [comment]
The cache for a port is already in three parts.  Might as well make it four parts.

see comments at https://news.freshports.org/2020/04/18/if-packages-and-ports-are-cached-separately-how-is-one-included-in-the-middle-of-the-other/

**Comment by dlangille** [comment]
This was a one line change.

Finding that one line took longer than I figured.

dev.freshports.org is now configured this new way for all ports.

**Comment by dlangille** [comment]
Categories also updated for this same type of change. e.g. https://dev.freshports.org/net/

**Comment by dlangille** [comment]
Oh. It seems I have some work to do:

```
[dan@dev-nginx01:~/www] $ grep -r 'new ports, applications' * | wc -l
      55

```

**Comment by dlangille** [comment]
> This was a one line change.
> 
> Finding that one line took longer than I figured.
> 
> dev.freshports.org is now configured this new way for all ports.

That's just for the first display. This isn't making it in to cache yet.  I'll have to expand that.

**Comment by dlangille** [comment]
> > This was a one line change.
> > Finding that one line took longer than I figured.
> > dev.freshports.org is now configured this new way for all ports.
> 
> That's just for the first display. This isn't making it in to cache yet. I'll have to expand that.

After a walk in the park, it took about 10 minutes to make the code changes. to `rewrite/missing-port.php`.

**Comment by dlangille** [comment]
Please note: I have swapped out this branch - the fix is not visible now - while I work on another feature.

**Comment by dlangille** [comment]
This is now in production.
