### ISSUE TITLE
Provide "Expand this list" plist link on the top and and on the bottom of the plist.

### ISSUE THREAD

**Issue by jurajlutter** [FreshPorts/freshports#168]
A link with `Expand this list` would be nice to have not only on the bottom (after expanding the plist) but also on the top of the expanded plist to quicky _toggle_ expanded/folded plist.

**Comment by dlangille** [comment]
it should also apply to distinfo (https://www.freshports.org/net-im/signal-cli/), dependencies (https://www.freshports.org/textproc/asciidoc/), & master sites: (https://www.freshports.org/audio/drumstick/)

**Comment by dlangille** [comment]
Also UPDATING say, for [net-mgmt/librenms](https://www.freshports.org/net-mgmt/librenms/)

**Comment by dlangille** [comment]
Related to #167
