### ISSUE TITLE
Missing number(s) in the dependency block

### ISSUE THREAD

**Issue by novel** [FreshPorts/freshports#175]
How to reproduce,

1. Go to a specific port page, e.g. https://www.freshports.org/audio/mpg123 (though the problem affects other ports as well),
2. Navigate to "This port is required by:", and then scroll down to "for Libraries"
3. After number 7, click the "Expand this list (25 items / 18 hidden)" label. You'll get a full list, but:

```  
    7. audio/py-fmoo-audiotools
         Collapse this list.
    9. audio/sdl2_mixer
```

As you can see, number 8 is missing.

Same story with the "for Run" section: if you click the expand list control, number 8 will be missing again.

**Comment by dlangille** [comment]
Looking at the HTML, I am sure no data is missing. I think this is only a numbering issue.  Thank you.

**Comment by dlangille** [comment]
@novel This should be fixed on [dev.freshports.org](https://dev.freshports.org)

**Comment by novel** [comment]
> @novel This should be fixed on [dev.freshports.org](https://dev.freshports.org)

This looks good, thanks!
