### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by CyberCr33p** [FreshPorts/freshports#176]
When I visit https://www.freshports.org/ports-mgmt/pkg/ and https://www.freshports.org/math/R-cran-uroot/ it shows a white screen. Other ports pages work fine. The most common issue when this happens is related to low php memory_limit, but enable display_errors to be sure what the issue is.

**Comment by dlangille** [comment]
The cache entries were zero.  Not sure why.

Clearing the cache solved that.

**Comment by CyberCr33p** [comment]
Thank you.
