### ISSUE TITLE
Add a link for pkg-fallout list of each port on portsfallout.com

### ISSUE THREAD

**Issue by dbaio** [FreshPorts/freshports#181]
Hi.

Opening an issue as asked.

pkg-fallout list for individual ports:
https://portsfallout.com/fallout?port=www%2Ffirefox%24

Query is `port=www/firefox$`, using regular expressions.

Something like 

```
https://portsfallout.com/fallout?port=
+
rawurlencode("port/category$")
```

Don't know if it's necessary, but here is a query with the API as well:

https://portsfallout.com/api/fallout/?search=www%2Ffirefox
https://portsfallout.com/api/fallout/?format=json&search=www%2Ffirefox
^^ This is an exact match.

If you will use an image icon, here is what we are using, but feel free to use any icon you want to:
https://github.com/dbaio/portsfallout/blob/master/static/favicon-16x16.png
https://github.com/dbaio/portsfallout/tree/master/static/
^^ There are other sizes as well

Thank you!

**Comment by dlangille** [comment]
The icon links are much appreciated.

**Comment by dlangille** [comment]
Please review on dev.freshports.org. You should see it on

* main page
* each port page
* search results

**Comment by dbaio** [comment]
Hi.

Could you add `$` in the end?

```
https://portsfallout.com/fallout?port=
+
rawurlencode("port/category$")
```

https://dev.freshports.org/audio/id3lib
https://portsfallout.com/fallout?port=audio%2Fid3lib
OK

https://dev.freshports.org/www/nginx
https://portsfallout.com/fallout?port=www%2Fnginx
It shows fallouts for www/nginx-full.

https://dev.freshports.org/devel/py-pip
https://portsfallout.com/fallout?port=devel%2Fpy-pip
It shows results for devel/py-pip-licenses.

https://portsfallout.com/fallout?port=devel%2Fpy-pip%24
^^
This is the desired url.

And thank you!

**Comment by dlangille** [comment]
How's that now?

**Comment by dbaio** [comment]
Great.
Just one more thing, I think you can remove it from the main page, as the commits can reference more ports.

**Comment by dlangille** [comment]
Good point.

Have a look now. It is per port, not per commit.

**Comment by dlangille** [comment]
Also: added an FAQ entry for this new icon: https://dev.freshports.org/faq.php

**Comment by dbaio** [comment]
awesome, thank you
