### ISSUE TITLE
Add a link for opening tickets in bugs.freebsd.org

### ISSUE THREAD

**Issue by lwhsu** [FreshPorts/freshports#182]
Hello,

It would be useful to have a link to bugs.freebsd.org, to quickly chek the opening tickets of that port. It could encourage people fixing the existing issues and avoid reporting the same issue.

The URL is `https://bugs.freebsd.org/bugzilla/buglist.cgi?quicksearch=${query}`

where query is `category%2Fport`

For example: for, editors/liboreffice, the link would be: https://bugs.freebsd.org/bugzilla/buglist.cgi?quicksearch=editors%2Flibreoffice

Please consider adding this, thanks!

**Comment by dlangille** [comment]
Have a look at the port page itself. The arrow in the following image points between the two icons in question.

![IMG_1445](https://user-images.githubusercontent.com/1626436/98243299-b713ed00-1f3b-11eb-9b74-b71bb7e08f29.jpeg)

This is a screen shot from [x11-wm/icewm](https://www.freshports.org/x11-wm/icewm/)

The left icon goes to:

 https://bugs.freebsd.org/bugzilla/buglist.cgi?component=Individual%20Port%28s%29&list_id=385624&product=Ports%20%26%20Packages&query_format=advanced&resolution=---&short_desc=x11-wm%2Ficewm&short_desc_type=allwordssubstr

The right icon goes to: 

https://bugs.freebsd.org/bugzilla/enter_bug.cgi?component=Individual%20Port%28s%29&product=Ports%20%26%20Packages&short_desc=x11-wm%2Ficewm

Does that help?

This leads me to: the [FAQ](https://www.freshports.org/faq.php) page is incomplete and does not list newer icons.

**Comment by lwhsu** [comment]
Oh that's great, sorry that I was not aware of those icons, I thought they mean the states of that port such as new, broken, has vulnerability, etc. I didn't know they can also be clicked. Do you think these clickable icons deserve some text description or other ways to improve the intuition?

**Comment by dlangille** [comment]
If you hover over the icon, you should get a pop-up message describing each icon.

**Comment by lwhsu** [comment]
> If you hover over the icon, you should get a pop-up message describing each icon.

That works, indeed, I found it after you pointed that out. Perhaps we can do something to make it more intuitive for clickable at the first sight?

**Comment by dlangille** [comment]
Sure.  I'm open to suggestions.
