### ISSUE TITLE
Scripts, surrounded with <pre> at the topmost of the page in dev.freshports.org are visible to the public.

### ISSUE THREAD

**Issue by vigole-com** [FreshPorts/freshports#183]
Scripts, surrounded with <pre> at the topmost of the page in dev.freshports.org are visible to the public.
I'm not sure whether it's a problem or it's intentional. After all it's "dev.*".  I thought I should report it.
Example:
https://dev.freshports.org/x11-wm
https://dev.freshports.org/x11-wm/i3

**Comment by dlangille** [comment]
That is debugging output.  I turned it on a few weeks ago while tracking something down.

What I was looking for? I don't recall now.

Thank you for your kind concern.

**Comment by dlangille** [comment]
Debugging is now off.
