### ISSUE TITLE
change http:// to https://

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#184]
There are numerous instances of http:// within the code.

I think they can all be changed to https://

Perhaps declare a constant.

**Comment by smyru** [comment]
Starting links with // would create a relative link compatible with whichever protocol is used to load the site. Not advocating for HTTP usage in production, although it may occasionally be helpful for debugging or testing when setting development env.

**Comment by dlangille** [comment]
Thanks.

Most of these links were to another server.

Many were to this same server.
