### ISSUE TITLE
display distinfo size for ports

### ISSUE THREAD

**Issue by vrwmiller** [FreshPorts/freshports#19]
Can a port's distsize attribute be displayed for each port?

From twitter:
I can sense a new table coming on: distinfo (port_id, distname, sha256, size...)

Should be simple to extract SIZE and parse the line for each file.

**Comment by dlangille** [comment]
distinfo now displayed on http://dev.freshports.org/

**Comment by dlangille** [comment]
New code and webui pushed to site.
