### ISSUE TITLE
Prepare for reference to the (fast) cgit service for ports

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#197]
Leisurely preparations `:-)`

### Beta service

* https://cgit-dev.freebsd.org/ports/

https://lists.freebsd.org/pipermail/freebsd-current/2021-January/078487.html questions where to report issues with the beta. In the meantime, please note that (for example) there's a default to `branches/2014Q1` where (I guess) `main` should be more appropriate. 

### Context

https://www.freebsd.org/news/status/report-2020-10-2020-12.html#Git-Migration-Working-Group

I _assume_ that the eventual non-beta service URL will be: 

* `https://cgit.freebsd.org/ports`

**Comment by grahamperrin** [comment]
… maybe this GitHub issue will be of no benefit to preparations. If so: sorry, please close.

----

https://news.freshports.org/?s=cgit&searchsubmit= for _cgit_ finds: 

* [Moving devgit.freshports.org from GitHub to git.FreeBSD.org – FreshPorts News](https://news.freshports.org/2020/12/17/moving-devgit-freshports-org-from-github-to-git-freebsd-org/) (2020-12-17) with reference to `https://cgit.freebsd.org/doc/` (doc)
* [Moving to the FreeBSD git repo for src – FreshPorts News](https://news.freshports.org/2020/12/21/moving-to-the-freebsd-git-repo-for-src/) (2020-12-21) with reference to `https://cgit.freebsd.org/src/` (src). 

More generally, https://news.freshports.org/category/development/git/ for _git_.

**Comment by dlangille** [comment]
It is always helpful to have others involved in the work. Concern for upcoming changes is appreciated.
