### ISSUE TITLE
Parser failed – ucl_tool failed – for graphics/drm-current-kmod

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#205]
https://www.freshports.org/graphics/drm-current-kmod/#message

```text
ERROR
    WARNING: The FreshPorts parser failed.  ucl_tool failed.  Please report this.
```

If it helps: there was no error before I raised https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253092

**Comment by dlangille** [comment]
Looks like EOM got dropped with this commit:

https://svnweb.freebsd.org/ports/head/graphics/drm-current-kmod/pkg-message?r1=508877&r2=563288&pathrev=563288

**Comment by dlangille** [comment]
fixed via https://svnweb.freebsd.org/ports?view=revision&revision=566759
