### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by dbaio** [FreshPorts/freshports#21]
Only the first 100 commits are shown, even if you click on other pages.

Example:

http://www.freshports.org/sysutils/apcupsd/?page=2
http://dev.freshports.org/sysutils/apcupsd/?page=2

**Comment by dlangille** [comment]
How does http://dev.freshports.org/sysutils/apcupsd/?page=2 look now?

**Comment by dbaio** [comment]
Looks great. 
http://dev.freshports.org/security/vuxml/?page=8

**Comment by dlangille** [comment]
I now wonder about the pagination on all other pages.

This is my patch to fix your issue:

-       if (isset($_SERVER['REDIRECT_QUERY_STRING'])) {
-          parse_str($_SERVER['REDIRECT_QUERY_STRING'], $query_parts);
+       if (isset($_SERVER['QUERY_STRING'])) {
+          parse_str($_SERVER['QUERY_STRING'], $query_parts);
