### ISSUE TITLE
watch.php Go: something terrible has happened

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#211]
I guess, it makes sense to have a separate issue for this …

Whilst encountering #210 I recklessly ignored the error and chose to select all (two) available lists, then clicked **Update**: 

![image](https://user-images.githubusercontent.com/192271/107169020-c714f000-69b4-11eb-9ce5-d399b4fa7477.png)

Now at https://www.freshports.org/watch.php simply clicking the **Go** button (without attempting to select a non-default list) results in: 

> something terrible has happened

**Comment by grahamperrin** [comment]
PS not wanting a proliferation of issues, I'll stop clicking buttons `:-)` and it's 02:30 here in the UK so I might not return to this until the evening …

**Comment by dlangille** [comment]
I bet this is related to #210.  Please try again.

**Comment by grahamperrin** [comment]
No longer reproducible. Thanks.
