### ISSUE TITLE
Add OPTIONS_NAME value under Configuration Options

### ISSUE THREAD

**Issue by tuaris** [FreshPorts/freshports#217]
Each port has a unique `OPTIONS_NAME` value that allows you to configure port options using a `make.conf` file.  This is especially useful when building ports using [poudriere](https://www.freshports.org/ports-mgmt/poudriere/).

The value can be retrieved by running `make -V OPTIONS_NAME` in the port's directory:

```
# cd ports/lang/php80/
# make -V OPTIONS_NAME
lang_php80
```

You could probably add this as a new section under *Configuration Options*

![image](https://user-images.githubusercontent.com/5660265/109893317-71510200-7c59-11eb-89e4-b0a26419a38b.png)

Sample HTML Code:

```html
<hr>
<dl><dt id="config-name"><b>OPTIONS_NAME:</b></dt>
<dd class="like-pre">lang_php80</dd></dl>

**Comment by dlangille** [comment]
To simplify my work, I will do this only on the git-branch. Which means it won't really be visible until `2021Q2` starts.

I've added the new column to the database and modified the ingress code to pull it from the Makefile and add it to the database.

**Comment by dlangille** [comment]
We have data:

```
freshports.devgit=# select options_name from ports where options_name is not null;
   options_name   
------------------
 games_zdoom
 games_zdoom
 misc_visp
 devel_llvm12
 net_tcptestsuite
(5 rows)

```

**Comment by dlangille** [comment]
Code added to website. See https://devgit.freshports.org/games/zdoom/ or any of the items listed above, or any recent commit at https://devgit.freshports.org/

**Comment by dlangille** [comment]
@tuaris How is that looking now?

**Comment by tuaris** [comment]
Looks good.  That was very awesome of you to do that so quickly.  Hopefully others besides me will find it useful. At least for me it will be a big time saver.

**Comment by dlangille** [comment]
Good, thank you.

This will be committed soon.

**Comment by dlangille** [comment]
Although this is closed, the fix is not yet in production.

**Comment by dlangille** [comment]
This won't go into production until after we move to git processing for ports.

**Comment by dlangille** [comment]
This is now on testgit.freshports.org

**Comment by dlangille** [comment]
Now fixed in prod.

@tuaris please review.

**Comment by dlangille** [comment]
Thank you for a great new feature.
