### ISSUE TITLE
unparsed <br> on the end of "NOTE:" line in plaintext

### ISSUE THREAD

**Issue by vmisev** [FreshPorts/freshports#22]
When searching with _**Depends Build/Lib/Run**_ and _**sounds like**_ for _gimp_ or anything with _**Plain Text**_ selected first line is: 

> `"NOTE: Instead of using 'sounds like' as instructed, the system used 'containing'.  See the notes below for why this is done.<br>graphics/cimg `

with unparsed `<br>` so first result is in the same line

**Comment by dlangille** [comment]
Have a look at http://dev.freshports.org/search.php?stype=depends_all&method=soundex&query=gimp&num=10&orderby=category&orderbyupdown=asc&search=Search&format=html please

**Comment by vmisev** [comment]
Link contains "**_sounds like"_** but html page turns it back to **_"contains"_**. 
After selecting **_Plain Text_** choose **_"sounds like"_** again just before hitting **_Search_** to replicate error. 

With sounds like and Plain Text selected first line is:
`<p><b>NOTE</b>: Instead of using 'sounds like' as instructed, the system used 'containing'.  See the notes above for why this is done.</p>graphics/cimg 
`
pls check:
http://dev.freshports.org/search.php?stype=depends_all&method=soundex&query=gimp&num=10&orderby=category&orderbyupdown=asc&search=Search&format=plaintext

**Comment by dlangille** [comment]
Plain text fixed.

**Comment by vmisev** [comment]
http://www.freshports.org/search.php?stype=depends_all&method=soundex&query=gimp&num=100&orderby=category&orderbyupdown=asc&search=Search&format=plaintext

there is still `<br>first/result` on the **NOTE:** line end.

**Comment by dlangille** [comment]
> Link contains "sounds like" but html page turns it back to "contains". 

This is by design. Sounds like is not valid for many fields.

**Comment by dlangille** [comment]
You looked at prod.  I'm working on dev.  :)

**Comment by dlangille** [comment]
'sounds like' is only valid for certain fields, by design.  Why would you search for sounds like gimp when what you want is contains gimp.

I have added this to the page: Searching for 'sounds like' is only valid for Committer, Maintainer, Package Name, and Port Name.

**Comment by vmisev** [comment]
> 'sounds like' is only valid for certain fields, by design. Why would you search for sounds like gimp when what you want is contains gimp.
> 
> I have added this to the page: Searching for 'sounds like' is only valid for Committer, Maintainer, Package Name, and Port Name.

That’s great! 
I'm aware that this can be produced only intentionally from the page, and that does not make sense, but my only concern was that some script for some strange reason may send this as request and be confused with first line in plain text (or first result may be lost).

**Comment by dlangille** [comment]
That first line in the plain text no longer appears on dev.

**Comment by vmisev** [comment]
great, thanks :) you are star!

**Comment by dlangille** [comment]
Please confirm.  :)

**Comment by vmisev** [comment]
> Please confirm. :)

Plain Text is clean and giving expected results on dev:

http://dev.freshports.org/search.php?stype=depends_all&method=soundex&query=gimp&num=10&orderby=category&orderbyupdown=asc&search=Search&format=html 

and 

http://dev.freshports.org/search.php?stype=depends_all&method=soundex&query=gimp&num=10&orderby=category&orderbyupdown=asc&search=Search&format=plaintext

Thanks one more time!

**Comment by dlangille** [comment]
Thank you.  Let me keep this open until I move it to production.

**Comment by dlangille** [comment]
Commit ede1474 it not related. By 22, it means https://github.com/FreshPorts/git_proc_commit/issues/22
