### ISSUE TITLE
new feature: search by USES=

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#225]
FreshPorts stores the `USES=` values for each port.  A future project: search by `USES`. e.g show me all ports which use `USES= kmod`

**Comment by dlangille** [comment]
Required change:

```
freshports.testgit=# create index ports_uses_simple_idx on ports using gin (to_tsvector('simple'::regconfig, uses));
CREATE INDEX
freshports.testgit=# 
```

**Comment by dlangille** [comment]
Now implemented on dev.

**Comment by dlangille** [comment]
Now in production.

**Comment by grahamperrin** [comment]
Amongst the results for `python:3.*,build` <https://www.freshports.org/search.php?stype=uses&method=match&query=python%3A3.*%2Cbuild&num=20&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head>: 

1. <https://www.freshports.org/emulators/mame/#uses> … `python:3.9,build`
2. <https://www.freshports.org/ports-mgmt/packagekit/#uses> … `python:build` …
3. <https://www.freshports.org/www/qt5-webkit/#uses> … `python:3.5+,build` …

Given the second of those three examples: am I stretching the boundaries of what might be expected with a wildcard? Improper use of a wildcard?

Thanks

**Comment by dlangille** [comment]
I think what you're asking: should wild cards work here?

No, they won't work here with how it's implemented now.
