### ISSUE TITLE
Watch icon (spectacles) not shown in some contexts

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#226]
The icon does appear in search results, and listings, for example: 

![image](https://user-images.githubusercontent.com/192271/112537018-17e67980-8da6-11eb-9f37-d2705f1354d1.png)

Unless I'm missing something, I don't see the icon at <https://www.freshports.org/> – if this is by design, that's fine (keep the homepage not too busy). 

----

A minor issue …

I _sometimes_ don't see the icon at port-specific pages e.g. <https://www.freshports.org/net/wireguard-kmod/> in Firefox `87`.

For a while I suspected that this was more likely to occur when enhanced tracking protection (ETP) is set to strict. 

Now I wonder whether there's a simpler explanation. It seems to be quite easily reproducible: 

1. sign in
2. new 7 days
3. click the name of a port that's new to you

![image](https://user-images.githubusercontent.com/192271/112539194-980dde80-8da8-11eb-8d22-b7602afb0394.png)

I forgot to add: when this happens, a simple reload seems to workaround.

**Comment by dlangille** [comment]
> I forgot to add: when this happens, a simple reload seems to workaround.

That sounds like server-side caching

**Comment by dlangille** [comment]
> > I forgot to add: when this happens, a simple reload seems to workaround.
> 
> That sounds like server-side caching

Confirmed. It is.

**Comment by dlangille** [comment]
I think I've fixed this at https://dev.freshports.org/

It was a flag not being set correctly.

**Comment by dlangille** [comment]
@grahamperrin can you verify fixed at https://dev.freshports.org/ please?

**Comment by grahamperrin** [comment]
OK, https://dev.freshports.org/ports-new.php?interval=week appears OK after creating an account for _grahamperrin_

Thanks
