### ISSUE TITLE
Watch categories ▶ click a category ▶ something terrible has happened

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#227]
Signed in, with https://www.freshports.org/watch-categories.php as a starting point, I clicked three categories. For each one, _something terrible has happened_: 

* https://www.freshports.org/port-watch.php?category=afterstep&wlid=19254
* https://www.freshports.org/port-watch.php?category=archivers&wlid=19254
* https://www.freshports.org/port-watch.php?category=benchmarks&wlid=19254

**Comment by dlangille** [comment]
perhaps related to #210 & #211

**Comment by dlangille** [comment]
Can be reproduced at https://dev.freshports.org/watch-categories.php

**Comment by dlangille** [comment]
Please test at https://dev.freshports.org/

**Comment by grahamperrin** [comment]
Thanks, and I should create an account at dev? (I assume so …)

**Comment by dlangille** [comment]
> Thanks, and I should create an account at dev? (I assume so …)

Sure, if it does not already exist there.  It created as a copy from prod.

**Comment by grahamperrin** [comment]
Account created, _grahamperrin_

The terrible thing seems to be no more, I can get as far as https://dev.freshports.org/port-watch.php?category=emulators&wlid=18842

Thanks!
