### ISSUE TITLE
freshports is down

### ISSUE THREAD

**Issue by mexicarne** [FreshPorts/freshports#23]
Hi Dan, 

we have no freshports for a whole day. In future it would be great to have a note in freebsd-ports@ or in your twitter account for cases like that with likely ETAs on the issue. Thank you!

**Comment by dlangille** [comment]
Please follow FreshPorts on Twitter.  https://twitter.com/freshports

**Comment by dlangille** [comment]
See also https://freshports.wordpress.com where maintenance is also posted.

**Comment by mexicarne** [comment]
I wasn't aware of this resources. Thank you!
