### ISSUE TITLE
HTML anchor #masterport

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#235]
https://github.com/FreshPorts/freshports/blob/f24fa29b607c65907a5664ba0b44dfb735191f97/classes/port-display.php#L1084

After posting https://forums.freebsd.org/threads/freshports-linking-referencing-anchors-in-pages.79644/ I realised that one of the anchors does not appear with my _default_ Firefox profile: 

https://www.freshports.org/graphics/xpdf/#masterport

@dlangille please, can you suggest some other port pages that will have the `#masterport` anchor? 

Thanks

### Observations

![2021-04-03 12:03:00](https://user-images.githubusercontent.com/192271/113476912-61098e00-9476-11eb-9903-aef81765cd75.png)

![2021-04-03 12:03:20](https://user-images.githubusercontent.com/192271/113476914-649d1500-9476-11eb-8526-2745b2500c58.png)

No problem with a different profile, and no problem with e.g. [qutebrowser](https://www.qutebrowser.org/) on the same computer. So it's almost certainly **not an issue with FreshPorts**, however I'm puzzled. 

Logged out from FreshPorts, <kbd>Control</kbd>-<kbd>F5</kbd> reloaded the page, no improvement. 

I suspect an issue with an extension to Firefox, already tried disabling a handful of likely contenders. 

As far as I can tell, https://www.freshports.org/graphics/xpdf4/#slaveports and all other examples are OK with the otherwise bugged Firefox profile. 

![2021-04-03 12:03:36](https://user-images.githubusercontent.com/192271/113476922-7088d700-9476-11eb-9908-7395c7e818b7.png)

**Comment by dlangille** [comment]
Have you tried within the past 12 hours or so?

I ask because the git-based and subversion-based code is different. I think the anchors only went to the git-based code.

**Comment by grahamperrin** [comment]
Interesting. 

https://www.freshports.org/graphics/xpdf/#masterport does now work with my _default_ Firefox profile. 

Where previously the anchor for https://www.freshports.org/graphics/xpdf4/#slaveports appeared to the right, now it appears to the left (in both Firefox profiles): 

![image](https://user-images.githubusercontent.com/192271/114213409-d5eb3500-995a-11eb-9cbb-8367bf072533.png)

**Comment by dlangille** [comment]
Try https://stage.freshports.org/ which is subversion-specific code.  I bet the change to git-based code has fixed this.

**Comment by grahamperrin** [comment]
https://stage.freshports.org/graphics/xpdf4/#slaveports appears to be OK. 

https://stage.freshports.org/graphics/xpdf/#masterport is currently without the anchor with two Firefox profiles, and with qutebrowser.

**Comment by dlangille** [comment]
So.. fixed in prod?

**Comment by grahamperrin** [comment]
I think so. Thanks. 

Peculiar that originally, I found the issue (with one URL) with only one Firefox profile …
