### ISSUE TITLE
Wrong link on delete ports page

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#24]
At http://www.freshports.org/ports-deleted.php, click on any SVNWeb link and you get a 404.  The URL is wrong (e.g. https://ports/head/accessibility/at-poke/?pathrev=362407).

The hostname is missing from the SQL query.

**Comment by dlangille** [comment]
Note the link is correct at http://www.freshports.org/accessibility/at-poke/

**Comment by dlangille** [comment]
Ports deleted prior to SVN introduction will not have an SVN link. Instead of trying to link to svn from this page, you will now click onto the port page, then click the svn link.

Please try this on http://dev.freshports.org/ports-deleted.php and let me know what you think.,

**Comment by pgiffuni** [comment]
Looks like it works ... Thanks!

**Comment by pgiffuni** [comment]
For reference:

Hmm.. a quick failure ..

I looked for "Modula-3" including the deleted ports:

http://dev.freshports.org/search.php?stype=name&method=match&query=Modula&num=100&deleted=includedeleted&orderby=category&orderbyupdown=asc&search=Search&format=html

I clicked on svnweb and I get and exception from svnweb:

https://svnweb.freebsd.org/ports/head/lang/modula-3/?pathrev=-1

The revision in this case is wrong but I think we added a new port
of that without resurrecting the old one.

**Comment by dlangille** [comment]
lang/modula-3 was removed from the tree before the tree went to subversion.  Have another look and see if the new results make more sense.

**Comment by pgiffuni** [comment]
Hmm .. I thought cvs2svn had translated those. Bummer that those are lost.
It's OK then. Thanks!

**Comment by dlangille** [comment]
Have you noticed the changed page output now for your original search query? 

http://dev.freshports.org/search.php?stype=name&method=match&query=Modula&num=100&deleted=includedeleted&orderby=category&orderbyupdown=asc&search=Search&format=html

**Comment by pgiffuni** [comment]
Yes, I noticed the SVNWeb appears crossed. I guess it's the best that can be done right now.

**Comment by dlangille** [comment]
Good.

It seemed to be the best way to do this if FreshPorts does not know how to link to the repo.

**Comment by dlangille** [comment]
See https://github.com/FreshPorts/freshports/commit/352759fc3cf4991262980a2202f69ae12f1af6f4

**Comment by pgiffuni** [comment]
Hmm .. FWIW, it does seem possible to find a revision for some ports that appear crossed.
For the case of FreeCAD, it appears crossed, however, checking the annotations for the MOVED files I find:

https://svnweb.freebsd.org/ports/head/MOVED?r1=235718&r2=235719&
https://svnweb.freebsd.org/ports?view=revision&revision=235719

**Comment by dlangille** [comment]
That commit was on 2009-06-13, which predates svn, does it not?

I mention that because the svn_revision field in FreshPorts for that commit is empty.

We could parse the svn repo for this information, but that would require others to help with the coding and import.

**Comment by pgiffuni** [comment]
I think the ports tree was converted to SVN with cvs2svn, so commits previous to the SVN move still have some corresponding svn revision. I am not sure how to hunt it down though: I tried the MOVED ports file but even that doesn't catch stuff like Modula-3.

**Comment by dlangille** [comment]
The current issue is that FreshPorts acts upon the information available to it at commit time.

**Comment by dlangille** [comment]
It seems this issue has resurfaced, based on email from Pietro Cerutti.

**Comment by dlangille** [comment]
I think I will take a new approach: if no host is provided by the query, default to svnweb.freebsd.org and proceed.

I will work on this soon.

**Comment by gahr** [comment]
Thanks, I'll keep this watched :)

**Comment by dlangille** [comment]
I think this fixed now at http://dev.freshports.org/ports-deleted.php?sort=port&page=127

**Comment by gahr** [comment]
Yup, the yassl link is working, thanks!

**Comment by dlangille** [comment]
Thank you.  This is now in production.
