### ISSUE TITLE
Links to cgit.freebsd.org have wrong URL

### ISSUE THREAD

**Issue by yasuhirokimura** [FreshPorts/freshports#240]
Through conversion of Freshports to git is still in progress, l found one problem.

At the top of each commit there is a link to the page of `cgit.freebsd.org` that corresponds to the commit.

![FreshPorts20210407-01](https://user-images.githubusercontent.com/5249848/113821098-984da700-97b6-11eb-82b4-ce626a0d7896.PNG)

But if you click any of them you always go to the page that corresponds to the latest commit to main branch at the time.

![FreshPorts20210407-02](https://user-images.githubusercontent.com/5249848/113821185-bd421a00-97b6-11eb-87a5-98ba03d64432.PNG)

I checked HTML source code of FreshPorts top page and found each link to `cgit.freebsd.org` has following value of `href` attribute.

```
http://cgit.freebsd.org/ports/commit/(full hash value)
```

But to point to the page of corresponding commit correctly, it should be as following.

```
https://cgit.freebsd.org/ports/commit/?id=(full hash value)
```

**Comment by dlangille** [comment]
@yasuhirokimura - thank you for the examples.

Please review at https://devgit.freshports.org/ - there were similar issues on a commit page, such as https://devgit.freshports.org/commit.php?message_id=e956200e0cb1ab3a412c123fa23aaaf47b1ea8da&files=yes

**Comment by OlCe2** [comment]
Same problem here (spotted in the Commit History section of ports). Indeed fixed on https://devgit.freshports.org. Thanks!

**Comment by dlangille** [comment]
I hope to get this into production today.

**Comment by dlangille** [comment]
With this update, the `repo` table needs to be updated, something like this:

```
freshports.testgit=# update repo set repo_hostname = 'cgit.freebsd.org', path_to_repo = '/ports' where name = 'ports' and repository = 'git';
UPDATE 1
```

**Comment by dlangille** [comment]
Should now be fixed everywhere (dev, test, staging, prod).

**Comment by dlangille** [comment]
> Same problem here (spotted in the Commit History section of ports). Indeed fixed on https://devgit.freshports.org. Thanks!

All OK now @OlCe2?

**Comment by OlCe2** [comment]
Yes, OK on prod.
