### ISSUE TITLE
HTML/CSS/RSS Validator issues

### ISSUE THREAD

**Issue by za3k** [FreshPorts/freshports#241]
1. Currently, HTML and CSS errors are present
2. The entire RSS validation website is down.

**Comment by dlangille** [comment]
Looks likes we're missing `<!DOCTYPE html>` for some reason.

**Comment by dlangille** [comment]
This stuff was valid mere weeks ago. The validator changed significantly.

**Comment by dlangille** [comment]
https://devgit.freshports.org/ has a different validator, but still lots of errors.

**Comment by dlangille** [comment]
This is not fixed, but greatly improved at https://devgit.freshports.org/

**Comment by dlangille** [comment]
@za3k how are things now?

**Comment by za3k** [comment]
I mean all I did is click the three links at the bottom because I was feeling bored, you probably know as well as me. All I'm doing to answer your questions is clicking the three links again, from the front page of freshports.org. It looks there is a working RSS validator now, at least, that's good!

- The RSS says it's valid, with 1 suggestion
- The CSS validator says it's invalid, with 5 errors
- The HTML validator says it's invalid, with 1 error (SIZES as you mention)

**Comment by dlangille** [comment]
OK, thank you.  I'll close this now and work on the validation issues another day. Thank you.
