### ISSUE TITLE
Links to svnweb are broken

### ISSUE THREAD

**Issue by ronaldklop** [FreshPorts/freshports#242]
An example svnweb link points to https://changeset/ports/568912 .
So it looks like it misses a hostname.

**Comment by dlangille** [comment]
At which URL are you seeing this please?

**Comment by dlangille** [comment]
Seems OK at https://www.freshports.org/lang/gcc9-devel/, for example.

**Comment by dlangille** [comment]
Oh, I think I see what you mean. Are you referring to links under Commit History on a port page?

**Comment by ronaldklop** [comment]
Yes, in the Commit History. I was already thinking if I explained it enough. 😉

**Comment by dlangille** [comment]
@ronaldklop Please review at https://devgit.freshports.org/

**Comment by dlangille** [comment]
This should now be fixed on production.
