### ISSUE TITLE
Package message not presented

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#245]
<https://www.freshports.org/ports-mgmt/pkg-provides/#message> no `#message` however: 

![image](https://user-images.githubusercontent.com/192271/114314201-a4f13880-9af1-11eb-92cd-a79ba0d50452.png)

**Comment by dlangille** [comment]
This is how FreshPorts knows there is a pkg-message file:

```
[dan@devgit-ingress01:/var/db/freshports/ports-jail/var/db/repos/ports/ports-mgmt/pkg-provides] $ make -V pkgmessagepath

[dan@devgit-ingress01:/var/db/freshports/ports-jail/var/db/repos/ports/ports-mgmt/pkg-provides] $ 
```

Let's see if there is more.

**Comment by dlangille** [comment]
This seems to do the thing:

```
[dan@devgit-ingress01:/var/db/freshports/ports-jail/var/db/repos/ports/ports-mgmt/pkg-provides] $ sudo mkdir work
[dan@devgit-ingress01:/var/db/freshports/ports-jail/var/db/repos/ports/ports-mgmt/pkg-provides] $ sudo make apply-slist
[dan@devgit-ingress01:/var/db/freshports/ports-jail/var/db/repos/ports/ports-mgmt/pkg-provides] $ cat work/pkg-message 
[
{ type: install
  message: <<EOM
In order to use the pkg-provides plugin you need to enable plugins in pkg.
To do this, uncomment the following lines in /usr/local/etc/pkg.conf file
and add pkg-provides to the supported plugin list:

PKG_PLUGINS_DIR = "/usr/local/lib/pkg/";
PKG_ENABLE_PLUGINS = true;
PLUGINS [ provides ];

After that run `pkg plugins' to see the plugins handled by pkg.
EOM
}
{ type: upgrade
  maximum_version: "0.6.0"
  message: <<EOM
To update the provides database run `pkg provides -u`.
EOM
}
{ 
  type: upgrade
  maximum_version: "0.6.0"
  message: <<EOM
Pkg-provides from v0.6.0 introduces a new database file format.

To update the provides database run `pkg provides -uf`.
EOM
}
]
[dan@devgit-ingress01:/var/db/freshports/ports-jail/var/db/repos/ports/ports-mgmt/pkg-provides] $ sudo make clean
===>  Cleaning for pkg-provides-0.7.1
[dan@devgit-ingress01:/var/db/freshports/ports-jail/var/db/repos/ports/ports-mgmt/pkg-provides] $ 
```

**Comment by dlangille** [comment]
This seems fixed for new commits.  Examples, where I have manually rerun the commits:

* https://devgit.freshports.org/sysutils/bacula11-server/#message
* https://devgit.freshports.org/net-p2p/rslsync/#message

There are a few to catch up on:

```
[dan@devgit-ingress01:/var/db/freshports/ports-jail/var/db/repos/ports] $ find . -name 'pkg-message.*' | wc -l
    1313
[dan@devgit-ingress01:/var/db/freshports/ports-jail/var/db/repos/ports] $ 
```

The proper way to find them is via `make -V PKGMESSAGE` for which the file returned does not exist in the ports tree.

**Comment by grahamperrin** [comment]
Is this a special case? 

* https://www.freshports.org/x11-fonts/dejavu/#message no message
* https://devgit.freshports.org/x11-fonts/dejavu/#message no message
* https://cgit.freebsd.org/ports/tree/x11-fonts/dejavu no `pkg-message` 
* https://cgit.freebsd.org/ports/tree/x11-fonts/dejavu/files/pkg-message.in exists 

```text
root@mowa219-gjp4-8570p:/usr/ports/x11-fonts/dejavu # make clean
===>  Cleaning for dejavu-2.37_1
root@mowa219-gjp4-8570p:/usr/ports/x11-fonts/dejavu # make -V PKGMESSAGE
/usr/ports/x11-fonts/dejavu/work/pkg-message
root@mowa219-gjp4-8570p:/usr/ports/x11-fonts/dejavu # file /usr/ports/x11-fonts/dejavu/work/pkg-message
/usr/ports/x11-fonts/dejavu/work/pkg-message: cannot open `/usr/ports/x11-fonts/dejavu/work/pkg-message' (No such file or directory)
root@mowa219-gjp4-8570p:/usr/ports/x11-fonts/dejavu # 
```

**Comment by dlangille** [comment]
The code change was in the commit-processing part of FreshPorts.

None of this will work until after a commit has occurred to the port in question.

Those 1313 ports mentioned above: they'll need a script written to manually refresh them so the `pkg-message` information is loaded from the ports tree into the database. Then it will appear on the website.

**Comment by dlangille** [comment]
I've just committed a fix. It will take some time before it hits production.

**Comment by dlangille** [comment]
I am sure this is in production now. Any ports with this configuration will pick up the `pkg-message` with a new commit.

A fix-up job is still required to fix all such ports.

**Comment by dlangille** [comment]
@grahamperrin : last night I ran a script on https://devgit.freshports.org/ to update all ports which use a `pkg-message` which is not in the ports tree. 

This should mean that (on that website) all ports which have some kind of `pkg-mesage` should now have a #message section.

I have not reviewed the script output yet.

**Comment by grahamperrin** [comment]
Cool! Thanks. I might take a look tomorrow.

**Comment by dlangille** [comment]
#217 (`options_name`)will also be updated via this script.

**Comment by grahamperrin** [comment]
☑ https://devgit.freshports.org/ports-mgmt/pkg-provides/#message

☑ https://devgit.freshports.org/x11-fonts/dejavu/#message

**Comment by dlangille** [comment]
Now running on testgit.freshports.org

**Comment by dlangille** [comment]
fail.  https://testgit.freshports.org/ports-mgmt/pkg-provides/#message does not show a message.

however, `Options name:` is present.

**Comment by dlangille** [comment]
Fixed. It was a problem with the `make-apply-slist.sh` script.

After install, this is required:

`sudo cp -a /usr/local/libexec/freshports/Jail/scripts/make-apply-slist.sh ~freshports/ports-jail/`

@grahamperrin https://testgit.freshports.org should now be completed.

**Comment by dlangille** [comment]
I'll start that running on stage later today.

**Comment by dlangille** [comment]
Looks good on https://stagegit.freshports.org too.

**Comment by dlangille** [comment]
I will run this on production soon.

**Comment by dlangille** [comment]
It ran much faster on prod than dev/test/stage.

**Comment by grahamperrin** [comment]
`https://www.`

☑ https://www.freshports.org/net-p2p/rslsync/#message

☑ https://www.freshports.org/ports-mgmt/pkg-provides/#message

☑ https://www.freshports.org/sysutils/bacula11-server/#message

☑ https://www.freshports.org/x11-fonts/dejavu/#message

**Comment by dlangille** [comment]
Thank you. Closing.
