### ISSUE TITLE
Commits on branches (2021Q2) are not being processed

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#247]
We have no commits for branches on git.

**Comment by ronaldklop** [comment]
Ah, that would explain why my https://www.freshports.org/backend/rss2.0.php?branch=quarterly RSS is empty for a while.
I will wait for the fix of this issue before opening one about the RSS.

**Comment by dlangille** [comment]
See https://news.freshports.org/2021/06/20/processing-commits-on-branches-with-git/
