### ISSUE TITLE
black background for packages page

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#260]
See https://www.freshports.org/security/krb5/ - in case that is not repeatable, this is the screen shot: 
<img width="1689" alt="Screen Shot 2021-05-03 at 9 20 30 AM" src="https://user-images.githubusercontent.com/1626436/116881332-228bfe00-abf1-11eb-9d43-69214d5180d2.png">

**Comment by dlangille** [comment]
@jethron

**Comment by jethron** [comment]
@dlangille This was the issue fixed in #255 which should have resolved this?

**Comment by dlangille** [comment]
Not seen again.
