### ISSUE TITLE
"This port is required by:" shows up twice

### ISSUE THREAD

**Issue by novel** [FreshPorts/freshports#264]
E.g. https://www.freshports.org/audio/mpg123:

![image](https://user-images.githubusercontent.com/24848/117531650-9ca6f300-aff4-11eb-9d23-766de730db9e.png)

This is probably related to dcad3ef507d2d196121ceb3eef65e2bceff9c63b.

**Comment by dlangille** [comment]
Fixed in production. Thank you for reporting this. :)
