### ISSUE TITLE
Table of packages: contrast when pointing (hovering), and order within pop-ups

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#280]
For example, currently under <https://www.freshports.org/x11/kde5/#packages>: 

![image](https://user-images.githubusercontent.com/192271/118420191-24a49100-b6b6-11eb-9587-af4f29a6d306.png)

I think, it will be better to increase (not decrease) contrast when pointing. A white background to the black text. 

Maybe also increased contrast for the pop-up. 

Is it possible/appropriate to present the times in chronological order? 

For the example above, I'd find things easier to visualise from something like this: 

```text
      package set built 2021-05-16 02:35 UTC
processed by FreshPorts 2021-05-16 16:00 UTC
set checked for changes 2021-05-16 23:00 UTC
```

**Comment by dlangille** [comment]
this is now on [test](https://testgit.freshport.org) via #283

**Comment by dlangille** [comment]
The order seems to be correct.

I have swapped around the text & timestamps so the latter is second.

@jethron can you make it so the popup hover text in the packages section is mono-spaced font? I tried. I failed,

**Comment by dlangille** [comment]
> @jethron can you make it so the popup hover text in the packages section is mono-spaced font? I tried. I failed,

Discussion on IRC says:

* you cannot style that with CSS — that is set by your browser/OS combination
* you would need to replace that with a popup you control, if you need styling capability
* If the information is important, consider that title is not accessible for some people, and that it’s not immediately clear that you need to hover to see more information, and that touch devices do not hover

**Comment by jethron** [comment]
Yeah, we'll have to remove it from the title attribute and display it on hover ourselves. I can make a PR for this tonight after work probably, should be pretty straight forward.

**Comment by dlangille** [comment]
@grahamperrin please review https://devgit.freshports.org/

**Comment by grahamperrin** [comment]
Thanks, https://testgit.freshports.org/archivers/py-zstd/#packages for example: 

![image](https://user-images.githubusercontent.com/192271/119057231-02678780-b9c4-11eb-9b86-916367199fc3.png)

**Comment by grahamperrin** [comment]
… in lieu of: 

> **Packages:** (move your mouse over the cells for more information)

– maybe: 

> **Packages** (timestamps in pop-ups are UTC):

Then remove the header _Repo dates_ and footer _All times are UTC_ within each pop-up: 

* to have shallower, more concise pop-ups. 

----

Nit: maybe `–` (en dash `&#8211;` (U+2013)) in lieu of `-` (dash) in the pop-ups.

**Comment by grahamperrin** [comment]
https://github.com/FreshPorts/freshports/issues/280#issuecomment-843654049

> * touch devices do not hover

Good point. 

I sent https://testgit.freshports.org/archivers/py-zstd/#packages to Firefox on Android, a OnePlus 2 handset, tapped to test.  

IMHO discovery of the pop-ups is (or will be) easy enough. 

----

A person might tap on table headers e.g. _py27-zstd_ and _py36-zstd_ … thought-provoking, but out of scope for this issue.

**Comment by grahamperrin** [comment]
> packages last built

– should be: 

> package last built

– singular. 

Each pop-up is for a single package (or single check, if there's no package).

**Comment by dlangille** [comment]
> A person might tap on table headers e.g. _py27-zstd_ and _py36-zstd_ … thought-provoking, but out of scope for this issue.

What would you expect to happen there?

**Comment by dlangille** [comment]
> – should be:
> 
> > package last built

Fixed on https://devgit.freshports.org/

**Comment by dlangille** [comment]
> … in lieu of:
> 
> > **Packages:** (move your mouse over the cells for more information)
> 
> – maybe:
> 
> > **Packages** (timestamps in pop-ups are UTC):
> 
> Then remove the header _Repo dates_ and footer _All times are UTC_ within each pop-up:
> 
> * to have shallower, more concise pop-ups.
> 
> Nit: maybe `–` (en dash `&#8211;` (U+2013)) in lieu of `-` (dash) in the pop-ups.

Fixed on https://devgit.freshports.org/

**Comment by grahamperrin** [comment]
> > A person might tap on table headers e.g. _py27-zstd_ and _py36-zstd_ … thought-provoking, but out of scope for this issue.
> 
> What would you expect to happen there?

Now: nothing. 

Back in 2021: I probably imagined some way of clicking to learn how one flavour differs from another. 

The _qtonly_ in this example is fairly self-explanatory: 

![image](https://user-images.githubusercontent.com/192271/192348915-0dceabfa-c33d-4fe2-a557-e039ce38275d.png)

– other ports might have flavours that are named more ambiguously. 

----

Forget the idea. 

It's for port maintainers and others to describe, if necessary, differences between flavours. In `pkg-descr`.
