### ISSUE TITLE
Package flavors: potential for confusion

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#287]
I'm not sure whether this is an issue, but here goes …

----

https://www.freshports.org/devel/llvm-devel/#flavors I saw two flavours and https://www.freshports.org/devel/llvm-devel/#packages two tables of packages, and the header of each table matches ~~a flavour~~ the package for a flavour. With ☑ matching numbers (2=2) ~~I can get my head around that~~ I thought I had my head around it, but I was wrong. 

https://www.freshports.org/graphics/py-cairo/#flavors just one flavour (package `py37-cairo` at the time of writing) then **four** tables of packages (`py27-cairo`, `py36-cairo`, `py37-cairo`, `py38-cairo`). ~~Is this an omission, or are there truly fewer named flavour packages than there are named packages?~~

Similarly, https://www.freshports.org/archivers/py-zstd/#flavors just one flavour `py38` followed by four tables of packages. 

----

I began thinking, ~~https://www.freshports.org/faq.php#package~~ https://www.freshports.org/faq.php#port might benefit from an additional paragraph (imagine a newcomer FreeBSD) including a link out to the FreeBSD Handbook, then realised: 

* [The FreeBSD Project | Chapter 4. Installing Applications: Packages and Ports](https://docs.freebsd.org/en/books/handbook/ports/) no mention of _flav_ in this chapter. 

https://docs.freebsd.org/en/books/handbook/ the table of contents is incomplete – no link to the glossary: 

* https://docs.freebsd.org/en/books/handbook/glossary/

https://docs.freebsd.org/en/books/handbook/glossary/#_f no listing for _flavor_.

Instead, https://docs.freebsd.org/en/books/porters-handbook/flavors/ and now I can make sense of it: 

```text
% grep FLAVORS /usr/ports/devel/llvm-devel/Makefile
FLAVORS=        default lite
FLAVOR?=        ${FLAVORS:[1]}
% grep FLAVORS /usr/ports/graphics/py-cairo/Makefile
% grep FLAVORS /usr/ports/archivers/py-zstd/Makefile
% 
```

----

Where there are no flavours for a port: 

* instead of listing one thing, would it be better to say "none"?

**Comment by dlangille** [comment]
There are flavors for this port:

```
[dan@empty:/usr/ports/graphics/py-cairo] $ make -V FLAVORS
py38 
```

**Comment by grahamperrin** [comment]
So … maybe I *mis*-read between the lines in the FreeBSD Porter's Handbook, https://docs.freebsd.org/en/books/porters-handbook/flavors/#flavors-using

> … To declare a port having multiple flavors, add `FLAVORS` to its Makefile. … 

– from which, I assumed that absence of the declaration = no flavour. 

Re: what's below, is it better to think of every port as having at least one flavour? 

```
root@mowa219-gjp4-8570p:/usr/ports # poudriere ports -u
[00:00:00] Updating portstree "default" with git+https... done
root@mowa219-gjp4-8570p:/usr/ports # cd graphics/py-cairo
root@mowa219-gjp4-8570p:/usr/ports/graphics/py-cairo # make -V FLAVORS
py38 
root@mowa219-gjp4-8570p:/usr/ports/graphics/py-cairo # grep FLAVORS Makefile 
root@mowa219-gjp4-8570p:/usr/ports/graphics/py-cairo # cd ../../archivers/py-zstd
root@mowa219-gjp4-8570p:/usr/ports/archivers/py-zstd # make -V FLAVORS
py38 
root@mowa219-gjp4-8570p:/usr/ports/archivers/py-zstd # grep FLAVORS Makefile
root@mowa219-gjp4-8570p:/usr/ports/archivers/py-zstd # cd ../../devel/llvm-devel
root@mowa219-gjp4-8570p:/usr/ports/devel/llvm-devel # make -V FLAVORS
default lite
root@mowa219-gjp4-8570p:/usr/ports/devel/llvm-devel # grep FLAVORS Makefile
FLAVORS=        default lite
FLAVOR?=        ${FLAVORS:[1]}
root@mowa219-gjp4-8570p:/usr/ports/devel/llvm-devel # 
```

Clearly, I'm confused (sorry), I might have done better to have a chat in e.g. Discord before raising anything here in GitHub …

**Comment by dlangille** [comment]
Some have no flavors. Chosen at random.

```
[dan@empty:/usr/ports/audio/yell] $ make -V FLAVORS

[dan@empty:/usr/ports/audio/yell] $ 
```

**Comment by dlangille** [comment]
Perhaps all Python ports have at least one flavor?

**Comment by dlangille** [comment]
Found, but not interpreted:
```
[dan@empty:/usr/ports/Mk/Uses] $ grep FLAVORS python.mk 
_PYTHON_FEATURE_FLAVORS=	yes
.if defined(_PYTHON_FEATURE_NOFLAVORS)
.undef _PYTHON_FEATURE_FLAVORS
WARNING+=	"PYTHON_DEFAULT must be a version present in PYTHON2_DEFAULT or PYTHON3_DEFAULT, if you want more Python flavors, set BUILD_ALL_PYTHON_FLAVORS in your make.conf"
# Automatically generates FLAVORS if empty
.if empty(FLAVORS) && defined(_PYTHON_FEATURE_FLAVORS)
_ALL_PYTHON_FLAVORS=	${_VALID_PYTHON_VERSIONS:S/.//:S/^/py/}
_ALL_PYTHON_FLAVORS=	${_PYTHON_VERSIONS:S/.//:S/^/py/}
.  if defined(BUILD_ALL_PYTHON_FLAVORS) || defined(_PYTHON_FEATURE_ALLFLAVORS)
FLAVORS=	${_ALL_PYTHON_FLAVORS}
.      if ${_ALL_PYTHON_FLAVORS:M${_f}} && !${FLAVORS:M${_f}}
.if !empty(FLAVORS)
FLAVORS:=	${FLAVORS} ${_f}
FLAVORS:=	${_f}
.  if !empty(FLAVORS) && empty(FLAVOR)
FLAVOR=	${FLAVORS:[1]}
.if !defined(_PYTHON_FEATURE_FLAVORS) && (${_PYTHON_VERSION_MINIMUM:M3*} || ${_PYTHON_VERSION_MAXIMUM:M2*})
.if defined(_PYTHON_FEATURE_FLAVORS) && ${FLAVOR} == ${FLAVORS:[1]}
.elif !defined(_PYTHON_FEATURE_FLAVORS) && ${_PYTHON_VERSION} == ${PYTHON_DEFAULT}
[dan@empty:/usr/ports/Mk/Uses] $ 

```

**Comment by grahamperrin** [comment]
From <https://github.com/FreshPorts/freshports/issues/280#issuecomment-846009139>

>> A person might tap on table headers e.g. …
> 
> What would you expect to happen there?

I'm not sure. Maybe nothing should happen. 

### Four examples

https://www.freshports.org/devel/llvm-devel/#flavors 

* the first of two tables is headed by the name of the package for the _default_ flavour
* the second table is headed by the name of the package for the _lite_ flavour

– OK so far (in my mind's eye).

https://www.freshports.org/audio/yell/#flavors

– again, OK (to me). A single table, and no flavour to think about. 

https://devgit.freshports.org/archivers/py-zstd/#flavors and https://testgit.freshports.org/archivers/py-zstd/#flavors 

* the fourth table is headed by the name of the package for the sole listed flavour, _py38_
* this, loosely speaking or coincidentally, tallies with the output from `make -v FLAVORS` at https://github.com/FreshPorts/freshports/issues/287#issuecomment-846310288 above. 

https://devgit.freshports.org/graphics/py-cairo/#flavors and https://testgit.freshports.org/graphics/py-cairo/#flavors 

* the third table is headed by the name of the package for the sole listed flavour, _py37_, which does not tally …

----

At this point, I should probably aim to revisit a relevant handbook however (a) it's the early hours (01:10 here); and (b) I'm not a porter :-)

**Comment by dlangille** [comment]
Note, for the last mentioned ports:

```
[dan@empty:/usr/ports/graphics/py-cairo] $ make -v FLAVORS
py38 
```
This differs from the webpage.

Over on the `devgit` box:

```
[dan@devgit-ingress01:/var/db/freshports/ports-jail/var/db/repos/ports/graphics/py-cairo] $ make -v FLAVORS
py38 
```

Same thing.  So why does https://devgit.freshports.org/graphics/py-cairo/#flavors  show `py37`?

That value only gets updated after a commit.  The value is determined by settings in `Mk`. Those values were updated since that commit. 

This is related to 

* #136 
* #131 
* #47

**Comment by dlangille** [comment]
I think you are saying FreshPorts should be stating: `pkg install origin`

**Comment by grahamperrin** [comment]
> I think you are saying FreshPorts should be stating: `pkg install origin`

Maybe, if that's more useful (and doesn't cause astonishment).

**Comment by dlangille** [comment]
Please review: https://devgit.freshports.org/graphics/py-cairo/#add

**Comment by dlangille** [comment]
@jethron Does this look OK to you?

**Comment by dlangille** [comment]
This is now in production.

**Comment by grahamperrin** [comment]
Thanks! 

When I find a suitable explanation of flavours (for the _hopelessly lazy_), I'll make a PR for a link out from https://www.freshports.org/faq.php#port
