### ISSUE TITLE
Ports that aren't really new are in the new ports reports

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#29]
On 22 Oct, we had:

<pre>

 Port count: 26568 http://www.FreshPorts.org/categories.php
New ports:     8 http://www.FreshPorts.org/ports-new.php?interval=today

21 Oct 2016

http://www.freshports.org/devel/libastylej-arduino/
    Source code indenter, formatter, and beautifier (JNI library)

http://www.freshports.org/devel/nspr/
    Platform-neutral API for system level and libc like functions

http://www.freshports.org/www/firefox-i18n/
    Localized interface for Firefox

22 Oct 2016

http://www.freshports.org/audio/raop_play/
    Music file player for Apple Airport Express

http://www.freshports.org/devel/ncurses/
    Library for terminal-independent, full-screen output

http://www.freshports.org/games/openra/
    Multiplayer re-envisioning of early RTS games by Westwood Studios

http://www.freshports.org/security/nmap/
    Port scanning utility for large networks

http://www.freshports.org/security/zenmap/
    GUI frontend for the Nmap scanning utility
<pre>

**Comment by dlangille** [comment]
see also http://twitter.com/RomainTartiere/status/826731282549919745

**Comment by dlangille** [comment]
I think I have a fix for this.

**Comment by woodsb02** [comment]
The not-so-new port reports appear to be tied to commits to the quarterly branches.

**Comment by dlangille** [comment]
This fix has been committed and is now in production, after sitting in dev for months.

**Comment by dlangille** [comment]
Closing based on previous comment.
