### ISSUE TITLE
Account Creation - CAPTCHA Won't Validate

### ISSUE THREAD

**Issue by Zzyzx-Wolfe** [FreshPorts/freshports#294]
Greetings,

I've tried several times to create a freshports.org account, but every time I try to create it, it tells me that the CAPTCHA is invalid.
![Screenshot 2021-05-29 011934](https://user-images.githubusercontent.com/179292/120063473-2e19eb80-c01c-11eb-91e8-02fc4f71a87b.png)
![Screenshot 2021-05-29 011943](https://user-images.githubusercontent.com/179292/120063488-34a86300-c01c-11eb-9f7a-bed6357e7907.png)

I don't think I am doing anything obviously dumb, but it wouldn't be the first time I was wrong about that.

Thanks in advance for your help,
Zzyzx

**Comment by Zzyzx-Wolfe** [comment]
Hm, well, I was able to create the account if I used an Incognito window, but the only thing being blocked was Google Analytics. Is that necessary for the CAPTCHA to function correctly?

**Comment by dlangille** [comment]
Good point. Off hand, I do not see why they should be connected.

**Comment by dlangille** [comment]
Looking at the code, the solution is stored in a session variable, which is not related to analytics at all.

**Comment by dlangille** [comment]
@Zzyzx-Wolfe How are you blocking Google Analytics? That might help with my testing.

**Comment by Zzyzx-Wolfe** [comment]
@dlangille It turns out it wasn't tracker blocking, but an old extension I still had installed for some reason that has since been delisted. If you're particularly interested in finding the interaction, it's [Manage Twitter Engagement](https://extpose.com/ext/63669/en-US), but at least for me, I'm removing this extension since it seems dead anyway.

**Comment by dlangille** [comment]
Huh.  I wonder how that interfered.
