### ISSUE TITLE
Lay-out of page is skewed

### ISSUE THREAD

**Issue by ronaldklop** [FreshPorts/freshports#303]
Hi. See https://www.freshports.org/commit.php?category=x11&port=bemenu&files=yes&message_id=93414bdebea80cccd69fa948674d6bd654fb6734

The tables are are not aligned nicely anymore.

**Comment by dlangille** [comment]
NOTE: if it's not skewed when you first load, reload. This is a problem on server side related to caching.

When pulling the three sections of the page from cache, something is missing.  Either it's something which should be cached, or something missed when the cached pieces are sticthed together.

**Comment by dlangille** [comment]
Here is the change I just made in dev.  @ronaldklop : please look around https://devgit.freshports.org/

```
[dan@devgit-nginx01:~/www] $ git diff
diff --git a/www/commit.php b/www/commit.php
index 5e8f13ff..b507621b 100755
--- a/www/commit.php
+++ b/www/commit.php
@@ -312,13 +312,13 @@
                                                $HTML .=  "<p>$ShowAllFilesURL</p>";
                                        } # files == 'y'
 
+                                       $HTML .= "\n</table></td>\n";
+
                                        # save the HTML
                                        if ($DoTheSave) {
                                                $Cache->CacheDataSet($HTML);
                                                $Cache->AddCommit($message_id, $clean['category'], $clean['port'], $files);
                                        }
-
-                                       $HTML .= "\n</table></td>\n";
                                } // $HTML != ''
                        } # count($message_id_array)
 
[dan@devgit-nginx01:~/www] $ 
```

**Comment by ronaldklop** [comment]
Hi, looks good to me. For completeness I add a screenshot which I could not upload from my mobile phone in the first comment.

![4E7EF69E-5B30-4112-9641-ACA666EC7387](https://user-images.githubusercontent.com/28505882/122534490-dbcc5900-d022-11eb-9188-bac7a7a5374b.png)

BTW: I have another example of the same page which gives a HTTP 503 on www and works fine on devgit. Related? Or just a good reason to make a new production deploy. ;-) Thanks for you work on this.
https://www.freshports.org/commit.php?category=security&port=greenbone-security-assistant&files=yes&message_id=dc5371babb9ecb0effe15ece16356e1bb34a2206

**Comment by dlangille** [comment]
So I can keep track of it, I'll reopen this until it is confirmed fixed in production.

**Comment by dlangille** [comment]
This fix is now in production.

Those 503 errors are not related. The server got hit hard by some folks pulling stuff way faster than usual.
