### ISSUE TITLE
Search queries return duplicate results

### ISSUE THREAD

**Issue by feld** [FreshPorts/freshports#31]
Some (many? all?) search queries are returning duplicate results.

example:

http://www.freshports.org/search.php?stype=name&method=match&query=bind9&num=10&orderby=category&orderbyupdown=asc&search=Search&format=plaintext&minimal=1

produces the following output:

dns/bind9-devel
dns/bind910
dns/bind910
dns/bind911
dns/bind911
dns/bind99
dns/bind99

**Comment by dlangille** [comment]
Have a look at http://dev.freshports.org/search.php?stype=name&method=match&query=bind9&num=10&orderby=category&orderbyupdown=asc&search=Search&minimal=1&branch=2016Q4

You'll also see a drop down list box for selecting branch.  It defaults to HEAD.

**Comment by dlangille** [comment]
This is now in production.
