### ISSUE TITLE
distinfo sections are sometimes too wide

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#320]
I vaguely recall discussing this somewhere a few weeks ago …

At, for example, <https://www.freshports.org/editors/aee#distinfo> the width of the content makes the page uncomfortably wide. 

![image](https://user-images.githubusercontent.com/192271/126743351-04329be8-1a04-4279-ba48-70aeb5bf05fc.png)

**Comment by dlangille** [comment]
Perhaps #35 or #63 can help.

**Comment by dlangille** [comment]
@jethron this is definitely something you'd be better at than me.

**Comment by dlangille** [comment]
Reopening until this hits production

**Comment by dlangille** [comment]
@grahamperrin please compare with https://dev.freshports.org/editors/aee#distinfo

This should hit production soon.

**Comment by dlangille** [comment]
Good in prod.

**Comment by grahamperrin** [comment]
Thanks, and apologies for missing the comment on 25th August.
