### ISSUE TITLE
404:  Warning: htmlentities() expects parameter 1 to be string, resource given in /usr/local/www/freshports/rewrite/missing.php on line 38

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#329]
When an invalid address is entered, for example <https://www.freshports.org/audio/multimedia/>, 

![image](https://user-images.githubusercontent.com/192271/130322431-fe417168-7625-4ca2-a21a-7564697f7ee2.png)

The suggestions to look elsewhere are good, but is it proper for the warning to appear?

**Comment by dlangille** [comment]
It is only repeatable if logged in.  Thanks.

**Comment by dlangille** [comment]
Reopening this until it hits procuction.

**Comment by dlangille** [comment]
Fixed in prod.
