### ISSUE TITLE
/commits.php seems to be redundant now

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#337]
I see no need to keep /commits.php - perhaps we should delete it and redirect to the home page.

The page is broken in more than one way. Rather than fix it, let's remove it.

It is lightly used; about 30 times a day:

```
$ grep -c 'GET /commits.php' freshports.org-access.log.?
freshports.org-access.log.0:30
freshports.org-access.log.1:30
freshports.org-access.log.2:35
freshports.org-access.log.3:30
freshports.org-access.log.4:35
freshports.org-access.log.5:54
freshports.org-access.log.6:41
freshports.org-access.log.7:34
freshports.org-access.log.8:28
freshports.org-access.log.9:34
```

**Comment by aturetta** [comment]
I can add that /commit.php is also not working correctly, the title says "100 most recent commits" but then it shows maybe 10
I was going to open an issue

**Comment by debdrup** [comment]
Since I'm using [this RSS feed](https://www.freshports.org/backend/news.php?flavor=new), I would also like to make sure that part of the process of removing commits.php also checks to make sure that the RSS feed in question isn't affected.

**Comment by dlangille** [comment]
> I can add that /commit.php is also not working correctly, the title says "100 most recent commits" but then it shows maybe 10
> I was going to open an issue

I don't know what's up with that.

**Comment by dlangille** [comment]
> Since I'm using [this RSS feed](https://www.freshports.org/backend/news.php?flavor=new), I would also like to make sure that part of the process of removing commits.php also checks to make sure that the RSS feed in question isn't affected.

You can test that out now at dev.freshports.org where /commits.php redirects permanently to / via:

```
  rewrite ^/commits.php / permanent;
```

**Comment by debdrup** [comment]
> You can test that out now at dev.freshports.org where /commits.php redirects permanently to / via:
> 
> ```
>   rewrite ^/commits.php / permanent;
> ```

It looks to me like it's still working, at least based on the XML that I got redirected when grabbing the feed URI.

**Comment by dlangille** [comment]
What is the URL you used?

**Comment by debdrup** [comment]
> What is the URL you used?

I just changed the www in [the link above](https://www.freshports.org/backend/news.php?flavor=new) to dev, and it grabbed an XML file that looks like an RSS feed to me.

**Comment by dlangille** [comment]
Thanks.  I think we're save to roll this one out to test, stage, and prod.

**Comment by dlangille** [comment]
This is now implemented on test, stage, and prod.
