### ISSUE TITLE
Link to bug tracker

### ISSUE THREAD

**Issue by ari** [FreshPorts/freshports#338]
It used to exist before the move to bugzilla. Could we have it back please?

**Comment by dlangille** [comment]
Sure. Can you give me an example please.

**Comment by ari** [comment]
https://bugs.freebsd.org/bugzilla/buglist.cgi?quicksearch=net%2Fhaproxy

**Comment by dlangille** [comment]
I went to https://www.freshports.org/net/haproxy and clicked on the icon next to the skull. It is this link:

https://bugs.freebsd.org/bugzilla/buglist.cgi?component=Individual%20Port%28s%29&list_id=442680&product=Ports%20%26%20Packages&query_format=advanced&resolution=---&short_desc=net%2Fhaproxy&short_desc_type=allwordssubstr

The URLs are not identical and they produce the same list of PRs.

At https://www.freshports.org/faq.php search for this text:

`Find Bugs: a link to search for open Problem Reports (issues/bugs) for this port`

**Comment by dlangille** [comment]
@ari is that link what you need? Is there another link you had in mind?

**Comment by ari** [comment]
Ah, I didn't see that icon. Yes, that's perfect. There is a lot of great things about Freshport, but usability of the UI isn't one of them... thanks for providing this tool.

**Comment by dlangille** [comment]
I'm happy for anyone to make changes to the UI.
