### ISSUE TITLE
Some ports (those on branches?) result in more-than-one-row error on upload to watch list.

### ISSUE THREAD

**Issue by CambridgeDave** [FreshPorts/freshports#34]
When uploading a watch list, if it contains certain ports, the following error is returned, and the watch list is unchanged:

`ERROR: more than one row returned by a subquery used as an expression CONTEXT: SQL statement "UPDATE watch_list_staging SET element_id = ( SELECT ports.element_id FROM ports, categories, element WHERE element.name = watch_list_staging.port AND categories.name = watch_list_staging.category AND ports.element_id = element.id AND ports.category_id = categories.id) WHERE user_id = UserID" PL/pgSQL function watchliststagingprocess(integer) line 17 at SQL statement sql = select WatchListStagingProcess(13320)`

I find that any of these ports in the watch list result in the problem:

- dns/bind911
- security/ca_root_nss
- ftp/curl
- multimedia/ffmpeg
- devel/jsoncpp
- www/mod_php56
- lang/perl5.24
- lang/php56 (and probably all its slave ports)
- ports-mgmt/pkg
- security/sudo

**Comment by dlangille** [comment]
This is related to branches.

**Comment by dlangille** [comment]
I think I have fixed this. Please verify.

**Comment by CambridgeDave** [comment]
Yes, this looks to be fixed for me now.  Thanks!
