### ISSUE TITLE
Purpose of "more..." under search input field

### ISSUE THREAD

**Issue by Tectu** [FreshPorts/freshports#342]
Below the `Enter Keywords` input box in the `Search` container, there is some text reading `more...`. However, it appears to be just static text doing pretty much nothing for the user.

I´d like to understand what the purpose of this is? Is this an upcoming feature? Or is this some left-over relic from past times?

**Comment by Tectu** [comment]
Yep, talking about the good old https://www.freshports.org :)

I think I was just confused - the link is indeed there (and does what I expected it to do). However, it isn't a link when displaying current search results. I'm not sure whether that is intentional or not.
I was looking for a package, used the search box on the right hand side, the results showed up (`search.php`) and then the `more...` link is gone - it's just a static text.

**Comment by dlangille** [comment]
@Tectu it sounds like `more...` should not be displayed at all when on the search page.
