### ISSUE TITLE
Seeking within package messages

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#343]
Please, might https://www.freshports.org/search.php be adapted to allow search within package messages? 

(Am I missing something?)

Context, for example <https://forums.FreeBSD.org/posts/537144>

> … There was formerly a requirement for procfs (but not fdescfs) in …, but I'm no longer seeing either of those requirements in any package other than …

**Comment by grahamperrin** [comment]
Seeking `/dev/fd`

_dev_ <https://dev.freshports.org/search.php?stype=pkg-message&method=match&query=%2Fdev%2Ffd&num=20&orderby=category&orderbyupdown=asc&search=Search&format=plaintext&branch=head> is OK

_www_ <https://www.freshports.org/search.php?stype=pkg-message&method=match&query=%2Fdev%2Ffd&num=20&orderby=category&orderbyupdown=asc&search=Search&format=plaintext&branch=head>

```text
<br />
<b>Warning</b>:  pg_query_params(): Query failed: ERROR:  column &quot;pkgmessage_textsearchable2&quot; does not exist
LINE 8:         pkgmessage_textsearchable2 @@ websearch_to_tsquery($...
                ^
HINT:  Perhaps you meant to reference the column &quot;ports.pkgmessage_textsearchable&quot;. in <b>/usr/local/www/freshports/classes/ports_by_pkg_message.php</b> on line <b>58</b><br />
SQL ERROR
```

**Comment by dlangille** [comment]
That's a lack of implementing [what I wrote about ealier](https://github.com/FreshPorts/freshports/issues/343#issuecomment-950333009).

Let's go do that now.

**Comment by dlangille** [comment]
@grahamperrin - now `www` works

**Comment by grahamperrin** [comment]
Cool! Thanks. 

I have hidden some comments as _resolved_. 

At a glance: https://github.com/FreshPorts/freshports/issues/343#issuecomment-950361391 not yet resolved, for example `www` https://www.freshports.org/search.php?stype=pkg-message&method=match&query=procfs&num=50&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head finds nothing.

**Comment by grahamperrin** [comment]
At <https://dev.freshports.org/search.php>:

* seeking `linux_enable="YES"` finds nothing
* seeking `linux_enable` **does** find ports for which the package message includes `linux_enable="YES"`

**Comment by grahamperrin** [comment]
_dev_ search results for `linux_enable` include www/firefox, however <https://www.freshports.org/www/firefox/#message>: 

* includes the word _Linux_
* does not include the phrase _linux_enable_

**Comment by dlangille** [comment]
This seems better now on dev but still completely not working on prod.

**Comment by dlangille** [comment]
So many things in here. Not sure we've drive them all.

**Comment by dlangille** [comment]
I think it's all done.

**Comment by grahamperrin** [comment]
https://github.com/FreshPorts/freshports/issues/343#issuecomment-1008229480

> … search results for `linux_enable` …

<https://www.freshports.org/search.php?stype=pkg-message&method=match&query=linux_enable&num=100&orderby=port&orderbyupdown=asc&search=Search&format=html&branch=head>

* finds 32 ports
* the sought phrase actually appears in 8 of the 32.

If it's _wontfix_ as an edge case, that's fine.
