### ISSUE TITLE
visible <a id="updating">Notes from UPDATING</a>

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#348]
At (for example) <https://www.freshports.org/editors/calligra/> and _dev_ <https://dev.freshports.org/editors/calligra/>

![image](https://user-images.githubusercontent.com/192271/138994221-c906d8ba-dc3c-4e46-bb35-98468772d0a4.png)

**Comment by dlangille** [comment]
I have this fixed on the [freshports_PageBannerText](https://github.com/FreshPorts/freshports/tree/freshports_PageBannerText) branch.

**Comment by dlangille** [comment]
Looks fixed now.

**Comment by grahamperrin** [comment]
Fix confirmed, thanks. 

> Please try again. on dev.

(Sorry, I missed that.)
