### ISSUE TITLE
Cases where specifying the origin with pkg-install(8) will result in multiple flavours

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#349]
Spun off from [259672 – benchmarks/phoronix-test-suite all three flavours result from pkg install benchmarks/phoronix-test-suite](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259672) (not a bug); follow-up to https://github.com/FreshPorts/freshports/issues/287

From <https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259672#c1>: 

> … This is a general issue when you use origin instead of package name with pkg.
> 
> With FLAVOURS, you end up having 3 packages with the same origin, hence pkg will install all packages with that origin.
> 
> I guess there is room for improvement, but it's not specific to this port/package. …

<https://github.com/FreshPorts/freshports/issues/287#issuecomment-850650943> imagined an enhancement to <https://www.freshports.org/faq.php#port>, however I'm uncertain how to phrase things. 

[php applications, php flavors and freshports](https://lists.freebsd.org/archives/freebsd-ports/2021≥-November/000970.html) uses the phrase _1:n relationship between origin and packages_. 

Where `n ≥ 2` for a port, might the FreshPorts page for the port drop a hint that `pkg install ⋯/⋯` can lead to unexpected results (or words to that effect)?

With [www/falkon](https://www.freshports.org/www/falkon/) as an example: 

```text
% sudo pkg install -n -r FreeBSD www/falkon
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 2 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        falkon: 3.1.0_1 [FreeBSD]
        falkon-qtonly: 3.1.0_1 [FreeBSD]

Number of packages to be installed: 2

The process will require 20 MiB more space.
4 MiB to be downloaded.
% 
```

A PHP-related example: 

```text
% sudo pkg install -n devel/arcanist
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
Updating poudriere repository catalogue...
poudriere repository is up to date.
All repositories are up to date.
The following 22 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        arcanist-lib-php73: 20210113_1 [FreeBSD]
        arcanist-lib-php74: 20210113_1 [FreeBSD]
        arcanist-lib-php80: 20210113_1 [FreeBSD]
        arcanist-php73: 20210113_1 [FreeBSD]
        arcanist-php74: 20210113_1 [FreeBSD]
        arcanist-php80: 20210113_1 [FreeBSD]
        oniguruma: 6.9.7.1 [FreeBSD]
        php73: 7.3.32 [FreeBSD]
        php73-curl: 7.3.32 [FreeBSD]
        php73-dom: 7.3.32 [FreeBSD]
        php73-hash: 7.3.32 [FreeBSD]
        php73-json: 7.3.32 [FreeBSD]
        php73-mbstring: 7.3.32 [FreeBSD]
        php73-simplexml: 7.3.32 [FreeBSD]
        php73-zlib: 7.3.32 [FreeBSD]
        php74-mbstring: 7.4.25 [FreeBSD]
        php80: 8.0.12 [FreeBSD]
        php80-curl: 8.0.12 [FreeBSD]
        php80-dom: 8.0.12 [FreeBSD]
        php80-mbstring: 8.0.12 [FreeBSD]
        php80-simplexml: 8.0.12 [FreeBSD]
        php80-zlib: 8.0.12 [FreeBSD]

Number of packages to be installed: 22

The process will require 94 MiB more space.
15 MiB to be downloaded.
% 
```

<https://www.freebsd.org/cgi/man.cgi?query=pkg-install&sektion=8&manpath=Ports>

**Comment by dlangille** [comment]
All FreshPorts can do is make people aware of different flavors. Something like this:

```
To install the port:

cd /usr/ports/benchmarks/phoronix-test-suite/ && make install clean

To add the package, run one of these commands:

* pkg install benchmarks/phoronix-test-suite
* pkg install phoronix-test-suite-php74

NOTE: This is a PHP port. Instead of phoronix-test-suite-php74 listed in the above command, you can pick from the names under the Packages section.
```

Earlier today, that modification was made. I think it should be displayed for all ports with flavors.

**Comment by dlangille** [comment]
I lost that code change.

Now the fix is:

`NOTE: If this package has multiple flavors (see below), then use one of them instead of the name specified above.`
