### ISSUE TITLE
Commit history does not display the author’s name

### ISSUE THREAD

**Issue by thierry-FreeBSD** [FreshPorts/freshports#352]
When a commit with a specific author-name is pushed, this author’s name is not displayed: e.g. https://www.freshports.org/cad/opencascade/ at 12 Nov 2021 17:51:09.

Only the committer’s name and the reporter ("Reported by") are displayed.

**Comment by dlangille** [comment]
The good news: it is being captured.

```
freshports.devgit=# select author_name, author_email from commit_log where message_id = '4e0ab0ccde840334aaf7ac9a9b8250d9809ad7dc';
 author_name |   author_email    
-------------+-------------------
 Craig Leres | leres@FreeBSD.org
(1 row)

freshports.devgit=# 

```

**Comment by dlangille** [comment]
@thierry-FreeBSD how does https://dev.freshports.org/cad/opencascade/#history look?

**Comment by dlangille** [comment]
See also https://dev.freshports.org/commit.php?category=cad&port=opencascade&files=yes&message_id=4e0ab0ccde840334aaf7ac9a9b8250d9809ad7dc

**Comment by dlangille** [comment]
For future reference, I'll add some screen shots.

**Comment by dlangille** [comment]
This is what it looks like on watch.php

![Screen Shot 2021-11-14 at 3 52 58 PM](https://user-images.githubusercontent.com/1626436/141698385-6acdd288-85b3-4e42-acfa-88634de965f6.png)

**Comment by thierry-FreeBSD** [comment]
This is fine, thanks!

**Comment by dlangille** [comment]
After reviewing, I decided not to show 'Committer:' - context indicates that.

**Comment by dlangille** [comment]
This is now in production.
