### ISSUE TITLE
RSS feed quarterly is empty since git 

### ISSUE THREAD

**Issue by ronaldklop** [FreshPorts/freshports#354]
[](https://www.freshports.org/backend/rss2.0.php?branch=quarterly) 

result is empty rss 
This happening since the svn git conversion afaik

**Comment by dlangille** [comment]
Most of this has been discussed here:

https://twitter.com/rjvvliet/status/1516457811152195589

**Comment by dlangille** [comment]
Closing based on success declared at https://twitter.com/ronnie_bonkers/status/1518230816333123589
