### ISSUE TITLE
patch order presentation on freshports.org, dnsmasq commits of 2021-12-11

### ISSUE THREAD

**Issue by mandree** [FreshPorts/freshports#355]
IRC Transcript of 2021-12-11, UTC times
(11:06:28) mandree: dvl: freshports.org picked up the two dns/dnsmasq commits today in the wrong order. I think the mails were sent out in the wrong order, too. Any chance to get commits in Git graph order without exploding memory and time complexity on your end?
(11:07:42) mandree: also, on the 2.86_1,1 commit, the URL grabber malfunctioned, the commit message had a bare URL
(14:46:50) dvl: mandree: FreshPorts used to process email, but now it pulls directly from git.
(14:48:12) dvl: mandree: I see them now. I think this is a display issue, not a processing issue. Notice the version at the top of the page.
(14:49:22) dvl: mandree: It is an issue to fix though. Could you please create an issue for me? [...]

**Comment by dlangille** [comment]
@mandree fixed now, I think by another issue.

**Comment by dlangille** [comment]
@mandree all OK now?

**Comment by mandree** [comment]
I seem to recall that I checked last winter, and I think it was fixed. Let's close this one and open a new one if it breaks again.
