### ISSUE TITLE
URL grabber failure

### ISSUE THREAD

**Issue by mandree** [FreshPorts/freshports#356]
Visible on 2.86_1,1 of https://www.freshports.org/dns/dnsmasq/ - note the partial HTML tag that ends in `REL="NOFOLLOW">`, the original message just contained the bare https://... link (with the embedded `@` if that matters).

```dns/dnsmasq: fix error "config error is REFUSED (EDE: not ready)"

Fix --address=/#/...... which was lost in 2.86

ML message:
dnsmasq-discuss@lists.thekelleys.org.uk/msg15508.html" REL="NOFOLLOW">https://www.mail-archive.com/dnsmasq-discuss@lists.thekelleys.org.uk/msg15508.html

Git commit:
https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=26bbf5a314d833beaf0f147d24409969f05f3dba

PR:		260331
Obtained from:	Simon Kelley (upstream maintainer)
```

IRC Transcript of 2021-12-11, UTC times
(11:06:28) mandree: dvl: freshports.org picked up the two dns/dnsmasq commits today in the wrong order. I think the mails were sent out in the wrong order, too. Any chance to get commits in Git graph order without exploding memory and time complexity on your end?
(11:07:42) mandree: also, on the 2.86_1,1 commit, the URL grabber malfunctioned, the commit message had a bare URL
(14:46:50) dvl: mandree: FreshPorts used to process email, but now it pulls directly from git.
(14:48:12) dvl: mandree: I see them now. I think this is a display issue, not a processing issue. Notice the version at the top of the page.
(14:49:22) dvl: mandree: It is an issue to fix though. Could you please create an issue for me? [...]

**Comment by dlangille** [comment]
@mandree this sounds like another issue I read somewhere. Has this been fixed? I think so, yes, https://www.freshports.org/dns/dnsmasq/ looks OK for commits on 2021-12-11

**Comment by dlangille** [comment]
@mandree the URL issue remains. Perhaps I need a better URL-grabber which is PHP-friendly. Got one? Or any one, not necessarily PHP.

**Comment by dlangille** [comment]
Perhaps https://github.com/vstelmakh/url-highlight

**Comment by dlangille** [comment]
Here is my first test.

new code: https://dev.freshports.org/htmlify-test.php
old code: https://test.freshports.org/htmlify-test.php

**Comment by dlangille** [comment]
Raised issue at https://github.com/vstelmakh/url-highlight/issues/40

**Comment by dlangille** [comment]
@mandree compare:

* https://dev.freshports.org/dns/dnsmasq/#history
* https://www.freshports.org/dns/dnsmasq/#history

**Comment by dlangille** [comment]
Seems fixed now.

My next challenge: how to port this.

**Comment by dlangille** [comment]
I have also tried https://github.com/iamcal/lib_autolink  - found an issue with emails, raised https://github.com/iamcal/lib_autolink/issues/23
