### ISSUE TITLE
Duplication/multiplication within watchlist categories

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#357]
<https://www.freshports.org/port-watch.php?category=editors&wlid=19254>, for example: 

![image](https://user-images.githubusercontent.com/192271/148440357-6a510653-5ba2-4c90-aaa7-9216cd6f589f.png)

**Comment by grahamperrin** [comment]
I randomly chose to click the name of one that appeared in triplicate: 

https://www.freshports.org/deskutils/freeplane/

– wondering whether there might be, within the page, a clue to the cause. 

(Flavours? Python? And so on.) At a glance, I see no clue.

**Comment by dlangille** [comment]
My first suspicion is branches.

**Comment by dlangille** [comment]
It was branches:  Fix here.  Changes query from using `ports` (all branches) to `ports_active` (originally just non-deleted ports, but now it's non-deleted ports on head).

```
diff --git a/www/port-watch.php b/www/port-watch.php
index 5199ac14..e6567253 100644
--- a/www/port-watch.php
+++ b/www/port-watch.php
@@ -150,14 +150,14 @@ $sql = "
   SELECT element.id, 
          element.name    AS port, 
          element.status,
-         CASE WHEN ports.category_id = $1 THEN '' ELSE '&nbsp;<sup>*</sup>' END AS virtual,
+         CASE WHEN P.category_id = $1 THEN '' ELSE '&nbsp;<sup>*</sup>' END AS virtual,
          PRIMARY_CATEGORY.name as primary_category
-    FROM ports, ports_categories, element, categories PRIMARY_CATEGORY
+    FROM ports_active P, ports_categories, element, categories PRIMARY_CATEGORY
    WHERE ports_categories.category_id = $1
-     AND ports_categories.port_id     = ports.id
-     AND ports.element_id             = element.id
+     AND ports_categories.port_id     = P.id
+     AND P.element_id                 = element.id
      AND element.status               = 'A'
-     AND PRIMARY_CATEGORY.id          = ports.category_id
+     AND PRIMARY_CATEGORY.id          = P.category_id
 ORDER BY port, primary_category";
 
 if ($Debug) echo "<pre>$sql</pre>\n";
@@ -213,7 +213,7 @@ if ($numrows) {
       }
 
       if ($Row == 1) {
-         $HTML .= '<td clss="vtop nowrap">';
+         $HTML .= '<td class="vtop nowrap">';
       }
 
       $HTML .= '<input type="checkbox" name="ports[]" value="'. htmlentities($rows[$i]["id"]) .'"';
[22:57 dev-nginx01 dan ~/www] % 
```

While here, fix an alignment issue caused by typing `clss` instead of `class` - see 5effffd97fc96c91c635fd188b6098d7579ae501

**Comment by grahamperrin** [comment]
Thanks. 

`dev` <https://dev.freshports.org/port-watch.php?category=editors&wlid=19254> looks good, at a glance (down from _926_, in the opening post, to _347 ports found (297 primary, 50 secondary)_.)

`www` <https://www.freshports.org/port-watch.php?category=editors&wlid=19254> finds _1661_, I guess that this will drop when the fix lands in production.

**Comment by dlangille** [comment]
Should now be on production with https://github.com/FreshPorts/freshports/releases/tag/2.5.1.3

Thank you
