### ISSUE TITLE
Ports do not display which architectures they work on

### ISSUE THREAD

**Issue by yoshicool** [FreshPorts/freshports#36]
There are several ports that are restricted to only certain architectures.  I know that Openjdk (for example) is restricted to i386, AMD64.

**Comment by dlangille** [comment]
Thanks for raising this on [Twitter](http://twitter.com/yoshicool/status/825780064713314308).

This was about 10 lines of code to display on the website.  The values were already in the database.  How does the [DEV](http://dev.freshports.org/java/openjdk7/) website look now?  All pages should now display those values.

**Comment by yoshicool** [comment]
Looks good to me, thanks!

**Comment by dlangille** [comment]
I'll send this to production soon.

**Comment by dlangille** [comment]
This is now in production.  See it?

**Comment by yoshicool** [comment]
I see it.  Looks good.  Thanks a ton!
