### ISSUE TITLE
maia maia-1.0.4_9 Unknown encoding 'UTF-8

### ISSUE THREAD

**Issue by FlorianMueller1900** [FreshPorts/freshports#362]
Hi,

I have recently installed maia 1.0.4_9 with 
portmaster -dG --no-confirm security/maia

        Upgrade of maia-1.0.4_8 to maia-1.0.4_9

and afterwards I got in /var/log/maillog error messages like the following

Apr 30 07:08:47 mail postfix/smtp[1249]: 273BE4B15F4: to=<user@domain.tld>, relay=127.0.0.1[127.0.0.1]:10024, delay=2561, delays=2561/0/0/0.14, dsn=4.5.0, status=deferred (host 127.0.0.1[127.0.0.1] said: 451 4.5.0 Error in processing, id=99932-03, mime_decode-1 FAILED: Unknown encoding 'UTF-8;' at /usr/local/sbin/maiad line 3837, <GEN14> line 114. (in reply to end of DATA command))

Such errors appear for e-mails sent from thunderbird and roundcube.
The system has the following software installed
FreeBSD 12.3-RELEASE-p5 FreeBSD 12.3-RELEASE-p5 GENERIC  amd64
postfix-3.7.2,1
mysql80-client-8.0.28_1
clamav-0.104.2_2,1
spamassassin-3.4.5
dovecot-2.3.18_1
dovecot-pigeonhole-0.5.18

The database is also under mysql80-server, but on another machine.

postconf shows 
"smtputf8_enable = yes"

maiad rusns as vscan which has the following in its profile definition
LANG="en_US";	export LANG
LC_ALL=$LANG.UTF-8;	export LC_ALL

The  CHARACTER_SET_NAME for the table maia_mail and the column subject is
+--------------------+
| CHARACTER_SET_NAME |
+--------------------+
| utf8mb4            |
+--------------------+

In order to fix the problem I had to drongrade maia to
maia-1.0.4_7
installed previously from ports.

Kind regards,

**Comment by dlangille** [comment]
Sorry, we don't help with ports here. For that, you want the [ports mailing list](https://lists.freebsd.org/subscription/freebsd-ports) or the [FreeBSD bug reporting system](https://bugs.freebsd.org/bugzilla/enter_bug.cgi?component=Individual%20Port%28s%29&product=Ports%20%26%20Packages).

**Comment by eekay35** [comment]
Don't want to re-open this but figured I'd let you know this is a known issue with the most recent version of Maia-Mailguard. See https://github.com/technion/maia_mailguard/issues/88 for more info.
