### ISSUE TITLE
Add links to Codeberg, GitHub and GitLab mirrors; attention to other icons

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#363]
Please, is this feasible? 

For example, currently at <https://www.freshports.org/sysutils/fusefs-ntfs/#history>: 

![image](https://user-images.githubusercontent.com/192271/170634494-aa5ecc02-e0f2-4296-98ad-9235a9b52da2.png)

* there's a link to <https://cgit.freebsd.org/ports/commit/?id=2ff06ffe8797c36db433ae5a2ab53a8410086a53>
* I'd prefer a link to <https://github.com/freebsd/freebsd-ports/commit/2ff06ffe8797c36db433ae5a2ab53a8410086a53>
* other users might prefer a link to <https://gitlab.com/FreeBSD/freebsd-ports/-/commit/2ff06ffe8797c36db433ae5a2ab53a8410086a53>

The one icon to have a particular effect, depending on whether the user prefers the canonical cgit view or one of the mirrors. 

Thanks

**Comment by dlangille** [comment]
For logged in users, I think that's entirely possible.

I'm under severe time constraints for the next coming months. Anyone can mock that up, create code, etc.  I can grant access to dev environments for testing.

**Comment by rwp0** [comment]
I was going to open an issue saw this searching so adding my thoughts here:

I'd also like to have a GitHub instead (or in addition to) to git

https://cgit.freebsd.org/ports/tree/databases/mysqlbackup 

https://github.com/freebsd/freebsd-ports/tree/main/databases/mysqlbackup

![image](https://user-images.githubusercontent.com/68062695/188111501-160881a2-d159-410d-829b-16df0f8b5034.png)

Considering that GitHub's UI is more convenient for many, and that FreeBSD has official GitHub mirrors, GH should be integrated into FreshPorts, I think.

**Comment by dlangille** [comment]
For the home page, I like the idea of both links: `cgit : github` (e.g. https://dev.freshports.org/cad/opencascade/)

Why? This approach is code only. No database changes. No setting default values, no changing the web UI to capture preferences, etc.

I'll tackle links from commits soon.

**Comment by dlangille** [comment]
Commits at https://dev.freshports.org now display links to cgit, github, and gitlab.

**Comment by dlangille** [comment]
Wanted:

* icon for svnweb
* icon for homepage

**Comment by grahamperrin** [comment]
Neat! Thanks. 

A slip of the finger prevented me from tidying this, but the general idea is to have the home page first, and demote SVN (least used) to the end: 

![image](https://user-images.githubusercontent.com/192271/190921963-6ffa534d-d29f-4198-9234-5eec01276126.png)

**Comment by grahamperrin** [comment]
The home icon there is `&#127968;` _HOUSE BUILDING_. Found by seeking _house_ in KCharSelect. It might look odd on computers other than mine, I have no idea (haven't checked). 

Basically, have a home icon for the home page. 

I'm still not keen on the icon that's currently used for Cgit, is there a similar icon that would look OK rotated 45° counterclockwise? For it to appear more upright, with horizontals and verticals.

**Comment by grahamperrin** [comment]
Googling _software branch_ led, strangely, to this (converted to PNG): 

![branch_29788_logo_1641381625_f7qw0](https://user-images.githubusercontent.com/192271/190922980-97c3d852-1c2a-47c8-8eba-8b0909b4a497.png)

Origin: <https://www.saasworthy.com/product/branch-remote>, apparently it was used a couple of years ago at `www.branch.gg` <https://web.archive.org/web/20200913011222/https://www.branch.gg/>. I don't know the true origin, copyright etc., but a Yandex image search finds it at a few other sites: 

![image](https://user-images.githubusercontent.com/192271/190923084-aac4976a-e1b0-4e4a-953a-8e2c4475fc45.png)

**Comment by grahamperrin** [comment]
> … not keen on the icon that's currently used for Cgit, … appear more upright, with horizontals and verticals.

Lazy find: [Arrow branch Icon | Fugue Iconset | Yusuke Kamiyamane](https://iconarchive.com/show/fugue-icons-by-yusuke-kamiyamane/arrow-branch-icon.html) from <https://iconarchive.com/search?q=branch>. 

Food for thought: 

![image](https://user-images.githubusercontent.com/192271/190923317-dae418ec-eac7-48ea-854a-10bf80c09b29.png)

– from [Arrow Fork Icon | Line Iconset | IconsMind](https://iconarchive.com/show/outline-icons-by-iconsmind/Arrow-Fork-icon.html)

> License: Linkware (Backlink to http://www.iconsmind.com/ required)

**Comment by dlangille** [comment]
This is what we have now on dev.freshports.org

![Screen Shot 2022-09-18 at 4 37 17 PM](https://user-images.githubusercontent.com/1626436/190927280-80aeddde-7140-431d-9654-b1a3cb33c692.png)

**Comment by grahamperrin** [comment]
> … what we have now on dev.freshports.org …

Very nice, thanks!

----

(Much better than what I originally imagined: a single icon, that would refer to one of the three Git mirrors, depending on the preference of the logged-in user.)

**Comment by grahamperrin** [comment]
Experimenting (compare with the original shot at <https://github.com/FreshPorts/freshports/issues/363#issue-1250354300>): 

![image](https://user-images.githubusercontent.com/192271/190951862-f65fc455-a533-4e03-b921-cf90b3c02eaa.png)

Neither _Date_ (the original) nor _Version_ is an ideal column heading, where each cell in the column includes a variety of information, but I don't suppose that readers will care.

**Comment by dlangille** [comment]
> > … what we have now on dev.freshports.org …
> 
> Very nice, thanks!
> 
> (Much better than what I originally imagined: a single icon, that would refer to one of the three Git mirrors, depending on the preference of the logged-in user.)

Letting the user choose was work I didn't want to do right now: database table changes, UI changes where the user can  set those choices, etc. This approach is just web changes.

**Comment by dlangille** [comment]
This is what a more complex page looks like: https://dev.freshports.org/databases/mysql55-client/

<img width="905" alt="Screen Shot 2022-09-19 at 8 13 27 AM" src="https://user-images.githubusercontent.com/1626436/191015301-71c8fdb8-6019-40cb-b2a9-510e43395a74.png">

**Comment by grahamperrin** [comment]
Thanks. 

Final thoughts (probably) for this round of changes: 

![image](https://user-images.githubusercontent.com/192271/191049736-2185076e-2da7-4d5d-81e4-09b07f59a012.png)

Move the visible/selectable hash of the most recent commit from near the head of the page, to the relevant cell in the table; lose the _Commit Hash:_ prefix; and it no longer needs to be a link (it'll be a duplicate of the Cgit link that's provided by the Git icon). 

_Maybe_ show one more character of the hash. With <https://dev.freshports.org/ports-mgmt/pkg_tree/> as an example, GitLab <https://gitlab.com/FreeBSD/freebsd-ports/-/commit/fb16dfecae4a6efac9f3a78e0b759fb7a3c53de4> shows: 

`fb16dfec`

– FreshPorts currently shows: 

`fb16dfe`

**Comment by dlangille** [comment]
> Move the visible/selectable hash of the most recent commit from near the head of the page, to the relevant cell in the table; lose the _Commit Hash:_ prefix; and it no longer needs to be a link (it'll be a duplicate of the Cgit link that's provided by the Git icon).

The latest commit and revision has always been at the top of the page:

```
Last Update: 2022-09-07 21:58:51
Commit Hash: fb16dfe
```

What is the reasoning for moving this away? It is because the hash is a link? If so, we can change that link to `#history`

**Comment by dlangille** [comment]
> _Maybe_ show one more character of the hash. With https://dev.freshports.org/ports-mgmt/pkg_tree/ as an example, GitLab https://gitlab.com/FreeBSD/freebsd-ports/-/commit/fb16dfecae4a6efac9f3a78e0b759fb7a3c53de4 shows:
> 
> `fb16dfec`
> 
> – FreshPorts currently shows:
> 
> `fb16dfe`

FreshPorts stores the `hash` and a `short hash`:

```
freshports.devgit=# \d commit_log
                                          Table "public.commit_log"
      Column       |           Type           | Collation | Nullable |                Default                 
-------------------+--------------------------+-----------+----------+----------------------------------------
 id                | integer                  |           | not null | nextval('commit_log_id_seq'::regclass)
 message_id        | text                     |           | not null | 
 message_date      | timestamp with time zone |           | not null | 
 message_subject   | text                     |           |          | 
 date_added        | timestamp with time zone |           | not null | 
 commit_date       | timestamp with time zone |           | not null | 
 committer         | text                     |           | not null | 
 description       | text                     |           | not null | 
 system_id         | integer                  |           | not null | 
 encoding_losses   | boolean                  |           | not null | false
 svn_revision      | text                     |           |          | 
 repo_id           | integer                  |           |          | 
 commit_hash_short | text                     |           |          | 
 committer_name    | text                     |           |          | 
 committer_email   | text                     |           |          | 
 author_name       | text                     |           |          | 
 author_email      | text                     |           |          | 
```

This hash is obtained at processing time via https://github.com/FreshPorts/git_proc_commit/blob/master/git-to-freshports/git-to-freshports-xml.py#L217

You'll see longer and shorter hashes depending on what was extracted at the time.  Look at https://dev.freshports.org/audio/amberol/ for example, where I see `bd833b3`

**Comment by dlangille** [comment]
I seem to recall longer hashes being discussed at sometime, and https://github.com/FreshPorts/git_proc_commit/commit/556f9e1e963a6086c903349d227ddce8b09c09ab#diff-747afef3fbcd6648854a3fdc7d80088c2efb018b20b847547fba951ef5c22ec0L147 seems to show work in that area. Look for line 147 and an `=4`

**Comment by grahamperrin** [comment]
For things such as date(s) and version, it's _very_ useful to see the information at a glance (without needing to scroll or page down). 

> What is the reasoning for moving this away?

I assume that the wish to see a hash is less commonplace. 

If the hash is adjacent to the commit to which it relates (in history, which is gained from clicking on the version at the head of the page), then does there remain a great desire to _also_ see the hash near the head of the page?

**Comment by dlangille** [comment]
> If the hash is adjacent to its commit (in history, which is gained from clicking on the version at the head of the page), then does there remain a great desire to _also_ see the hash near the head of the page?

Is this a suggestion to display a hash on every line of `history`?

**Comment by grahamperrin** [comment]
> Is this a suggestion to display a hash on every line of `history`?

No, just the first, if it's not complicated. 

(Would it be simpler to display a hash on every line? Without the appearance of clutter?)

**Comment by dlangille** [comment]
> > Is this a suggestion to display a hash on every line of `history`?
> 
> No, just the first, if it's not complicated.

It should straight forward.

Why is a hash on the first commit useful?

> (Would it be simpler to display a hash on every line? Without the appearance of clutter?)

To do only the first line is 'harder' in that you need to detect it's the first commit.  It is creating a flag and an `if` to check that flag.

**Comment by grahamperrin** [comment]
> Why is a hash on the first commit useful?

I thought of that only because the current design shows just one hash (for the most recent commit).

**Comment by dlangille** [comment]
> > Why is a hash on the first commit useful?
> 
> I thought of that only because the current design shows just one hash (for the most recent commit).

I understand.

**Comment by grahamperrin** [comment]
Noted with thanks: 

* [New links to GitLab and GitHub, in addition to the exist cgit.freebsd.org – FreshPorts News](https://news.freshports.org/2022/09/20/new-links-to-gitlab-and-github-in-addition-to-the-exist-cgit-freebsd-org/)

Re: this line, 

> … the commit hash at the top of the page is now a link to the commit history further down the page.

The version, not the hash, links to the history. 

----

A former benefit of having a visible hash that is **not** a link: 

* double-click to select

– swift, when aiming to copy the hash then seek it in another context.

**Comment by dlangille** [comment]
Well, would you look  at that.  They both link to `#history`:

* The version link to `#history` was [added two days ago](https://github.com/FreshPorts/freshports/blame/master/classes/port-display.php#L767).

* Whereas, the link from short commit hash to `#history` was [created 4 months ago](https://github.com/FreshPorts/freshports/blame/master/classes/port-display.php#L990).

**Comment by dlangille** [comment]
> A former benefit of having a visible hash that is **not** a link:
> 
> * double-click to select
> 
> – swift, when aiming to copy the hash then seek it in another context.

Well, it seems that ability has never been there. When the [commit hash was first added in](https://github.com/FreshPorts/freshports/blame/8d6c08265710297fb48c1f943da5d1089eb35eab/classes/port-display.php#L674), it was a link.

Before that, it was svn revision, and that too [was a link at least 6 years ago](https://github.com/FreshPorts/freshports/blame/e4f9325315a4000daf2381eed491fefab3cf294f/classes/port-display.php#L209).

Are you sure it's this part of the website where you were double-clicking that hash?

To be fair, I've long considered adding a click-to-copy link for hashes.  Much lke GitHub has, see [this page](https://github.com/FreshPorts/freshports/commits/master) for an example: the icon to the left of the hashes.

**Comment by grahamperrin** [comment]
> Are you sure it's this part of the website where you were double-clicking that hash?

Sorry! My memory of things was mistaken: <https://web.archive.org/web/20220601173504/https://www.freshports.org/sysutils/fusefs-ntfs> there's the hash, clickable (not double-clickable to select). 

I routinely do this type of thing, without giving it a second thought: 

1. go to `#history`
2. click the cgit link
3. _in the address bar_, double-click to select the hash. 

(Truly. That combination of steps feels quicker and more useful than slowing down to carefully drag across a link without accidentally following the link.)

**Comment by grahamperrin** [comment]
<https://github.com/FreshPorts/freshports/issues/363#issuecomment-1250260012>

> Commits, port history, and …

Nit. In search results, e.g. <https://www.freshports.org/search.php?stype=maintainer&method=exact&query=ports@FreeBSD.org>, a click on the version number: 

* does add `#history` to the tail of the URL
* does not do so in the context of _the page for_ the port.

![image](https://user-images.githubusercontent.com/192271/192071471-bda3906a-af8e-4173-b777-b20dff3f4e13.png)

**Comment by dlangille** [comment]
AFAIK, the hash/revision number was always a link.

If someone can figure out a copy icon with the code to go with it, I can add that in. Hashes on all the commits.

**Comment by grahamperrin** [comment]
Nit, under e.g. <https://www.freshports.org/sysutils/bsdadminscripts/#description>: 

![image](https://user-images.githubusercontent.com/192271/192072726-3dab85f5-5bd1-4373-847c-f0e1de53b7fd.png)

– should be: 

![image](https://user-images.githubusercontent.com/192271/192072805-999ab00d-a48f-4a31-be9c-bc9fbeb9a103.png)

**Comment by grahamperrin** [comment]
> a copy icon

_CLIPBOARD_ `&#128203;` for simplicity, maybe? 

![image](https://user-images.githubusercontent.com/192271/192073467-7d806534-77b8-485c-a093-158e7cf22750.png)

… I'll try to review this in dark mode.

**Comment by grahamperrin** [comment]
> a copy icon

Browsing SVG-oriented <https://iconarchive.com/svg-icons.html> led me to these two: 

* [Clipboard Icon | Office Iconset | Thalita Torres](https://iconarchive.com/show/office-icons-by-thalita-torres/clipboard-icon.html)
* [Clipboard Icon | Office Iconset | Vexels](https://iconarchive.com/show/office-icons-by-vexels/clipboard-icon.html)

Respectively (PNG): 

* ![image](https://user-images.githubusercontent.com/192271/192074124-5a5353c7-0903-48cb-ac9a-24505adb9665.png)
* ![image](https://user-images.githubusercontent.com/192271/192074133-10ab81ba-6b2c-48d3-bd8d-fad7fc9f6f3f.png)

The first one is too fussy, doesn't work well at that size. 

----

Also, from the two pages above: 

![image](https://user-images.githubusercontent.com/192271/192074224-c54a09ce-78a5-4a41-8178-efc0fd061f09.png)

![image](https://user-images.githubusercontent.com/192271/192074248-e93ef459-f323-4b0c-a9d8-dc7d93e56a27.png)

Alternatively, although some of these don't have SVG: 

* <https://iconarchive.com/search?q=clipboard>

----

@dlangille if you particularly like any one or two, let me know which one(s), then I can aim to test in dark mode and maybe attempt a PR. Thanks

**Comment by dlangille** [comment]
> * does add `#history` to the tail of the URL
> * does not do so in the context of _the page for_ the port.

I see `#history` has no context on the search page; the link needs to be `/arabic/ae_fonts_mono/#history` on the search page, not just `#history`.  The same code produces both sets of output.

**Comment by dlangille** [comment]
> Nit, under e.g. https://www.freshports.org/sysutils/bsdadminscripts/#description:
> 
> ![image](https://user-images.githubusercontent.com/192271/192072726-3dab85f5-5bd1-4373-847c-f0e1de53b7fd.png)
> 
> – should be:
> 
> ![image](https://user-images.githubusercontent.com/192271/192072805-999ab00d-a48f-4a31-be9c-bc9fbeb9a103.png)
> 
> Sorry for not spotting things such as these earlier, in dev.

Good catch, fixed at https://dev.freshports.org/sysutils/bsdadminscripts/#description

**Comment by dlangille** [comment]
> > * does add `#history` to the tail of the URL
> > * does not do so in the context of _the page for_ the port.
> 
> I see `#history` has no context on the search page; the link needs to be `/arabic/ae_fonts_mono/#history` on the search page, not just `#history`. The same code produces both sets of output.

This turned out rather simple to implement.

The first part of this code is within the function `SetDetailsSearch()` which is invoked by `www/search.php` -  it says: display only the fields pertinent to search results.  I added a new variable to that list.

```
@@ -569,6 +571,12 @@ class port_display {
                $this->ShowPortCreationDate    = true;
                $this->ShowShortDescription    = true;
                $this->ShowWatchListStatus     = true;
+
+               # when showing links such as #history, include the full path to the port
+               # because we are linking to another page. Otherwise, just use #history
+               # because the link is on this page.
+               #
+               $this->_UseFullPathNames       = true;
        }
 
        function SetDetailsPkgMessage() {
@@ -764,7 +772,11 @@ class port_display {
                        $HTML .= "<dt><b>";
                        $PackageVersion = freshports_PackageVersion($port->{'version'}, $port->{'revision'}, $port->{'epoch'});
                        if (strlen($PackageVersion) > 0) {
-                               $HTML .= ' <a href="#history">' . $PackageVersion . '</a>';
+                               $HTML .= ' <a href="';
+                               if ($this->_UseFullPathNames) {
+                                       $HTML .= '/' . htmlentities($this->port->category) . '/' .  htmlentities($this->port->port) . '/';
+                               }
+                               $HTML .= '#history">' . $PackageVersion . '</a>';
                        }
```

https://dev.freshports.org/search.php?stype=maintainer&method=exact&query=ports@FreeBSD.org works as expected now.

**Comment by grahamperrin** [comment]
FWIW, I prefer the home icon pictured at <https://github.com/FreshPorts/freshports/issues/363#issuecomment-1250382707> to the home icons that currently appear under <https://dev.freshports.org/sysutils/bsdadminscripts/#description>: 

![image](https://user-images.githubusercontent.com/192271/192112699-63af02e4-686f-4f60-9b7d-95c645825292.png)

If your concern is that the black is too harsh/stark: I think, it's a good thing. 

The boldness (contrast) is more likely to catch the eye when a person looks for, but does not find, the `WWW` line. True: you currently have the _NOTE_ at the head of pages, but people _love_ to not notice notes :-)

**Comment by dlangille** [comment]
> If your concern is that the black is too harsh/stark: I think, it's a good thing.
> 
> The boldness (contrast) is more likely to catch the eye when a person looks for, but does not find, the `WWW` line. True: you currently have the _NOTE_ at the head of pages, but people _love_ to not notice notes :-)

I can't see the second home-page icon when in dark mode.

I can see the first one in both dark and light mode, however I think it's slight too busy.

**Comment by grahamperrin** [comment]
Re: <https://github.com/FreshPorts/freshports/commit/f231b3fba6df0a43488da070d90db264af3b0529#diff-ba364a4d6576849151fb33c2dd2f8ed1713b9ff96cfc0bafa311ef1a04a345e9> I like the previously used icon, I guess that it didn't suit dark mode. 

The new icon feels fiddly (too small) when aiming to click. YMMV (eyesight, pointing devices, etc.). With <https://dev.freshports.org/devel/llvm-devel/> as an example, how about what's below? Essentially, to enlarge the home icon: 

![image](https://user-images.githubusercontent.com/192271/192215660-7c52aa17-4f10-4743-9c36-a5cb7754361e.png)

The difference in size (compared to the icons for cgit, GitHub and GitLab) annoys me only if I stare at it, with knowledge of how the line previously appeared. Plus, a slight change to your differences for the Subversion icon, which plays tricks on the eye with its white area. 

In context, hopefully not offensively large: 

![image](https://user-images.githubusercontent.com/192271/192216854-f47f3759-13a5-4b57-89d1-8fbae8b2f820.png)

(I think I overdid the resize of the Subversion icon, but I can't tweak it now. Time to drive to work.)

Thanks again

**Comment by dlangille** [comment]
> Re: [f231b3f#diff-ba364a4d6576849151fb33c2dd2f8ed1713b9ff96cfc0bafa311ef1a04a345e9](https://github.com/FreshPorts/freshports/commit/f231b3fba6df0a43488da070d90db264af3b0529#diff-ba364a4d6576849151fb33c2dd2f8ed1713b9ff96cfc0bafa311ef1a04a345e9) I like the previously used icon, I guess that it didn't suit dark mode.

Indeed, it did not suit at all.

> (I think I overdid the resize of the Subversion icon, but I can't tweak it now. Time to drive to work.)
> 
> Thanks again

Let's try a different subversion icon

![Screen Shot 2022-09-26 at 8 44 22 AM](https://user-images.githubusercontent.com/1626436/192280136-3ac4c2df-c408-4b10-9c83-f3840013931f.png)

**Comment by grahamperrin** [comment]
Found (Yandex Images: image search): `https://icons.veryicon.com/png/System/Fugue/subversion.png` at <https://www.veryicon.com/icons/system/fugue/subversion-1.html>

![image](https://user-images.githubusercontent.com/192271/192344896-84945141-ca8c-49a8-8cfe-c9b8b7a32856.png)

**Comment by dlangille** [comment]
That's a 16x16 icon scaled to 28x28. It looks fuzzy.

**Comment by dlangille** [comment]
Yes, terrible.

![Screen Shot 2022-09-26 at 3 17 33 PM](https://user-images.githubusercontent.com/1626436/192361488-23be9107-5741-45f7-8034-717640ec9dcb.png)

**Comment by grahamperrin** [comment]
<https://docs.freebsd.org/en/books/handbook/mirrors/#external-mirrors> I forgot, Codeberg. 

<https://design.codeberg.org/> 

> … [design.codeberg.org](https://design.codeberg.org/) acts as a CDN for design resources, …

So: 

`<img class="icon" src="https://design.codeberg.org/logo-kit/icon.svg" alt="Codeberg" title="Codeberg" width="22" height="22">`

![image](https://user-images.githubusercontent.com/192271/193444571-c3aab4fc-a20f-4388-98a2-9a5d5b240c2b.png)

Other suggestions (screenshot above, screenshot below, messing with <https://dev.freshports.org/devel/llvm-devel/>): 

* `vertical-align: bottom;` or `vertical-align: text-bottom;` for `.icon` (improves the first appearances of icons at the page for a port)
* `margin: 2px;` for `.icon`
* back to an earlier suggestion of having whitespace to separate the home icon from the Git mirror icons (conceptually: a home page is rarely port-related, everything to the right of the space is ports-related)
* experimenting with _BROKEN BAR_ `&#166;` as a separator between each the three Git mirrors and SVNWeb (I also experimented with _VERTICAL LINE_ `&#124;`, didn't like it as much)
* proper case for GitHub and GitLab (not dropped to github and gitlab)
* now with a circular icon in the mix, and none of the six icons larger than 22 x 22, the tilt of the currently used SVNWeb icon appears less peculiar
* 16 x 16 for the fallout icons within tables of packages (larger than text, however any smaller might create difficulty when aiming to click)

![image](https://user-images.githubusercontent.com/192271/193444715-63d304b6-c251-435b-a102-2705cde1a9d8.png)

**Comment by grahamperrin** [comment]
Somewhat off-topic, I'm puzzled by the `17` measurement in the _Box Model_: 

![image](https://user-images.githubusercontent.com/192271/193445686-638e3d6d-c70e-4ce7-bb91-452d03f564ed.png)

What's the origin of this `17`, and should I be concerned by the related grid-line cutting across the heads of the icons?

**Comment by dlangille** [comment]
> * 16 x 16 for the first appearance of the fallout icon

...

> * 16 x 16 for fallout icons within tables of packages (that is larger than text, however any smaller than 16 x 16 might create difficulty when aiming to click)


All instances of the `fallout` icon should now be 16x16? The first statement leads me to think no.

**Comment by dlangille** [comment]
> Somewhat off-topic, I'm puzzled by the `17` measurement in the _Box Model_:
> 
> ![image](https://user-images.githubusercontent.com/192271/193445686-638e3d6d-c70e-4ce7-bb91-452d03f564ed.png)
> 
> What's the origin of this `17`, and should I be concerned by the related grid-line cutting across the heads of the icons?

I don't see that here. Perhaps I changed something already. Please verify.

**Comment by dlangille** [comment]
At some point, we need to finish this issue.

**Comment by grahamperrin** [comment]
> At some point, we need to finish this issue.

Absolutely. 

Sorry, I was looking at _dev_, assuming that it was somehow ahead of _www_. (I didn't see the changes at www until after this morning's comments from me.)

**Comment by grahamperrin** [comment]
<https://github.com/FreshPorts/freshports/issues/363#issuecomment-1264646174> 

> I don't see that here. …

Apologies for the lack of clarity. 

I took the shot of the _Box Model_ whilst using the dev-based mockup that was used in [the previous comment](https://github.com/FreshPorts/freshports/issues/363#issuecomment-1264584097), which I'll now hide (today's various commits noted with thanks). 

----

Towards answering my own question, I bookmarked <https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model> and <https://www.w3schools.com/css/css_boxmodel.asp> (mostly new to me!) … I'll try to figure out how the 17 is calculated.

**Comment by grahamperrin** [comment]
I think: 

1. ready to close when what's currently in dev hits production
2. if there's anything to correct post-closure, I'll aim to draft a PR
3. above, [Hashes on all commits](https://github.com/FreshPorts/freshports/issues/363#issuecomment-1256810662) can be spun into a separate issue, if you like, @dlangille

**Comment by dlangille** [comment]
These changes are now on test.

**Comment by grahamperrin** [comment]
Thanks. 

<https://test.freshports.org/databases/mysql55-client/#history>, the table of packages. 

I checked the left column intersection with the first two (earliest) rows for `5.5.62_3` – the 2019 commit, then the first of the 2021 commits. 

![image](https://user-images.githubusercontent.com/192271/195481069-b0e2325a-ae02-4b04-bb3f-91525920a6c5.png)

Links from icons for cgit, Codeberg, GitHub and GitLab seem to be OK – all four are for: 

    Remove # $FreeBSD$ from Makefiles.

– incidentally, a broad-ranging commit that [reportedly involved](https://test.freshports.org/commit.php?category=databases&port=mysql55-client&files=yes&message_id=305f148f482daf30dcf728039d03d019f88344eb): 

* 29**222** _ports [& non-ports]_
* 29**333** _files_.

----

Then, the uppermost commit in the table. All four icons lead to: 

    cleanup: Remove expired ports:

– using long hash `6fcb7301e2a5cc0c3586a5f826e5a82613de7822`.

Finally, compare those four with the four near the head of the page, which use short hash `6fcb730`, I discovered issue #399, which is not limited to test service.

----

399 aside: that looks good to me.

**Comment by grahamperrin** [comment]
Next up, check: 

* https://test.freshports.org/www/firefox/
* branch-specific https://test.freshports.org/www/firefox/?branch=2022Q4

**Comment by grahamperrin** [comment]
Time flew. 

In production (thanks), the row of six icons looks good, to me: 

* https://www.freshports.org/www/firefox/
* https://www.freshports.org/www/firefox/?branch=2022Q4. 

Codeberg icons are not yet apparent at the home page. I'm in no rush for this … (I imagine myself looking at a `.php` file somewhere and making a horrible mess of it.

**Comment by dlangille** [comment]
Now in prod.
