### ISSUE TITLE
watch.php htmlentities message

### ISSUE THREAD

**Issue by CyberCr33p** [FreshPorts/freshports#371]
Hello Dan,

https://www.freshports.org/watch.php shows:

`Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/www/freshports/include/freshports.php on line 121
`

**Comment by dlangille** [comment]
I think this was fixed earlier today. Can you confirm please?

**Comment by CyberCr33p** [comment]
Yes it's ok now.

**Comment by dlangille** [comment]
Thank you for reporting it. Please always report stuff like that. In this case, I just happened to find it too. :)
