### ISSUE TITLE
Some non-new ports are misrepresented as new, some new ports lack the NEW! hint

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#372]
According to <https://www.freshports.org/faq.php#new>: 

> New: This port has been recently added. A port is marked as new for 10 days.

<https://www.freshports.org/graphics/drm-fbsd13-kmod/> ([captured](https://web.archive.org/web/20220721210012/https://www.freshports.org/graphics/drm-fbsd13-kmod/)) has the NEW! symbol, however <https://www.freshports.org/graphics/drm-fbsd13-kmod/#history> it was added 2021-01-22.

----

Random checks of other pages: 

* <https://www.freshports.org/graphics/drm-510-kmod/> is free from this issue
* <https://www.freshports.org/ports-new.php?interval=week> at least one of the ports lacks the NEW! hint
* <https://web.archive.org/web/20220601122148/https://www.freshports.org/ports-new.php?interval=week> none had the hint …

**Comment by dlangille** [comment]
The code was doing: `if ('22 Jan 2021 17:34:22' > 1657629188)`

The fix: convert  the first value to a timestamp via `strtotime`

After pushing the fix to prod, the cache was cleared so new HTML could be rendered:

```
root@aws-1-nginx01:/ # zfs rollback data01/freshports/nginx01/var/db/freshports/cache/ports@empty
root@aws-1-nginx01:/ # 
```
