### ISSUE TITLE
WWW moved to Makefile, no longer represented at ports' pages

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#383]
<https://www.freshports.org/audio/virtual_oss/#description> for example, there's no longer the WWW line. 

<https://cgit.freebsd.org/ports/diff/audio/virtual_oss/Makefile?id=b7f05445c00f2625aa19b4154ebcbce5ed2daa52>

Context: <https://reviews.freebsd.org/D36369>

> ⚙ D36369 Document move of project website from port's pkg-descr to Makefile

**Comment by dlangille** [comment]
A bunch of work has been done for this. Can you identify a problem?

**Comment by grahamperrin** [comment]
Sorry! I'm so accustomed to seeing the WWW line, I forgot about the _Homepage_ link. 

Not a bug.
