### ISSUE TITLE
watch-list-maintenance.php: Parse error: Unclosed '(' does not match ']'

### ISSUE THREAD

**Issue by agrajag9** [FreshPorts/freshports#386]
Visiting https://www.freshports.org/watch-list-maintenance.php yields only the following:

    Parse error: Unclosed '(' does not match ']' in /usr/local/www/freshports/www/watch-list-maintenance.php on line 89

Oddly enough it's a 200. Response headers below:
```
HTTP/2 200 OK
server: nginx/1.22.0
date: Tue, 20 Sep 2022 01:36:36 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
x-powered-by: PHP/8.1.10
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
content-encoding: gzip
X-Firefox-Spdy: h2
```

**Comment by dlangille** [comment]
Ouch. I'll fix this on Tuesday. Thanks.

**Comment by dlangille** [comment]
Reopening until this hits production.

**Comment by dlangille** [comment]
@agrajag9 should be fixed on prod now. Thank you.

**Comment by agrajag9** [comment]
Thanks for the quick fix! Confirmed working as expected again :+1:
