### ISSUE TITLE
The #dependencies anchor is missing from pages for ports that require nothing, but are required by something

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#388]
<https://www.freshports.org/faq.php#anchors> includes _dependencies_, and the anchor does appear at most pages where it's expected, but not yet in contexts such as: 

* <https://www.freshports.org/archivers/arc/#dependencies> | <https://dev.freshports.org/archivers/arc/#dependencies>

It's an example of a port that requires nothing, but is required by some things: 

![image](https://user-images.githubusercontent.com/192271/192130917-61ec6efc-4120-4a75-8456-6db95d7f393e.png)

**Comment by dlangille** [comment]
Have a look at:

1. https://dev.freshports.org/misc/xtail/#required
2. https://dev.freshports.org/misc/xtail/#dependencies
3. https://dev.freshports.org/archivers/arc/#dependencies
4. https://dev.freshports.org/archivers/arc/#required

**Comment by grahamperrin** [comment]
Thanks. I'm not sure about this type of thing, I have to look _twice_: 

![image](https://user-images.githubusercontent.com/192271/192163352-c5410628-1975-46d8-9605-c1718d5407b9.png)

– because (a) I think of the five items, maybe wrongly, as reverse dependencies; and (b) the absence of a heading for _This port is required by:_ makes it appear as if its heading is _This port has no dependencies_.

**Comment by dlangille** [comment]
What you're saying is "This port is required by" needs to be the same size as "This port has no dependencies".

**Comment by dlangille** [comment]
See https://dev.freshports.org/archivers/arc/#dependencies :


![Screen Shot 2022-09-25 at 4 55 20 PM](https://user-images.githubusercontent.com/1626436/192165340-b3678ab7-2135-49af-9d29-6aa5235bc1c6.png)

**Comment by grahamperrin** [comment]
Punctuated: 

> This port has no dependencies.

**Comment by dlangille** [comment]
> Punctuated:
> 
> > This port has no dependencies.

Done.

**Comment by grahamperrin** [comment]
<https://dev.freshports.org/security/clamav/#dependencies> with anchors revealed: 

![image](https://user-images.githubusercontent.com/192271/192167652-6017b1fc-ad71-4d1e-a463-e42c5b78862a.png)

I reckon, the anchor for _This port is required by:_ should be `#requiredby`

**Comment by dlangille** [comment]
> I reckon, the anchor for _This port is required by:_ should be `#requiredby`

Done.

**Comment by grahamperrin** [comment]
<https://dev.freshports.org/devel/llvm-devel/#dependencies> as it appeared a few minutes ago: 

----
![image](https://user-images.githubusercontent.com/192271/192168764-2a824627-88be-438d-8bcf-112d2876e72b.png)
----

_Maybe_: 

1. less use of bold
2. reduce the level of indentation for items beneath `#requiredby`. 

Mocked-up some of (1) but not (2): 

----
![image](https://user-images.githubusercontent.com/192271/192169189-c10be937-5595-4a3c-a4ff-a1a2e5741771.png)

**Comment by dlangille** [comment]
It is easier for me if you list the changes. I'm likely to miss suggestions in this form. Showing me the CSS changes is good.

I think the changes are all under "This port is required by".

If there are changes to text, I've missed them. 

This is the change I made:

```
 dd.required
 {
   margin-top: 5px;
-  font-weight: bold;
+/*  font-weight: bold; */
   margin-inline-start: 30px;
 }

```

**Comment by grahamperrin** [comment]
Yes, I'm somewhat out of my comfort zone with CSS and so on. 

Re: the second shot under <https://github.com/FreshPorts/freshports/issues/388#issuecomment-1257297163> I couldn't figure out how to achieve what I have in mind. 

(This is not a plea for help with CSS; I'll put more effort into learning/guessing at the weekend, maybe …)

**Comment by dlangille** [comment]
This is now in prod. Please reopen if there are issues.
