### ISSUE TITLE
"see SVNWeb link above for full details"

### ISSUE THREAD

**Issue by yasuhirokimura** [FreshPorts/freshports#389]
At the top of commit history of port, there is following message.

> Commit History - (may be incomplete: see SVNWeb link above for full details)

But ports reporsitory had already migrated from SVN to Git. So `cgit` should be used instead of `SVNWeb`.

**Comment by dlangille** [comment]
I'm not sure how best to word that:

`may be incomplete: see various links to repositories for full details` is what I have now on `dev`.

**Comment by dlangille** [comment]
Let's  go with this for now:

`may be incomplete: for full details, see links to repositories near top of page`
