### ISSUE TITLE
BOOST_NO_CXX11_HDR_MUTEX always defined

### ISSUE THREAD

**Issue by 2underscores-vic** [FreshPorts/freshports#39]
Boost 1.63 `boost/config/stdlib/libcpp.hpp` has code

```
#if __cplusplus < 201103
...
#  define BOOST_NO_CXX11_HDR_MUTEX
...
```

So the macro is always defined despite of libc++ has `std::mutex`!
Boost.Context - C++11 library never uses `std::mutex` as a consequence.

**Comment by dlangille** [comment]
I have no idea what you referring to.  That does not look like FreshPorts code to me.  Can you elaborate please?

**Comment by 2underscores-vic** [comment]
Likely it is not FreshPorts issue but I failed to build Boost correctly on FreeBSD using ports

**Comment by dlangille** [comment]
FreshPorts only reports, it does not maintain. Sorry, we cannot help you here.

**Comment by 2underscores-vic** [comment]
How maintains the ports?

**Comment by dlangille** [comment]
Each page has 'Maintainer' listed at the top.

**Comment by dlangille** [comment]
But you might want to seek help elsewhere first, rather than asking the maintainer.

**Comment by 2underscores-vic** [comment]
Thank you.
Apologize for disturbing

**Comment by dlangille** [comment]
e.g. forums.freebsd.org, #FreeBSD on FreeBSD, FreeBSD Questions mailing list.
