### ISSUE TITLE
PHP warnings in "Report Subscriptions" page

### ISSUE THREAD

**Issue by gall0ws** [FreshPorts/freshports#390]
Report Subscription page is cluttered by many PHP warning messages like:

```
Warning: Undefined array key "frequency" in /usr/local/www/freshports/www/report-subscriptions.php on line 175

Warning: Undefined array key "selected" in /usr/local/www/freshports/www/report-subscriptions.php on line 180

Warning: Undefined array key "frequency" in /usr/local/www/freshports/www/report-subscriptions.php on line 204
```

I'm not a PHP guy, but looks a very easy to fix using php's idiomatic way of handle possible undefined values (could it be just turning the warning off? 😄).

**Comment by dlangille** [comment]
I think I'll fix the problem. Warnings can become problems later.

**Comment by dlangille** [comment]
To reproduce:

* login
* click on `Report Subscriptions` (under `Watch Lists`)
* click on `update`

**Comment by gall0ws** [comment]
@dlangille Fixed on `dev` 👍

**Comment by dlangille** [comment]
Fixed in prod. Please reopen if you see this problem.
