### ISSUE TITLE
Website is sporatically slow.

### ISSUE THREAD

**Issue by cweimann** [FreshPorts/freshports#391]
At first I thought it might relate to if I was logged in or not but some testing shows that isn't it.  It is almost as though it is load balancing and one of the backend servers is overloaded.

**Comment by dlangille** [comment]
Let me know if it's still present now.

**Comment by cweimann** [comment]
Right now I think it might be down.

**Comment by dlangille** [comment]
Yes. I took it offline. If the website is that bad right now, might as well do some db upgrades.

**Comment by dlangille** [comment]
should be better now.

**Comment by cweimann** [comment]
Yes, much better today.  Thank you!
