### ISSUE TITLE
Links to github, gitlab, and codeberg repos will be wrong for non-port commits

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#392]
<https://docs.freebsd.org/en/books/handbook/mirrors/#external-mirrors> I forgot, Codeberg. 

<https://design.codeberg.org/> 

> … [design.codeberg.org](https://design.codeberg.org/) acts as a CDN for design resources, …

So: 

`<img class="icon" src="https://design.codeberg.org/logo-kit/icon.svg" alt="Codeberg" title="Codeberg" width="22" height="22">`

![image](https://user-images.githubusercontent.com/192271/193444571-c3aab4fc-a20f-4388-98a2-9a5d5b240c2b.png)

Other suggestions (screenshot above, screenshot below, messing with <https://dev.freshports.org/devel/llvm-devel/>): 

* `vertical-align: bottom;` or `vertical-align: text-bottom;` for `.icon` (improves the first appearances of icons at the page for a port)
* 16 x 16 for the first appearance of the fallout icon
* `margin: 2px;` for `.icon` (easier when aiming to click)
* back to an earlier suggestion of having whitespace to separate the home icon from the Git mirror icons (conceptually: a home page is rarely port-related, everything to the right of the space is port-related)
* experimenting with _BROKEN BAR_ `&#166;` to separate each of the three Git mirrors and SVNWeb (I also experimented with _VERTICAL LINE_ `&#124;`, didn't like it as much)
* proper case for GitHub and GitLab (not dropped to github and gitlab)
* now with a circular icon in the mix – and none of the six icons larger than 22 x 22 – the tilt of the currently used SVNWeb icon appears less peculiar
* 16 x 16 for fallout icons within tables of packages (that is larger than text, however any smaller than 16 x 16 might create difficulty when aiming to click)

![image](https://user-images.githubusercontent.com/192271/193444715-63d304b6-c251-435b-a102-2705cde1a9d8.png)

_Originally posted by @grahamperrin in https://github.com/FreshPorts/freshports/issues/363#issuecomment-1264584097_

**Comment by grahamperrin** [comment]
Sorry, my mind is a blank here, what would be an example of a _non-port_ commit?

**Comment by dlangille** [comment]
These changes are now on test.

**Comment by dlangille** [comment]
> Sorry, my mind is a blank here, what would be an example of a _non-port_ commit?

Something to `UPDATING` or `MOVED`, something to `src`, `docs`, or `www`.

**Comment by dlangille** [comment]
`MOVED` links are correct.  See https://dev.freshports.org/MOVED

**Comment by dlangille** [comment]
Not correct for https://dev.freshports.org/commit.php?message_id=419be99ba86de09cf89b56edd02d491f6c793c25

* https://cgit.freebsd.org/doc/commit/?id=419be99ba86de09cf89b56edd02d491f6c793c25 (right)
* https://gitlab.com/FreeBSD/freebsd-ports/-/commit/419be99ba86de09cf89b56edd02d491f6c793c25 (wrong)
* https://github.com/FreeBSD/freebsd-ports/commit/419be99ba86de09cf89b56edd02d491f6c793c25 (wrong)

Both wrong URLs show `ports` when they should not.

The corrected `wrong` URLS are:

* https://gitlab.com/FreeBSD/freebsd-doc/-/commit/419be99ba86de09cf89b56edd02d491f6c793c25
* https://github.com/FreeBSD/freebsd-doc/commit/419be99ba86de09cf89b56edd02d491f6c793c25
