### ISSUE TITLE
cgit commit links refer to the wrong commits if the hashes are not preceded by ?id=

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#399]
### Steps

1. <https://www.freshports.org/databases/mysql55-client/>
2. click the GitHub or GitLab icon
3. observe the first line of the commit message, _cleanup: Remove expired ports:_
4. click the cgit icon

### Expected

5. <https://cgit.freebsd.org/ports/commit/?id=6fcb730>

### Actual result

5. <https://cgit.freebsd.org/ports/commit/6fcb730>, _editors/vim: Update to 9.0.0735_

### Postscript

databases/mysql55-client is, notably, a **deleted** port. 

Pages for (non-deleted) [databases/mysql56-client](https://www.freshports.org/databases/mysql56-client/) and [databases/mysql57-client](https://www.freshports.org/databases/mysql57-client/) are not affected by this issue.

**Comment by grahamperrin** [comment]
Aside, 

> [cgit.freebsd.org/ports/commit/6fcb730](https://cgit.freebsd.org/ports/commit/6fcb730), _editors/vim: Update to 9.0.0735_

Either I made a mistake with copy-and-paste, or there's now different content at the same address (lacking `?id=`) for `6fcb730`: 

![image](https://user-images.githubusercontent.com/192271/195478966-4fa96c73-2824-4d21-9f59-13ff8d77a05a.png)

**Comment by dlangille** [comment]
https://www.freshports.org/databases/mysql55-client/ is a deleted port, and an edge case. I will describe what these links should be for an active port.

I'm  assuming we are discussing the links between `Description` and `pkg-plist` - They are meant to be links to the port withimn the repo.  For example, from https://www.freshports.org/devel/cmake/ they should be:

* https://cgit.freebsd.org/ports/tree/devel/cmake
* https://github.com/freebsd/freebsd-ports/tree/main/devel/cmake
* https://gitlab.com/FreeBSD/freebsd-ports/-/tree/main/devel/cmake
* https://svnweb.freebsd.org/ports/head/devel/cmake/

With a deleted port, that won't work. For example:

* https://cgit.freebsd.org/ports/tree/databases/mysql55-client
* https://github.com/freebsd/freebsd-ports/tree/main/databases/mysql55-client
* https://gitlab.com/FreeBSD/freebsd-ports/-/tree/main/databases/mysql55-client

What the code attempts to do instead: link to  the last commit for that port.

* https://cgit.freebsd.org/ports/commit/6fcb730
* https://github.com/freebsd/freebsd-ports/commit/6fcb730
* https://gitlab.com/FreeBSD/freebsd-ports/-/commit/6fcb730

**Comment by dlangille** [comment]
This is fixed at https://dev.freshports.org/databases/mysql55-client/

Please review.

**Comment by grahamperrin** [comment]
> This is fixed at [dev.freshports.org/databases/mysql55-client](https://dev.freshports.org/databases/mysql55-client/)
> 
> Please review.

Thanks, edge case fixed! 

<https://cgit.freebsd.org/ports/commit/?id=6fcb730>, as expected. 

----

Also reviewed, confirmed fixed: two cgit icons picked randomly from <https://dev.freshports.org/ports-deleted.php>.
