### ISSUE TITLE
Feature request: Additional rss feed(s)

### ISSUE THREAD

**Issue by debdrup** [FreshPorts/freshports#40]
After a discussion on irc and a tweet at Dan, along with some additional ideas I had on my own, I think there's room for improvement with respect to specific rss feeds, so here's a few things that I've thought of, in no particular order, which new feeds could do:
- Include only newly added ports, not updated ones
- Include only broken ports
- Include only vulnerable ports

The first suggestion is mostly because sometimes a neat little thing gets added which someone might not have thought of using, and number two and three will help people who don't regularly build ports with poudriere, or who don't keep packages up-to-date.

I realize that all of that information could be scraped, but then only I would have that information, and I suspect others can use it.

**Comment by dlangille** [comment]
see also #41

**Comment by dlangille** [comment]
FYI, I found https://www.freshports.org/backend/newsfeeds.php which already has an RSS feed for ne ports.  However, it is not being refreshed.  See #58

**Comment by dlangille** [comment]
On my laptop, I have a working RSS feed for new ports, which works on both head and any branch.

**Comment by dlangille** [comment]
An issue with a broken ports feed: If you list all broken ports, how do you sort the list?  Ideally, it would be against latest commit. I can think of no other way.

**Comment by dlangille** [comment]
Please have a look at https://dev.freshports.org/backend/newsfeeds.php and see if this does what you need.

If this stuff is OK, I will then add vulnerable ports
