### ISSUE TITLE
ports_by_pkg_message.php:48 undefined variable $Debug | ports_by_pkg_message.php:83 undefined variable $User and attempt to read property "id" on null

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#401]
When #343 seeking within package messages: 

<https://www.freshports.org/search.php?stype=pkg-message&method=match&query=example> and
<https://dev.freshports.org/search.php?stype=pkg-message&method=match&query=example>

> Warning: Undefined variable $Debug in /usr/local/www/freshports/classes/ports_by_pkg_message.php on line 48
> 
> Warning: Undefined variable $User in /usr/local/www/freshports/classes/ports_by_pkg_message.php on line 83
> 
> Warning: Attempt to read property "id" on null in /usr/local/www/freshports/classes/ports_by_pkg_message.php on line 83

----

<https://test.freshports.org/search.php?stype=pkg-message&method=match&query=example>

> SQL ERROR

**Comment by dlangille** [comment]
Fixed on `dev`.

**Comment by dlangille** [comment]
The problem on test is SQL related:

```
*** /var/log/freshports/freshports.log ***
Oct 18 00:45:53 test-nginx01 syslogd: last message repeated 2 times
Oct 18 00:45:56 test-nginx01 FreshPorts[89393]: /usr/local/www/freshports/classes/ports_by_pkg_message.php::63: ERROR:  column "pkgmessage_textsearchable2" does not exist
Oct 18 00:45:56 test-nginx01 FreshPorts[89393]: LINE 8:         pkgmessage_textsearchable2 @@ websearch_to_tsquery($...
Oct 18 00:45:56 test-nginx01 FreshPorts[89393]:                 ^
Oct 18 00:45:56 test-nginx01 FreshPorts[89393]: HINT:  Perhaps you meant to reference the column "ports.pkgmessage_textsearchable".
```

**Comment by dlangille** [comment]
`stage` has the same problem as `test`

**Comment by dlangille** [comment]
I'll come back to this when I can use `pg_admin` to compare the two databases. I think it's only a missing column.

**Comment by grahamperrin** [comment]
> Fixed on `dev`.

Confirmed, thanks!

**Comment by dlangille** [comment]
`test` & `stage` fixed.

However, `www` finds no results.

**Comment by dlangille** [comment]
Interesting. Searching for `QuakeForge` on prod finds [quakeforge](https://www.freshports.org/games/quakeforge/)

**Comment by dlangille** [comment]
A copy of the production dataabase was loaded into another FreshPorts node last night. Today, the search on that node works as expected. This makes me think production does not have the right stuff for full text search.

**Comment by dlangille** [comment]
I've ask the list: https://www.postgresql.org/message-id/9f89f00a-e400-4a9b-803b-f84999b6ffca%40app.fastmail.com

**Comment by dlangille** [comment]
Blog post #1: https://news.freshports.org/2022/12/18/when-tsvector-was-working-as-expected-on-most-hosts-but-not-one/

**Comment by dlangille** [comment]
Blog post \#2: https://news.freshports.org/2022/12/23/moving-from-storing-the-tsvector-values-to-a-tsvector-index/

**Comment by dlangille** [comment]
This is now in production.

**Comment by grahamperrin** [comment]
Wow.

**Comment by dlangille** [comment]
> Wow.

This has too man interpretations. :)

**Comment by grahamperrin** [comment]
… the approaches that you take to documenting/expressing things here, in your blog posts, and elsewhere. Including thought processes. Excellence. 

I'm usually quiet in my appreciation (and GitHub reactions etc. are often late), but sometimes I'm wowed by the whole caboodle, and one word covers it. 

Wow, and a happy new year to you and yours.

**Comment by dlangille** [comment]
Thanks. I like to record the information because the problem may occur again. :)
