### ISSUE TITLE
Search by pkg-plist is broken

### ISSUE THREAD

**Issue by endrift** [FreshPorts/freshports#402]
Error message is as follows, with any and all queries I've tried:
>  Parse error: syntax error, unexpected identifier "count", expecting "," or ";" in /usr/local/www/freshports/classes/ports_by_pkg_plist.php on line 62

**Comment by endrift** [comment]
Looks like the actual error is on line 58: https://github.com/FreshPorts/freshports/blob/master/classes/ports_by_pkg_plist.php#L58

It's a simple enough fix.

**Comment by dlangille** [comment]
This is fixed, and I stumbled across it today without remembering this issue.
