### ISSUE TITLE
ViewVC exception, 404 not found

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#403]
For example, through a click on the Subversion icon at <https://www.freshports.org/textproc/py-extract-msg/>: 

<https://svnweb.freebsd.org/ports/head/textproc/py-extract-msg/>

> An Exception Has Occurred
> 
> Unknown location: /head/textproc/py-extract-msg
> HTTP Response Status
> 
> 404 Not Found

It's genuinely a new port; an SVN icon is not expected.

**Comment by dlangille** [comment]
The problem to solve:

How to know if a port has svn history.

**Comment by dlangille** [comment]
A new icon was created and will be displayed when the port was added to the repo after `2022-10-25 18:42:09` (the date of the last subversion commit).
![Screen Shot 2022-12-31 at 9 28 34 AM](https://user-images.githubusercontent.com/1626436/210140149-6a3828fd-56eb-4a03-a9b3-0189e499fad5.png)
![Screen Shot 2022-12-31 at 9 27 35 AM](https://user-images.githubusercontent.com/1626436/210140152-f0569dfe-8ca0-44c2-923f-95c990121460.png)

**Comment by dlangille** [comment]
Now on prod.
