### ISSUE TITLE
Search: Makefile (ports only): results for a website or domain in the context of WWW

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#406]
After raising FreeBSD bug [267686 – emulators/qemu, emulators/qemu-devel, emulators/qemu-user-static: review WWW](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267686), I aimed to seek any other port for which the WWW is currently: 

`https://wiki.qemu.org/Main_Page`

Seeking that string, verbatim, did not have the required effect (no real surprise). Instead, I sought: 

`wiki.qemu.org`

<https://www.freshports.org/search.php?stype=makefile&method=match&query=wiki.qemu.org&num=30&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head> finds only two of the three ports that were identified in bug 267686. 

Please, is this an issue with FreshPorts, or am I overlooking something? 

Not found: **emulators/qemu-user-static**

<https://cgit.freebsd.org/ports/tree/emulators/qemu-user-static/Makefile#n10>: 

> `WWW=		https://wiki.qemu.org/Main_Page`

**Comment by dlangille** [comment]
It is not found because the database contains stale data for that column:
```
freshports.devgit=# select makefile from ports where id in (select id from ports_active where name = 'qemu-user-static') limit 10;
                                          makefile                                          
--------------------------------------------------------------------------------------------
 
 
 
 # Created by: nox@FreeBSD.org                                                             +
 # $FreeBSD: head/emulators/qemu-user-static/Makefile 441455 2017-05-22 13:17:38Z linimon $+
                                                                                           +
 MAINTAINER=     sbruno@FreeBSD.org                                                        +
 COMMENT=        QEMU CPU Emulator github bsd-user branch - static user targets            +
 PKGNAMESUFFIX=  -user-static                                                              +
                                                                                           +
 QEMU_USER_STATIC=       yes                                                               +
 PKGMESSAGE=     /dev/null                                                                 +
 DESCR=          ${.CURDIR}/pkg-descr                                                      +
 OPTIONS_SLAVE=  STATIC_LINK BSD_USER X86_TARGETS                                          +
 OPTIONS_EXCLUDE=SAMBA X11 GTK2 OPENGL GNUTLS SASL JPEG PNG CURL \                         +
                 CDROM_DMA PCAP USBREDIR GNS3 DOCS                                         +
 MASTERDIR=      ${.CURDIR}/../qemu-sbruno                                                 +
 CONFIGURE_ARGS+=        --extra-cflags=-D_IFI_OQDROPS                                     +
                                                                                           +
 NOT_FOR_ARCHS=          powerpc64                                                         +
 NOT_FOR_ARCHS_REASON=   error: Unhandled abi                                              +
                                                                                           +
```

**Comment by dlangille** [comment]
I first suspected this was related to the two mega-commits surrounding the move of `WWW` from `pkg-descr` to `Makefile`:

- [Remove WWW entries moved into port Makefiles](https://cgit.freebsd.org/ports/commit/?id=fb16dfecae4a6efac9f3a78e0b759fb7a3c53de4) 
- [Add WWW entries to port Makefiles](https://cgit.freebsd.org/ports/commit/?id=b7f05445c00f2625aa19b4154ebcbce5ed2daa52)

It took a while to catch up and one of the things I missed was updating the `Makefile` entry. This is updated on every commit but for ports with no subsequent commits it will remain old.

Then I looked at another port:
```
freshports.devgit=# select makefile from ports where id in (select id from ports_active where name = 'anvil');
                                         makefile                                         
------------------------------------------------------------------------------------------
 # $FreeBSD: head/sysutils/anvil/Makefile 451386 2017-10-06 15:05:48Z dvl $              +
                                                                                         +
 PORTNAME=       anvil                                                                   +
 PORTVERSION=    0.0.11                                                                  +
 PORTREVISION=   1                                                                       +
 CATEGORIES=     sysutils                                                                +
                                                                                         +
...
```

That is also outdated. Now I suspect `Makefile` is not being updated properly at all.

**Comment by dlangille** [comment]
I think this confirms the 'makefile not being updates' theory.

```
freshports.devgit=# select id, makefile from ports where id in (select id from ports_active where name = 'ot-recorder');
  id   | makefile 
-------+----------
 54134 | 
(1 row)

freshports.devgit=# 
```

**Comment by dlangille** [comment]
changes packaged and installed on test.

**Comment by dlangille** [comment]
test is good. Now on staging.

**Comment by dlangille** [comment]
Confirmed good on staging.

**Comment by dlangille** [comment]
Confirmed good on prod.

**Comment by dlangille** [comment]
The next step, run a one-off script to refresh `Makefile` for each port on `head`.

**Comment by dlangille** [comment]
Now updating dev:

`[dev-ingress01 dan ~/modules/Verify] % echo perl ./refresh-all-active-ports.pl | sudo su -fm freshports > /tmp/refresh-all-active-ports.log`

ETA 0000-0400 UTC

**Comment by dlangille** [comment]
Restarting after dealing with #407

**Comment by dlangille** [comment]
Let's say one second per port, 45000/60/60 or 12.5 hours...

**Comment by dlangille** [comment]
Finished at about 2022.12.11 12:53

**Comment by dlangille** [comment]
The original search phrase is no longer valid. The `Makefile`s have since been modified. Now the `WWW` value is `www.qemu.org`. That search finds 7 ports on dev:

1. emulators/qemu
2. emulators/qemu-devel
3. emulators/qemu-guest-agent
4. emulators/qemu-user-static
5. emulators/qemu-user-static-devel
6. emulators/qemu6
7. emulators/qemu70

**Comment by dlangille** [comment]
While waiting for @grahamperrin to confirm, I'll run the update script on both `test` and `stage` concurrently.

Adding full text searches on `Makefile` is for future consideration.

**Comment by grahamperrin** [comment]
> … finds 7 ports on dev: …

The same for me, thanks. 

<https://dev.freshports.org/search.php?stype=makefile&method=match&query=www.qemu.org&num=100&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head>

From the foot of text-only <https://dev.freshports.org/search.php?stype=makefile&method=match&query=www.qemu.org&num=100&orderby=category&orderbyupdown=asc&search=Search&format=plaintext&branch=head>: 

```text
here we are2NumFetches = 7WHAT IS THIS?emulators/qemu
emulators/qemu-devel
emulators/qemu-guest-agent
emulators/qemu-user-static
emulators/qemu-user-static-devel
emulators/qemu6
emulators/qemu70
```

`stage` and `www` also find seven: 

```text
emulators/qemu
emulators/qemu-devel
emulators/qemu-guest-agent
emulators/qemu-user-static
emulators/qemu-user-static-devel
emulators/qemu6
emulators/qemu70
```

**Comment by dlangille** [comment]
Yeah dev has some debug on.

**Comment by dlangille** [comment]
@grahamperrin prod is done.

**Comment by grahamperrin** [comment]
Excellent, thanks. 

(I see the 2022-12-14 0110 UTC message at the production site.)

Close?

**Comment by yurivict** [comment]
I've developed [PortsDB](https://github.com/yurivict/freebsd-portsdb) that rebuilds in 20 minutes and contains all essential information about ports.

It builds the SQLite DB: https://people.freebsd.org/~yuri/ports.sqlite

Maybe FreshPorts can consider using it some time in the future.

FreshPorts can, for example, show what other ports depend on a particular port, like [Spack](https://packages.spack.io/) does.

**Comment by dlangille** [comment]
> I've developed [PortsDB](https://github.com/yurivict/freebsd-portsdb) that rebuilds in 20 minutes and contains all essential information about ports.

I've been looking, it seems to do this in parallel? I ask because I see `-j $(sysctl -n hw.ncpu)` in `functions.sh` under `ports_tree_traverse()`

What is `make -I` doing?

Where is data extracted from the ports tree for a specific port? I could not find that.

I have thought about making my maintenance scripts run in parallel instead of serial. My main concern: updating master ports first before any slave ports.

> It builds the SQLite DB: https://people.freebsd.org/~yuri/ports.sqlite
> 
> Maybe FreshPorts can consider using it some time in the future.
> 
> FreshPorts can, for example, show what other ports depend on a particular port, like [Spack](https://packages.spack.io/) does.

FreshPorts does not have a user interface like Spack, but it does show the dependencies. For example, at https://www.freshports.org/shells/bash/#dependencies the run time dependencies are shown. Both the forward (what does this port need (`RUN_DEPENDS`)) and the reverse (what ports require this port) are shown.
