### ISSUE TITLE
Ignore: the answer, and contexts

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#408]
From <https://github.com/FreshPorts/freshports/issues/381#issue-1364636011>: 

> … This is not a priority for completion. There is a high work/risk/reward ratio.

Understood. 

In the meantime, maybe we can – with low risk and relatively little work – improve things such as [the answer](https://www.freshports.org/faq.php#ignore) to the FAQ. 

Currently: 

> Ignore: The port is marked as ignore. It probably does not build. Packages for an ignored port are not built by the package cluster. Therefore, `pkg install` will not work.

### An example

<https://www.freshports.org/sysutils/hammer2/> 

The _IGNORE_ phrase is clear enough: 

> Not supported on FreeBSD 12

The table of packages <https://www.freshports.org/sysutils/hammer2/#packages> includes some for `FreeBSD:13:⋯` and some for `FreeBSD:14:⋯`: 

* all built by the cluster.

<https://www.freshports.org/sysutils/hammer2/#add>: 

> **To install [the port](https://www.freshports.org/faq.php#port):**
>     `cd /usr/ports/sysutils/hammer2/ && make install clean`
> 
> **A [package](https://www.freshports.org/faq.php#package) is not available for ports marked as:**
>     **Forbidden / Broken / Ignore / Restricted**
> 
> **PKGNAME:** hammer2

* this could, more usefully, **include** the two `pkg install ⋯` options **and not** state that a package is not available

𣀓– would it be useful to have the _ignore_ blurb closer to the table?

![image](https://user-images.githubusercontent.com/192271/206893184-873a9369-69c2-4df8-a0a3-f415a1284ba5.png)

----

@dlangille initial thoughts? 

TIA

**Comment by dlangille** [comment]
How about repeating `broken` and `ignore` just above <b>Packages</b>?

**Comment by dlangille** [comment]
I'm having trouble parsing this one.

Is this the goal: For ports marked as "Forbidden / Broken / Ignore / Restricted", instead of showing

```
To add the [package](https://www.freshports.org/faq.php#package), run one of these commands:
pkg install sysutils/hammer2
pkg install hammer2
```

Show:

```
We doubt there is a package available for this port because we see it marked as Forbidden / Broken / Ignore / Restricted. That said, the instructions are:

To add the [package](https://www.freshports.org/faq.php#package), run one of these commands:
pkg install sysutils/hammer2
pkg install hammer2
```

NOTE: FreshPorts can't detect BROKEN IGNORE etc on all platforms.  Some are broken on i386, some on 12.x, etc. We'd need to set up N jails and detect in each one, etc...

**Comment by grahamperrin** [comment]
Sorry, I lost track of this. I'll try to make headspace for it this weekend.

**Comment by grahamperrin** [comment]
> `We doubt there is a package available for this port because we see it marked as …`

Nit: the combination of _there is_ and _available_. 

Instead, maybe, something like one of these: 

> `We doubt that a package is available, because the port is marked as …`

> `Packages are normally not provided for ports that are marked as …`


----

<https://www.freshports.org/sysutils/hammer2/> no longer presents an _IGNORE_ phrase. 

An alternative example: <https://www.freshports.org/net/citrix_ica/>

**Comment by dlangille** [comment]
See https://dev.freshports.org/biology/ucsc-userapps/

**Comment by grahamperrin** [comment]
> Restricted Package not available

That sounds like non-availability of a _restricted package_.

Better with an en dash?

> Restricted – Package not available

**Comment by grahamperrin** [comment]
> `We doubt a <b><a href="[/faq.php#package](view-source:https://dev.freshports.org/faq.php#package)" title="what is a package?">package</a> is` …

Should have a closing `</b>`: 

> `We doubt a <b><a href="[/faq.php#package](view-source:https://dev.freshports.org/faq.php#package)" title="what is a package?">package</a></b> is` …

**Comment by dlangille** [comment]
Fixed the `bold` issue.

Next: I moved the reasons why there may be no package into a list.

```
We doubt a [package](https://dev.freshports.org/faq.php#package) is available for this port because we see it marked as as:
* Restricted
* Package not available
```
