### ISSUE TITLE
rss per branch?

### ISSUE THREAD

**Issue by ronaldklop** [FreshPorts/freshports#41]
Thanks for this amazing site. I already use it for years.
Since the support for branches the rss feed contains everything which I think is a bit confusing if you do not follow a branch or even more when you do follow a branch.
Is it possible to get the rss per branch? Or only the changes on head/trunk?

**Comment by dlangille** [comment]
see also #40

**Comment by dlangille** [comment]
This commit prepares for this feature.

https://github.com/FreshPorts/freshports/commit/4d2df8168be4cae1f83da7e3c21424b6aacd32a3

**Comment by dlangille** [comment]
This commit implements this feature.

https://github.com/FreshPorts/freshports/commit/d22c5cc4f94cea4bb331e09948abb0116e83fa2c

**Comment by dlangille** [comment]
Now in production. Please confirm and reopen this ticket if you see an issue.

**Comment by ronaldklop** [comment]
Thanks a lot!
