### ISSUE TITLE
vuxml - displaying details for a vuln generates errors

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#421]
For package `samba413`: 

* dev <https://dev.freshports.org/vuxml.php?package=samba413> counts seven (7) vulnerabilities and, at a glance, [the list](https://dev.freshports.org/vuxml.php?vid=1c5f3fd7-54bf-11ed-8d1e-005056a311d1%7C1f6d97da-8f72-11eb-b3f1-005056a311d1%7C646923b0-41c7-11ec-a3b2-005056a311d1%7C6f33d38b-aa18-11eb-b3f1-005056a311d1%7C8579074c-839f-11ec-a3b2-005056a311d1%7C9ca85b7c-1b31-11eb-8762-005056a311d1%7Cf9140ad4-4920-11ed-a07e-080027f5fec9) does comprise seven ☑
* production <https://www.freshports.org/vuxml.php?package=samba413> counts seven, leads to <https://www.freshports.org/vuxml.php?vid=1c5f3fd7-54bf-11ed-8d1e-005056a311d1%7C1f6d97da-8f72-11eb-b3f1-005056a311d1%7C646923b0-41c7-11ec-a3b2-005056a311d1%7C6f33d38b-aa18-11eb-b3f1-005056a311d1%7C8579074c-839f-11ec-a3b2-005056a311d1%7C9ca85b7c-1b31-11eb-8762-005056a311d1%7Cf9140ad4-4920-11ed-a07e-080027f5fec9> three warnings, one listing and a fatal error

[FreshPorts - VuXML.pdf](https://github.com/FreshPorts/freshports/files/10314515/FreshPorts.-.VuXML.pdf)

> The VUXML data was last processed by FreshPorts on 2022-12-28 00:09:42 UTC

**Comment by grahamperrin** [comment]
(Something about this makes me think it's a duplicate of, or overlapping with, another issue, but I can't find a match …)

**Comment by dlangille** [comment]
The error is:

Warning: pg_query(): Query failed: ERROR: function getcategoryportfrompackagename(text) does not exist LINE 1: SELECT vuxml_names.*, GetCategoryPortFromPackageName(name) a... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. in /usr/local/www/freshports/classes/vuxml_names.php on line 28

**Comment by dlangille** [comment]
Similar errors on test and stage.

**Comment by dlangille** [comment]
This is related to #346 wherein `GetCategoryPortFromLatestLink()` was renamed to `GetCategoryPortFromPackageName()`

**Comment by dlangille** [comment]
Fixed via:

* committing changes from dev to `sp.txt` and `views.sql`
* running these commands in `psql`:
```
drop view ports_all;drop view ports_active;
\i views.sql
\i permissions.sql
\i ri.txt
\i sp.txt
commit;
```
