### ISSUE TITLE
Empty/blank plain text search result

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#425]
<https://www.freshports.org/search.php?stype=name&method=prefix&query=ldb&num=10&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head> for port name starting with _ldb_:

* finds four ports. 

<https://www.freshports.org/search.php?stype=name&method=prefix&query=ldb&num=10&orderby=category&orderbyupdown=asc&search=Search&format=plaintext&branch=head> (plain text equivalent): 

* is blank … as if nothing is found?

**Comment by dlangille** [comment]
I think it's a logic error, based on this fix for `dev` - try it there:

```
[dev-nginx01 dan ~/www] % git diff www/search.php                                                              19:41:20
diff --git a/www/search.php b/www/search.php
index 0ff76358..251fe1f5 100644
--- a/www/search.php
+++ b/www/search.php
@@ -1194,9 +1194,9 @@ Special searches:
 
                } /* NumFetches  != 0 */
 
-               if ($output_format == OUTPUT_FORMAT_HTML) {
-               
                        echo $HTML;
+               if ($output_format == OUTPUT_FORMAT_HTML) {
+
 ?>
 </table>
 
@@ -1227,7 +1227,7 @@ document.search.query.focus();
                } /* OUTPUT_FORMAT_HTML */
 
                if ($output_format !== OUTPUT_FORMAT_PLAIN_TEXT) {
-?>
+?>¨
 </body>
 </html>
 ```

**Comment by grahamperrin** [comment]
Thanks, confirmed good with `dev`. The result: 

```text
databases/ldb15
databases/ldb20
databases/ldb21
databases/ldb22
```
