### ISSUE TITLE
should suppress *_FOR_ARCHS if nil

### ISSUE THREAD

**Issue by allanjude** [FreshPorts/freshports#43]
Each search result, and each details page now displays:

ONLY_FOR_ARCHS: nil
NOT_FOR_ARCHS: nil

For something with an ONLY_FOR_ARCHS defined, you get:

ONLY_FOR_ARCHS: amd64
NOT_FOR_ARCHS: nil

The line should not display if the value is nil

**Comment by dlangille** [comment]
Have you noticed this has changed recently?

**Comment by allanjude** [comment]
I had not noticed, but looking at the source code:

https://github.com/FreshPorts/freshports/commit/551e712c1c0fc15fff1f6de2f11669aa4f34f7fd

You added the display in January.

I have created a pull request #44 that changes the code to only display then when they are not nil.

**Comment by dlangille** [comment]
With that pull request merged, and nothing said lately, closing this one.
