### ISSUE TITLE
lots of problems involving multiple watchlists

### ISSUE THREAD

**Issue by rwv37** [FreshPorts/freshports#443]
I've noticed over the past few months or so that there are a bunch of problems related to having more than one watch list. I've found workarounds for them (generally speaking, set your default watch list to the watch list you're interested in at the moment), but I figure I really should be opening issues for them. I will do so as I encounter (or remember) them.

The one I just ran into a moment ago:

If you select Watch Lists/Ports, you'll be brought to the list of ports in your default watch list, sorted by last update time. If you then select some other watch list (from the dropdown box), you'll be brought to the list of ports in that watch list, sorted by last update time. That's all fine so far. But:

If you then select a different display order (e.g. "category"), you will be shown _your default_ watch list (sorted by category).

**Comment by dlangille** [comment]
That's amazing. I can reproduce that on dev.freshports.org - this should be quickly fixed.

**Comment by rwv37** [comment]
Thank you! Like I said, though, there are a lot of problems that very strongly seem to be related to this, so it might be worthwhile to look beyond this very specific instance of such a problem.

**Comment by rwv37** [comment]
Off the top of my head, I think that (but don't remember the details of) there's a problem of this sort somehow related to the "+"/"-" buttons on a port (for adding/removing from watch lists), and also some involving the "Manage" page (like, maybe some operations operate on the default list rather than the selected list).

**Comment by dlangille** [comment]
The `watch.php` problem relates to links. The hyperlinks for sorting do not specify the watch list name/id. If they did, this would work.

**Comment by dlangille** [comment]
Committed code at https://github.com/FreshPorts/freshports/compare/443-multiple-watchlists?expand=1

**Comment by dlangille** [comment]
> Off the top of my head, I think that (but don't remember the details of) there's a problem of this sort somehow related to the "+"/"-" buttons on a port (for adding/removing from watch lists), and also some involving the "Manage" page (like, maybe some operations operate on the default list rather than the selected list).

I suspect the above may be related to the problem I just fixed. However, I have no investigated what you describe above. I may be able to come back to this later today.

**Comment by dlangille** [comment]
I will restore a fresh copy of production onto `test.freshports.org` and put the new code up there.  I'll let you know when it's ready.

`dev` is a mixture of code right now.

**Comment by dlangille** [comment]
@rwv37 Please try at test.freshports.org - it now has a copy of yesterday's backup of production.

**Comment by dlangille** [comment]
Thank you. Now on production. All OK over there too? @rwv37

**Comment by rwv37** [comment]
Seems fine there too.

**Comment by dlangille** [comment]
Good. Thank you for letting me know. This problem was affecting everyone.
