### ISSUE TITLE
Search: … pg_exec(): Query failed: ERROR: invalid byte sequence for encoding "UTF8": 0xe1 0x66 0x69 in /usr/local/www/freshports/www/search.php on line 908

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#447]
1. <https://www.freshports.org/search.php?stype=name&method=match&query=office&num=500&orderby=port&orderbyupdown=asc&search=Search&format=html&branch=head> (port name contains _office_, sort by port, ascending, 500 results)
2. broaden the search to include deleted ports

> `Warning: pg_exec(): Query failed: ERROR: invalid byte sequence for encoding "UTF8": 0xe1 0x66 0x69 in /usr/local/www/freshports/www/search.php on line 908`
> `something went terribly wrong. Sorry.`

**Comment by dlangille** [comment]
Cannot be repeated on `dev`, `test`, or `stage`; they return 390 results.

**Comment by dlangille** [comment]
```
git fetch origin
git checkout 447-search-pg_exec-query-failed-error-invalid-byte-sequence-for-encoding-utf8-0xe1-0x66-0x69-in-usrlocalwwwfreshportswwwsearchphp-on-line-908
git checkout tags/2.5.0.3
```
Even with code from most recent deployment.

**Comment by dlangille** [comment]
Fixed in prod. Thank you.

**Comment by grahamperrin** [comment]
Fix confirmed. Thanks!
