### ISSUE TITLE
Search results: more ports are counted than are listed

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#456]
<https://www.freshports.org/search.php?stype=pkg-message&method=match&query=net.local.stream.recvspace&num=50&orderby=category&orderbyupdown=asc&search=Search&format=html&minimal=1&branch=head> for _pkg-msg_ containing `net.local.stream.recvspace`

>  Number of ports: 4 

Only three are listed. [Plain text alternative](https://www.freshports.org/search.php?stype=pkg-message&method=match&query=net.local.stream.recvspace&num=50&orderby=category&orderbyupdown=asc&search=Search&format=plaintext&minimal=1&branch=head) to the minimal HTML results: 

```text
databases/akonadi
deskutils/kmail
www/e2guardian
```

Given [the message for deskutils/kmail](https://www.freshports.org/deskutils/kmail/#message), I wondered whether deskutils/kontact is missing from the list. Apparently not missing, it has no message: 

```text
% pkg iinfo kontact
kontact-23.08.0
kontactinterface-23.08.0
% pkg query %M kontact

% 
```

[rg(1)](https://man.freebsd.org/cgi/man.cgi?query=rg&sektion=1&manpath=freebsd-ports) (below) finds three, so: 

- I guess that **the count** in FreshPorts is somehow incorrect in this case. 

```text
% rg -e 'net.local.stream.recvspace' /usr/ports
/usr/ports/databases/akonadi/pkg-message
10:     sysctl net.local.stream.recvspace=65536

/usr/ports/deskutils/kmail/pkg-message
10:     sysctl net.local.stream.recvspace=65536

/usr/ports/www/e2guardian/files/pkg-message.in
33:         net.local.stream.recvspace=65535
% 
```

**Comment by grahamperrin** [comment]
The same discrepancy (Number of ports: 4) at `dev`. 

I checked there, because I have a vague memory of a count discrepancy being fixed in a different issue, although I can't find a matching issue.

**Comment by dlangille** [comment]
I suspect it is because the "how many are there?" query includes deleted ports, whereas the "display them" query gets more specific and shows only active ports. 

Fixed on dev.

**Comment by dlangille** [comment]
This is now in production.

**Comment by grahamperrin** [comment]
Confirmed fixed, with the originally given example. Thanks!
