### ISSUE TITLE
Tables of packages: FreeBSD:15: listings for FreeBSD 15.0-CURRENT

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#458]
#341 and #370 for stable/11 end of life. 

----

At <https://pkg-status.freebsd.org/builds?type=package> alongside jail names that begin with `14`, we now have eleven jail names that begin with `main-`, some of which are for: 

* FreeBSD 15.0-CURRENT.

Please add listings to tables of packages. Thanks

----

<details>
<summary>Note to self re: duplicate names</summary>

`main-amd64`, for example: 

1. <http://beefy18.nyi.freebsd.org/jail.html?mastername=main-amd64-default> 
2. <http://beefy19.nyi.freebsd.org/jail.html?mastername=main-amd64-default> with date-based build IDs, nothing recent. 

### beefy18

<https://pkg-status.freebsd.org/builds?type=package&all=1> sorted (Started (UTC)) builds in progress include <http://beefy18.nyi.freebsd.org/build.html?mastername=main-amd64-default&build=p563c845130a1_sfafb03ab42> in the `main-amd64` jail. The head of the log for built port number 1:

```text
=>> Building dns/public_suffix_list
build started at Tue Sep 12 01:23:08 UTC 2023
port directory: /usr/ports/dns/public_suffix_list
package name: public_suffix_list-20230827
building for: FreeBSD main-amd64-default-job-02 15.0-CURRENT FreeBSD 15.0-CURRENT 1500000 amd64
maintained by: sunpoet@FreeBSD.org
Makefile ident: 
Poudriere version: 3.2.8-23-ga7f8d188
Host OSVERSION: 1500000
Jail OSVERSION: 1500000
Job Id: 02

---Begin Environment---
SHELL=/bin/sh
OSVERSION=1500000
UNAME_v=FreeBSD 15.0-CURRENT 1500000
UNAME_r=15.0-CURRENT
…
```

</details>

**Comment by dlangille** [comment]
useful link: https://news.freshports.org/2021/02/10/adding-freebsd14-to-the-list-of-build-packages/

**Comment by dlangille** [comment]
I've removed 11 from `dev`:

```
freshports.devgit=# select * from abi where name like 'FreeBSD:11:%';
 id |        name        | active 
----+--------------------+--------
  4 | FreeBSD:11:i386    | t
  6 | FreeBSD:11:amd64   | t
  7 | FreeBSD:11:aarch64 | t
 14 | FreeBSD:11:mips64  | t
 25 | FreeBSD:11:armv6   | t
(5 rows)

freshports.devgit=# delete from abi where name like 'FreeBSD:11:%';
DELETE 5
d
```

**Comment by dlangille** [comment]
To me, `main` is a red herring. I want to add `15`, not `main`

**Comment by dlangille** [comment]
Added to `dev`:

```
[17:29 pg02 dan ~/bin] % psql freshports.devgit
psql (12.16, server 12.15)
Type "help" for help.

freshports.devgit=# begin;
BEGIN
freshports.devgit=# insert into abi (name) values 
('FreeBSD:15:amd64'), ('FreeBSD:15:armv6'), ('FreeBSD:15:armv7'), ('FreeBSD:15:i386'), ('FreeBSD:15:mips64'), ('FreeBSD:15:powerpc64'), ('FreeBSD:15:riscv64');
INSERT 0 7
freshports.devgit=# commit;
COMMIT
freshports.devgit=# 
```

**Comment by dlangille** [comment]
`test` and `stage` look good. Next: prod

**Comment by dlangille** [comment]
prod is done.

**Comment by grahamperrin** [comment]
Thanks! Close?

<details>
<summary>Example</summary>

Four URLs for sysutils/htop, alphabetical order:

* `dev` <https://dev.freshports.org/sysutils/htop/#packages>
* `stage`<https://stage.freshports.org/sysutils/htop/#packages>
* `test` <https://test.freshports.org/sysutils/htop/#packages>
* `www` <https://www.freshports.org/sysutils/htop/#packages>

</details>

**Comment by dlangille** [comment]
Yes, let's close.

**Comment by dlangille** [comment]
This is now in production.
