### ISSUE TITLE
Tables of packages: for 'repo not found' or 'never imported', do not display the fallout icon

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#460]
Currently under <https://www.freshports.org/x11/kde-baseapps/#packages>, for example: 

![image](https://github.com/FreshPorts/freshports/assets/192271/83e88678-5c92-4d6a-9c27-c8b943da63b2)

Re: <https://www.freshports.org/faq.php#fallout> it's feasible to expand the description, however it will be better (truer) to

* not present the fallout icon, where there is _definitely_ no_ fallout.

Thanks

**Comment by dlangille** [comment]
We have:

https://dev.freshports.org/x11/kde-baseapps/#packages

Now, I'm not sure how the code decides if the fallout symbol is displayed or not displayed.

**Comment by dlangille** [comment]
To be clear, I think the code has never queried fallout to see if there is fallout. It has only provided the link

**Comment by grahamperrin** [comment]
> … I think the code has never queried fallout to see if there is fallout. …

Without me digging up related issue numbers: I have the same recollection. 

Suggested label: [enhancement](https://github.com/FreshPorts/freshports/issues?q=is%3Aissue+label%3Aenhancement)

**Comment by dlangille** [comment]
I've removed the `fallout` graphics from  the `packages` section entirely.

reload: https://dev.freshports.org/x11/kde-baseapps/#packages

**Comment by dlangille** [comment]
You should see it now. Packages are processed at the top of the hour.

**Comment by dlangille** [comment]
Data added to `test` and `stage`.

**Comment by dlangille** [comment]
This is now in production.

**Comment by grahamperrin** [comment]
Thanks! Neat (clean).
