### ISSUE TITLE
riscv64 (not riskv64)

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#463]
Seen at `dev` pages such as <https://dev.freshports.org/archivers/py-lz4/#packages>: 

> FreeBSD:13:riskv64

**Comment by dlangille** [comment]
It should be deleted, not renamed.

```
freshports.devgit=# update abi set name = 'FreeBSD:13:riscv64' where name = 'FreeBSD:13:riskv64';
ERROR:  duplicate key value violates unique constraint "abi_name_idx"
DETAIL:  Key (name)=(FreeBSD:13:riscv64) already exists.
```

```
freshports.devgit=# delete from abi where name = 'FreeBSD:13:riskv64';
DELETE 1
```

**Comment by dlangille** [comment]
Not found on `test` or `stage`.

**Comment by grahamperrin** [comment]
Ah, OK. If it helps, <https://github.com/FreshPorts/freshports/issues/364#issuecomment-1336428301> included these three lines (amongst others):

```text
 34 | FreeBSD:13:riscv64   | t
 37 | FreeBSD:13:riskv64   | t
 26 | FreeBSD:14:aarch64   | t
```

**Comment by dlangille** [comment]
Not found on `prod`:

```
freshports.org=> select * from abi where name ilike '%risk%';
 id | name | active 
----+------+--------
(0 rows)

```

**Comment by dlangille** [comment]
> Ah, OK. If it helps, [#364 (comment)](https://github.com/FreshPorts/freshports/issues/364#issuecomment-1336428301) included these three lines (amongst others):
> 
> ```
>  34 | FreeBSD:13:riscv64   | t
>  37 | FreeBSD:13:riskv64   | t
>  26 | FreeBSD:14:aarch64   | t
> ```

If I understand correctly, only line 37 is relevant to this issue. If so, that has been covered by comment https://github.com/FreshPorts/freshports/issues/463#issuecomment-1728569380
