### ISSUE TITLE
Add Codeberg links for non-ports commits?

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#469]
Spun off from #392

<https://www.freshports.org/commit.php?category=security&port=openssl&files=yes&message_id=d5ec2e12f399b7813994564b77a0915821a0ac42>, for example: 

![image](https://github.com/FreshPorts/freshports/assets/192271/ec3492a6-a818-4906-8e05-c82aa4098ff3)

More broadly, <https://www.freshports.org/MOVED> and <https://www.freshports.org/UPDATING>.

**Comment by dlangille** [comment]
Add on `dev` for ports commits.

Not correct for `src` and `doc`.
