### ISSUE TITLE
Order of icons: cgit, Codeberg, GitHub, GitLab, SVNWeb

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#471]
A cosmetic and muscle memory issue. 

Within a page for a port, the order is good. Alphabetical, with primary mirror cgit first. 

Under `www` <https://www.freshports.org/security/openssl/#description>, for example: 

![image](https://github.com/FreshPorts/freshports/assets/192271/3d63d373-d03f-4b7c-9029-f36c2e7303b5)

----

At the `dev` home page, and at e.g. `dev` <https://dev.freshports.org/commit.php?category=security&port=openssl&files=yes&message_id=d5ec2e12f399b7813994564b77a0915821a0ac42>, the order is different: 

![image](https://github.com/FreshPorts/freshports/assets/192271/0f3550dc-3702-4df7-bef1-8272a32b1dfd)

![image](https://github.com/FreshPorts/freshports/assets/192271/38a2f1e9-8635-4160-90a9-7d518a5d4379)

**Comment by dlangille** [comment]
Fixed?

**Comment by grahamperrin** [comment]
Yes! Thanks. 

Random picks, all OK: 

* <https://dev.freshports.org/MOVED>
* <https://dev.freshports.org/UPDATING>
* <https://dev.freshports.org/?branch=quarterly>
