### ISSUE TITLE
Search categories?

### ISSUE THREAD

**Issue by patmaddox** [FreshPorts/freshports#473]
I want to view a list of ports in `ports-mgmt`, ordered by most recently updated. Is there a way to do that? The closest I’ve found is [“under a pathname”](https://www.freshports.org/search.php?stype=tree&method=match&query=ports-mgmt&num=10&orderby=lastupdate&orderbyupdown=desc&search=Search&format=html&branch=head) which looks like it returns commits rather than port information.

**Comment by dlangille** [comment]
We have https://www.freshports.org/ports-mgmt/

But you can't search that.

**Comment by dlangille** [comment]
This search query comes to mind: `site:www.freshports.org/net-mgmt/` - use it on DuckDuckGo or Google, for example.

**Comment by dlangille** [comment]
The technical side is straight forward.  I'm having trouble coming up with the user interface.

`select * from ports where name ilike '%search_string%' and category = 'foo'`

**Comment by patmaddox** [comment]
Searching within a category would be cool, and is above and beyond what I was thinking.

I had in mind a “category” option in the main search drop down list. My use case is wanting to list all ports in a category, ordered by when last updated.

So..l maybe you want to add sort links on the category page, or some way of searching categories.

but for my purposes, adding “category” to the drop-down list on search page does the job.

**Comment by grahamperrin** [comment]
Drive-by comment (without giving real thought):

<https://www.freshports.org/ports-mgmt/> add _Sort by_

**Comment by dlangille** [comment]
> Drive-by comment (without giving real thought):
> 
> https://www.freshports.org/ports-mgmt/ add _Sort by_

Right now, it's sorted by portname.  What other options are useful?

**Comment by dlangille** [comment]
> but for my purposes, adding “category” to the drop-down list on search page does the job.

I have changes underway for #447  which affect search already.

I'll either commit them and work on this, or do them both at the same time. We shall see.

**Comment by patmaddox** [comment]
> Right now, it's sorted by portname. What other options are useful?

I would like to be able to sort by created, and updated.

**Comment by dlangille** [comment]
First draft of search by category. Not widely tested. There are probably some combinations which are illogical.

**Comment by dlangille** [comment]
For me, later. This will be used to update the cached list of categories, so that each load of `search.php` does not query for the last of categories.

```
freshports.devgit=# select '            <OPTION VALUE="' || name || '" <?php if ($category == ''' || name || ''') echo ''SELECTED''?>>' || name || '</OPTION>' from categories order by name;
                                                                ?column?                                                                 
-----------------------------------------------------------------------------------------------------------------------------------------
                 <OPTION VALUE="accessibility" <?php if ($category == 'accessibility') echo 'SELECTED'?>>accessibility</OPTION>
                 <OPTION VALUE="afterstep" <?php if ($category == 'afterstep') echo 'SELECTED'?>>afterstep</OPTION>
                 <OPTION VALUE="arabic" <?php if ($category == 'arabic') echo 'SELECTED'?>>arabic</OPTION>
                 <OPTION VALUE="archivers" <?php if ($category == 'archivers') echo 'SELECTED'?>>archivers</OPTION>
,,,
```

**Comment by patmaddox** [comment]
I must be dense - how do I view ports-mgmt ports ordered by updated at?

**Comment by patmaddox** [comment]
Perhaps this is a clue on the search page:

> The list of categories is not available - the cache file does not exist - This should never happen.

**Comment by dlangille** [comment]
@patmaddox This is fixed in `dev` and `test`. `stage` has always been updated but not yet tested. Same with `prod`.

**Comment by dlangille** [comment]
> Perhaps this is a clue on the search page:
> 
> > The list of categories is not available - the cache file does not exist - This should never happen.

This is what I mean by 'fixed' in my previous comment.

**Comment by patmaddox** [comment]
Cool, I’m now able to view all ports in a category sorted by last updated by searching for ` ` (space) in the description - thank you!!

**Comment by dlangille** [comment]
> Cool, I’m now able to view all ports in a category sorted by last updated by searching for ` ` (space) in the description - thank you!!

A proper sort within category will be carried out under #490
