### ISSUE TITLE
Arrangement of icons, and presentation of texts, for multi-file entries such as those in UPDATING

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#474]
From `dev` <https://dev.freshports.org/UPDATING?page=3>: 

<details>
<summary>Screenshot</summary>

![image](https://github.com/FreshPorts/freshports/assets/192271/d29133fe-9fb2-4fb6-b0f8-cd61ca0f2c86)

</details>

I do like/love that icons for Git mirror links have been added, for each file. 

However: when I first encountered the new style, and then focused on a single entry, it took a little time for me to figure out what was going on. The first encounter was probably something like this: 

![image](https://github.com/FreshPorts/freshports/assets/192271/53f4f368-dc56-49cb-b08f-4430e5eb9a52)

IMHO, presentation would be better: 

* without bold
* with fewer variations between font sizes
* with a monospaced font for file paths
* without the staggering of icons, i.e. somehow tabulate things. 

The fourth point is potentially tricky. I'll add a comment with a first thought on how it might be addressed, unless you'd like to come up with something first …

Thanks

**Comment by dlangille** [comment]
Yeah, for that, we're going to need some CSS help I reckon.

**Comment by grahamperrin** [comment]
Remind me where the code is, I might take a look.

**Comment by grahamperrin** [comment]
> * without the staggering of icons, i.e. somehow tabulate things.
> 
> 
> … potentially tricky. I'll add a comment with a first thought on how it might be addressed, …

<https://nitter.net/peteranthropos/status/1717622782018621884> is exactly what I had in mind. 

Further: make this true for the first line. So, for example: 

> [ 17:30 Bernard Spil (brnrd) _magnifying glass_ ] icon icon icon icon `hash`

might become: 

> icon icon icon icon `hash` 17:30 Bernard Spil (brnrd) _magnifying glass_

**Comment by dlangille** [comment]
see See https://twitter.com/DLangille/status/1717586605752435048

![Screenshot 2023-10-26 at 4 29 20 PM](https://github.com/FreshPorts/freshports/assets/1626436/8577f9a8-60b6-4132-b264-b5a1d97bcbf3)

**Comment by dlangille** [comment]
How about moving those icons below?

* bold gone
* smaller font gone
* monospace font
* icons aligned

![Screenshot 2023-10-27 at 12 36 09 PM](https://github.com/FreshPorts/freshports/assets/1626436/6ed3a33e-0bf3-4380-ae68-2fa5654df04c)

**Comment by dlangille** [comment]
Next, I need to adjust the display for this situation:

https://dev.freshports.org/commit.php?message_id=7636b89500e53864a53949054ad95102e1b87f35

<img width="1117" alt="Screenshot 2023-10-28 at 2 42 43 PM" src="https://github.com/FreshPorts/freshports/assets/1626436/85a7a3fa-2689-44c7-8ab2-ba1cc6b73fe9">

**Comment by dlangille** [comment]
This is the first draft of the new layout. 

* commit message at the top
* no port descriptions
* no NEW!
* no link to files in that commit
* no past vuln link
* no Fallout link

![Screen Shot 2023-10-29 at 11 45 37 AM](https://github.com/FreshPorts/freshports/assets/1626436/6afa957a-e06c-4d3a-b346-983af653d926)


This is the second draft of that layout:
![Screen Shot 2023-10-29 at 12 02 49 PM](https://github.com/FreshPorts/freshports/assets/1626436/cee08b84-ad76-4cc2-a708-4ea6a898f48a)

**Comment by dlangille** [comment]
This also affects the front page:

![Screen Shot 2023-10-29 at 12 33 01 PM](https://github.com/FreshPorts/freshports/assets/1626436/c7b10c2d-f7ab-48e4-8a89-0d166b15ac21)

**Comment by grahamperrin** [comment]
Nice!

If not too drastic a change: try black, or dark grey, for commit log messages?

**Comment by dlangille** [comment]
I think that looks better:

![Screen Shot 2023-10-29 at 4 01 10 PM](https://github.com/FreshPorts/freshports/assets/1626436/492c9dca-e2f3-4626-a5ec-9c459643a44b)

I have applied that color change to:

* pkg-message
* port-description
* conflicts
* PKGNAME
* ONLY_FOR_ARCHS
* Master port
* Dependencies
* 


See https://dev.freshports.org/editors/lazarus-qt6-devel for examples

**Comment by grahamperrin** [comment]
_Sweet_. 

Final suggestions (I'm not sure how the first one will look, in practice): 

* remove the `[ … ]` square brackets from the first line of commit metadata
* remove the `< … | … | … >` angle brackets from chronological navigation (pictured below)
* order left-to-right, chronologically `{Precedingdate} | {Subsequentdate} | Latest`
* non-abbreviated day of the week in the date line
* present the number of commits within (not above) the date line, for example

> Tuesday, 24 Oct 2023: 80 commits

![image](https://github.com/FreshPorts/freshports/assets/192271/0bcf16c9-6af6-4bd8-99df-185b3aa8701b)

<details>
<summary>Another current dev screenshot, including credits to authors</summary>

From <https://dev.freshports.org/date.php?date=2023/10/24>:

![image](https://github.com/FreshPorts/freshports/assets/192271/6218de7a-60fc-468b-bf0a-dd2830fa412a)

</details>

**Comment by dlangille** [comment]
All suggestions done.

Number of commits moved to the next line.

Putting it within the Date line would affect both:

* https://dev.freshports.org/date.php?date=2023/10/29
* https://dev.freshports.org

The same code (`classes/display_commit.php`) is used for all commit displays. The date is part of the output. That change can't be done today.

**Comment by grahamperrin** [comment]
Thanks! 

This part of <https://dev.freshports.org/date.php?date=2023/10/24> looks better, for example:

![image](https://github.com/FreshPorts/freshports/assets/192271/3456769c-b33b-4bc0-9483-fade4d1dc67e)

**Comment by dlangille** [comment]
This also needs review with a dark background. How does it look to you there?

**Comment by dlangille** [comment]
This is a good comparison point:

![Screen Shot 2023-11-01 at 8 49 56 PM](https://github.com/FreshPorts/freshports/assets/1626436/99d5e3e4-801f-43ae-bc02-b9d6bf61fec8)
![Screen Shot 2023-11-01 at 8 49 48 PM](https://github.com/FreshPorts/freshports/assets/1626436/c4d46fd0-198a-4ca2-ab4c-2b00ebec4265)

**Comment by grahamperrin** [comment]
> This also needs review with a dark background. How does it look to you there?

Sorry for not looking sooner. 

I can't remember how to find dark mode.

**Comment by dlangille** [comment]
Dark mode is usually set by the operating system, or your browser.
