### ISSUE TITLE
UPDATING: Only the first x of y ports in this commit are shown above: fewer than y in the view of all ports

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#475]
<details>
<summary>Screenshot</summary>

![image](https://github.com/FreshPorts/freshports/assets/192271/0447b5b5-315c-4941-9ea8-7a66dca4fbc5)

</details>

Currently, at `dev` <https://dev.freshports.org/UPDATING?page=3> (and pictured at the foot of the screenshot above) for <https://cgit.freebsd.org/ports/commit/?id=7636b89500e53864a53949054ad95102e1b87f35> on 2023-06-19: 

> (Only the first 10 of 18 ports in this commit are shown above. [View all ports for this commit](https://dev.freshports.org/commit.php?message_id=7636b89500e53864a53949054ad95102e1b87f35)) 

In the linked page, the view of all ports for the commit: 

> Number of ports [& non-ports] in this commit: 6

That is, fewer than 18. 

![image](https://github.com/FreshPorts/freshports/assets/192271/5d601364-75b0-4235-a23b-67d9f31c4300)

A bug, or have I misunderstood something?

**Comment by grahamperrin** [comment]
First thought (a split-second after posting): flavours? No, I think not. None of the three ports has more than one flavour: 

* <https://dev.freshports.org/textproc/apache-solr/>
* <https://dev.freshports.org/textproc/apache-solr8/>
* <https://dev.freshports.org/textproc/apache-solr9/>

----

Second thought: cacheing. 

----

If I have a third thought, I'll can it.

**Comment by dlangille** [comment]
The code is counting everything returned: 

- three ports
- `MOVED`
- `UPDATING`
- `textproc/Makefile`

I'll see if I can count ports only, or adjust the wordage.

**Comment by dlangille** [comment]
See https://twitter.com/DLangille/status/1717586605752435048

**Comment by dlangille** [comment]
![Screenshot 2023-10-26 at 4 29 20 PM](https://github.com/FreshPorts/freshports/assets/1626436/8577f9a8-60b6-4132-b264-b5a1d97bcbf3)

**Comment by grahamperrin** [comment]
> See [twitter.com/DLangille/status/1717586605752435048](https://twitter.com/DLangille/status/1717586605752435048)

I think this belongs under: 

* https://github.com/FreshPorts/freshports/issues/474
:-)

**Comment by dlangille** [comment]
> > See [twitter.com/DLangille/status/1717586605752435048](https://twitter.com/DLangille/status/1717586605752435048)
> 
> I think this belongs under:
> 
> * [Arrangement of icons, and presentation of texts, for multi-file entries such as those in UPDATING #474](https://github.com/FreshPorts/freshports/issues/474)
> 
> :-)

I agree. Copied over.

**Comment by grahamperrin** [comment]
Hi, is this _truly_ completed?

<https://github.com/FreshPorts/freshports/issues/475#issuecomment-1773770804>

> … I'll see if I can count ports only, or adjust the wordage.

**Comment by dlangille** [comment]
I changed wordage.

**Comment by grahamperrin** [comment]
Sorry, I still can't see a change. 

For the second _19 Jun 2023_ entry that's currently under <https://www.freshports.org/UPDATING>: 

![image](https://github.com/FreshPorts/freshports/assets/192271/7f68ced6-02c9-4f0c-8eaf-825a8a0d9d49)

(If I look again with fresh eyes in a week or so, maybe I'll see it.)

**Comment by dlangille** [comment]
The first post in this issues shows "number of ports [and non-ports]..." - I fixed that.

There is a hidden screen shot which shows the you wanted fixed.

Fixed at https://dev.freshports.org/UPDATING:

![Screen Shot 2023-11-11 at 12 55 32 PM](https://github.com/FreshPorts/freshports/assets/1626436/2bc700bd-92c0-4c63-99b8-eba799b7929a)
