### ISSUE TITLE
Search by author

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#477]
_Author_ would be nice: 

![image](https://github.com/FreshPorts/freshports/assets/192271/1179bcea-44e8-4ed7-95f6-858e903d9dce)

A comparable request: <https://mastodon.bsd.cafe/@grahamperrin/111326964941658032> @freaky

**Comment by dlangille** [comment]
And:

* `author email`
* `author name`
* `commiter`
* `committer email`
* `committer name`

**Comment by dlangille** [comment]
> I've also had a request for [`mailmap`](https://github.com/freebsd/freebsd-src/blob/ca9dbde88122beb079b55fb4580b200f73044da6/.mailmap) support.

Please elaborate upon how that affects FreshPorts?

**Comment by dlangille** [comment]
> And:
> 
> * `author email`
> * `author name`
> * `commiter`
> * `committer email`
> * `committer name`

I have a first draft of those working now on `dev.freshports.org`

**Comment by Freaky** [comment]
> > I've also had a request for [`mailmap`](https://github.com/freebsd/freebsd-src/blob/ca9dbde88122beb079b55fb4580b200f73044da6/.mailmap) support.
> 
> Please elaborate upon how that affects FreshPorts? I ask because I do not understand the implications of your link.

The request was from a ports committer, in relation to searching the ports tree by email address.

**Comment by dlangille** [comment]
> > > I've also had a request for [`mailmap`](https://github.com/freebsd/freebsd-src/blob/ca9dbde88122beb079b55fb4580b200f73044da6/.mailmap) support.
> > 
> > 
> > Please elaborate upon how that affects FreshPorts? I ask because I do not understand the implications of your link.
> 
> The request was from a ports committer, in relation to searching the ports tree by email address.

If I understand correctly, what has been implemented in this ticket covers that.

**Comment by Freaky** [comment]
The point of mailmap is to allow for the [canonicalisation of names and email addresses](https://git-scm.com/docs/gitmailmap).  You wouldn't have implemented that by accident.

**Comment by dlangille** [comment]
Yeah, that's too much for me to comprehend in a drive-by.

**Comment by grahamperrin** [comment]
Thanks! 

<https://www.freshports.org/search.php?stype=author_email&method=exact&query=nhuff%40acm.org&num=100&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head> success.
