### ISSUE TITLE
Details: YYYYYYYY

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#483]
Currently at `dev` <https://dev.freshports.org/>: 

![image](https://github.com/FreshPorts/freshports/assets/192271/4e4ed600-c70f-4063-ab48-ec48c0cc2ea4)

**Comment by grahamperrin** [comment]
No longer apparent. 

(A few minutes ago I found a different issue at `dev` <https://dev.freshports.org/date.php?date=2023/10/24> … this, too, is no longer apparent.)

@dlangille if this was simply a transient issue, please close (and apologies for the noise).

**Comment by dlangille** [comment]
That was me, testing. :) Thank you. Always report this stuff. 👍
