### ISSUE TITLE
At ⋯/date.php?date=⋯ (worked around by reloading): display_commit.php:86: … processing row 0 … This commit_log_id is different at too many … category is setprocessing row 1 …

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#484]
Some time ago at `dev` <https://dev.freshports.org/date.php?date=2023/10/24>, for example: 

```text
/usr/local/www/freshports/classes/display_commit.php:86 Number of rows = 532
processing row 0 986222 e2721374e1e0f856123aa339c13b274519a52083
This commit_log_id is different
at too many
category is setprocessing row 1 986221 7778ae81eda3c44660c44d900e4b0e0963fa40cc
This commit_log_id is different
at too many
category is setprocessing row 2 986219 8241302dda4980341c3162f21aa8ded4e4a3b4d1
This commit_log_id is different
at too many
…
```

Worked around with <kbd>Control</kbd>+<kbd>F5</kbd> (in Firefox). 

Around 12:42 GMT/UTC at <https://dev.freshports.org/date.php?date=2023/11/04&branch=2023Q4: 

<details>
<summary>Screenshot</summary>

![image](https://github.com/FreshPorts/freshports/assets/192271/968574dd-6e2c-48b3-89f8-3e0497ceebcc)

</details>

Worked around with a simple reload. 

----

No issue with a first load of <https://dev.freshports.org/date.php?date=2023/01/01>, which I picked with the assumption that 1st January would have been a date with very few commits. It was OK in Firefox, and in qutebrowser. 

However: 

- stepping forward in time, to 2nd January, ~~there's~~ there was the same effect. 

----

I assume that there was a simple caching issue somewhere, or testing. 

Not reproducible at the time of writing, 13:41.

**Comment by dlangille** [comment]
This was debugging. :)

It appears (mainly) when the page is being composed. Once cached, server side, it does not appear again until the page is cleared from cache and needs to be composed again.
