### ISSUE TITLE
Parse "WWW" out of Makefile?

### ISSUE THREAD

**Issue by rwv37** [FreshPorts/freshports#487]
One of the features of freshports that I used to like a lot was that when you were looking at a port, its home page would be displayed (and linked), having been parsed out of (if I remember correctly) pkg_descr. A while back, there was a big ports-system-wide change to move those out of pkg_descr (or wherever they were) and into Makefile. Unfortunately, this change killed the feature in freshports.

Could this feature please be readded (by parsing the "WWW" line out of Makefile)? Thanks.

**Comment by dlangille** [comment]
Look for the home icon. 

![image](https://github.com/FreshPorts/freshports/assets/1626436/9a77961a-41d0-410f-8efd-7590013d423c)

**Comment by dlangille** [comment]
See also:

- #383
- #385

**Comment by dlangille** [comment]
I was sure I had coded to contribute to display the WWW: link in the old location.

**Comment by dlangille** [comment]
> I was sure I had coded to contribute to display the WWW: link in the old location.

It is displayed, at least on this page: https://www.freshports.org/net/ocserv

However, I see it is part of `pkg-message`, not `pkg-descr`.  That seems to be a brain fart.

![Screenshot 2023-11-09 at 9 08 50 AM](https://github.com/FreshPorts/freshports/assets/1626436/7f615f8d-c9ce-401d-8f95-e8d6974ddff2)

**Comment by dlangille** [comment]
@rwv37 please have a look around the `dev` website. Better? Any suggestions?

I've modified `WWW` on dev.

* it not longer appears under `pkg-message`
* it has moved to the top of the page
* some ports have multiple `WWW` values (example below)

From: `https://dev.freshports.org/net/ocserv`
![Screenshot 2023-11-09 at 9 27 30 AM](https://github.com/FreshPorts/freshports/assets/1626436/f06a6bdf-e8b5-460f-9d0f-365573341e08)

**Comment by dlangille** [comment]
This is now in production.

**Comment by rwv37** [comment]
Great - thank you!
