### ISSUE TITLE
 Search only this category: CVSROOT (at www); accessibility (at dev, stage, and test)

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#491]
`www` <https://www.freshports.org/search.php>: 

![image](https://github.com/FreshPorts/freshports/assets/192271/1264e327-1caf-4673-b5a0-bdab6369f2fc)

`dev` <https://stage.freshports.org/search.php> (logged in), `stage` <https://stage.freshports.org/search.php>, and `test` <https://test.freshports.org/search.php> default to: 

- accessibility.

I see `CVSROOT` mentioned in issue #489.

**Comment by grahamperrin** [comment]
Partial workaround: use the search box at the home page.

**Comment by dlangille** [comment]
This is affecting search results.

**Comment by dlangille** [comment]
Fixed with Committed revision 5928

**Comment by dlangille** [comment]
The search problem should be fixed. The content problem will be handled by #489
