### ISSUE TITLE
manual pages: if a page can be inferred from the pkg-plist, then link to the page

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#492]
I imagined this umpteen times in the past.

### Example

<https://www.freshports.org/security/bcwipe#pkg-plist> includes `man/man1/bcwipe.1.gz`, so:

- **bcwipe(1)**

– referring to <https://man.freebsd.org/cgi/man.cgi?query=bcwipe&sektion=1&manpath=freebsd-ports>

- note, `&manpath=freebsd-ports`

### Thoughts

I don't imagine a perfect result for _every_ port where a manual page can be inferred from the property list, but it's worth a try.

**Comment by dlangille** [comment]
Approach:

* parse `pkg-plist` looking for `/man/man?/*.?.gz`
* add link

Using developer tools, I modified the the HTML of the page in my browser. Is this what you're expecting?

![Screen Shot 2023-11-12 at 9 43 43 AM](https://github.com/FreshPorts/freshports/assets/1626436/f89e9288-27dd-4706-ae66-cf59dbe3ff0c)

**Comment by grahamperrin** [comment]
Thanks! 

Downside of what's pictured: _collapsed_ by default, readers will not intuitively click to expand to reveal a link. 

Downside of notionally _expanding_ the full list by default: overwhelming ([ports-mgmt/pkg](https://www.freshports.org/ports-mgmt/pkg/#pkg-plist) example below). 

<details>
<summary>Screenshot</summary>

![image](https://github.com/FreshPorts/freshports/assets/192271/cf4ac477-9835-4bd5-af15-22833d5ea35c)

</details>

### A quick thought

A very rough mock-up (and not properly thought-through, please kick back): 

![image](https://github.com/FreshPorts/freshports/assets/192271/133d48e4-7f68-4ebe-ad0a-4189219ced0b)

* two radio buttons
* one more prominent than the other.

**Comment by grahamperrin** [comment]
I'd like a **Manual pages** button to present a pop-up window comprising links to the pages.

Pop-ups might be contentious, so alternatively, a new tab comprising the same content. 

Either way: suitably titled (e.g. _pkg manpages_) and each link on a simple new line (not bulleted).

**Comment by dlangille** [comment]
I much prefer putting the list of man page links at the top of the page

1. it is straight forward to implement - grep for the regex, make hyperlinks
2. it leaves `pkg-plist` untouched

**Comment by dlangille** [comment]
For matching: https://regex101.com/r/uhEsGb/1

**Comment by dlangille** [comment]
See
* https://dev.freshports.org/security/bcwipe/
* https://dev.freshports.org/sysutils/bacula13-server/

**Comment by dlangille** [comment]
I see `Manual pages` appears three times per port. I'll track that one down.

**Comment by dlangille** [comment]
We're going to need to collapse the list: https://dev.freshports.org/print/fpc-libcups/ has

![Screen Shot 2023-11-12 at 7 28 52 PM](https://github.com/FreshPorts/freshports/assets/1626436/23809205-882f-480c-af7d-fe84065feaa7)

**Comment by dlangille** [comment]
Added.
![Screen Shot 2023-11-12 at 8 28 57 PM](https://github.com/FreshPorts/freshports/assets/1626436/33a188b7-7c8e-4c9c-82fb-7bffdc91768c)

**Comment by dlangille** [comment]
This is now on `www` and the cache has not been cleared. `pkgs` will appear as new commits occur.

I'll clear the cache after I've modified how non-port commits are displayed.
