### ISSUE TITLE
Manual pages: section number in parentheses

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#497]
Currently at <https://www.freshports.org/net/openbgpd8/#man>: 

![image](https://github.com/FreshPorts/freshports/assets/192271/3f0035c4-7efb-4da9-a72f-042ba0c651c8)

Ice the cake :-)

From <https://github.com/FreshPorts/freshports/issues/492#issue-1989239565>, the suggested example (for a different port), with parentheses:

> bcwipe(1)

### Rationale

There might be a port where two different pages share the same name.

More generally: 

- visibility of section numbers helps to reinforce the value and meaning of sectioning – this is subtle but, I think, nonetheless important (for newcomers and other people who are not manpage experts)
- there's more, but it's not easy for me to put into words. 

### Suggested priority

Low.

----

Thanks

**Comment by dlangille** [comment]
Look at https://github.com/FreshPorts/freshports/blob/main/classes/port-display.php#L1809 for how easy this will be.

Look at that comment. :)

**Comment by dlangille** [comment]
Done on dev.
