### ISSUE TITLE
expand/collapse lists in list view not fully functional

### ISSUE THREAD

**Issue by sambler** [FreshPorts/freshports#503]
In the port details you have lists such as man pages, plist, dependencies etc that can be expanded and collapsed.

In the list view page showing search results, the man pages are listed and initially expanded and the expand collapse doesn't work right. Only the first port in the list responds to the expand/collapse.

An example is to search for allegro, of the three ports found, two have ~1000 man pages listed. Collapsing the list on the first works, then using the expand/collapse in the second port works on the first port list not the second.

I would think the man pages shown in the search results is not really useful and could be removed and only shown in port details.

**Comment by dlangille** [comment]
I agree: the man page information should not be in the search results. I never intended that.

**Comment by dlangille** [comment]
@sambler How is `dev.freshports.org` for this?

**Comment by sambler** [comment]
I only see server busy.

If you removed the manpage list from the search results page, then thats good.

**Comment by dlangille** [comment]
`server busy` appears only if the server load is higher than expected and the user is not logged in. It never appears for logged in users. This acts to slow down the bots.
