### ISSUE TITLE
Increase visual emphasis for the port name

### ISSUE THREAD

**Issue by damilgra** [FreshPorts/freshports#506]
Since the recent layout change, it's hard to scan for port changes of interest as the port is no longer emphasized visually as it was before. The same is true for the port version.

Having the port title and version shown in a more prominent fashion would be greatly enhance the usability of the site, in my opinion, for the purposes of quickly identifying ports of interest that have changed.

**Comment by dlangille** [comment]
I'll add before and after images to this ticket so we're all referencing the same thing.

**Comment by dlangille** [comment]
@damilgra please choose a commit/port date/time as a starting point. I'll find the old version to compare.

**Comment by damilgra** [comment]
Just arbitrarily choosing commit e564ba7fe0a3411cfd31a65e5c9853a2f67c723b
But it's possible I'm unclear as to what you're looking for.

**Comment by dlangille** [comment]
On the home page:

| before               | after               |
| ---------------------- | ---------------------- |
| ![home-page old](https://github.com/FreshPorts/freshports/assets/1626436/f074f834-7eab-44bd-858e-6759003cf4d3) | ![home-page](https://github.com/FreshPorts/freshports/assets/1626436/792c8406-b583-4c30-9fad-78315a8a7208)|

**Comment by dlangille** [comment]
### commit.php?message_id=e564ba7fe0a3411cfd31a65e5c9853a2f67c723b

## New:
![commit php](https://github.com/FreshPorts/freshports/assets/1626436/3df6bc66-0ee4-42db-93f2-fbc464e728fb)

## Old:

![commit php old](https://github.com/FreshPorts/freshports/assets/1626436/50f43254-1b79-4960-ae72-5071329b0ec6)

**Comment by dlangille** [comment]
In this comment, I'll show screen shots from `dev`, where it has:

* port name is bold/larger

![home-page-dev](https://github.com/FreshPorts/freshports/assets/1626436/8eebeaf1-9a77-49f3-9d29-096cdea1a882)

**Comment by damilgra** [comment]
I think _both_ layout and formatting are contributing factors. I want to state my bias explicitly - in the past I would tend to view the home page quickly, scanning for either new ports that might be of interest, or new versions of ports I'm using. 

The bold version of the port helps in the dev screen shot, but I do still prefer having the port name emphasized more and visually separated (devel is of much less interest than rubygem-aws-sdk-supportapp). Additionally, the icons overwhelm the layout given their increased size and more prominent location. I wonder if they could be floated to the right.

**Comment by dlangille** [comment]
The main reason for moving the icons to the left was alignment.

If they are moved back to the right, I think a table is required to do that alignment. I'm not sure of a way to accomplish alignment otherwise.

This before/after shows the goal:

# New

![Screen Shot 2023-12-02 at 10 14 54 AM](https://github.com/FreshPorts/freshports/assets/1626436/7dd971b4-8d23-4a12-ae9f-5cf860f0bd9b)

# Old

![Screen Shot 2023-12-02 at 10 14 27 AM](https://github.com/FreshPorts/freshports/assets/1626436/9ae64b23-1b58-4ae2-8808-3b0952aab1d0)

**Comment by damilgra** [comment]
Ideally CSS with flexbox or grid instead of a table, and I'd offer to help but my lack of PHP zen would make this hard...

I think what stands out in the two screenshots is the sheer number of extra icon links in the new version.

**Comment by dlangille** [comment]
I can do it with a table. If you can do it with HTML CSS flexbox grid, I can translate code it.

The extra icons are links to various repos.  Shall we remove them? Adding the extra icons was also part of the redesign. The alignment followed on from that.

**Comment by damilgra** [comment]
Links to the repos are all visible when you go to the individual port page, right? If so, the trade-off is having a less cluttered dashboard vs. having to click an extra link to get to that next link. I think the previous UX was better and trying to click on the right icon when there are so many, so close, suggests removing them is probably the best option.

**Comment by damilgra** [comment]
In terms of reducing icons displayed by default, a compromise option is to hide/show the Details section in response to a button press,  keeping it hidden by default.

A simple implementation would involve:

1.  Globally including the javascript function below
2. Wrapping the details section in a div element assign with a class named "details"
3. Including the button at the bottom


`<head>
<base href="https://www.freshports.org/" target="_blank">
<script>
    function toggleVisibility(e) {
        var buttonText = e.innerHTML;
        var moreText = e.previousElementSibling;

        var btn = e; 
        if (buttonText == "Hide Details") {
            btn.innerHTML = "View Details";
            moreText.style.display = "none";
        } else {
            btn.innerHTML = "Hide Details";
            moreText.style.display = "block";
        }
    }
</script>
<style>
    .meta { font-size: 1em; }
    blockquote { border-left: 6px solid #efefef; padding-left: 20px; position: relative; left: -20px;}
    .commit-details {
        border: 2px solid #ccc;
        margin: 10px;
    }
    button { margin: 16px 0; display: block; padding: 6px;}

</style>
</head>
<body>
<td class="commit-details">
<span class="meta">13:19 <a href="mailto:tcberner@FreeBSD.org" title="authored by this person">Tobias C. Berner</a>&nbsp;(tcberner)&nbsp;<a href="/search.php?stype=committer&amp;method=exact&amp;query=tcberner"><img class="icon" src="/images/search.jpg" alt="search for other commits by this committer" title="search for other commits by this committer" width="17" height="17"></a></span>
<blockquote class="description"><pre class="description">KDE: Add KDE Frameworks 6 ports

KDE's 6th Megarelease - Alpha

Wednesday, 8 November 2023

En route to the new Plasma, Frameworks and Gear

Every few years we port the key components of our software to a new
version of Qt, taking the opportunity to remove cruft and leverage the
updated features the most recent version of Qt has to offer us.

It has been nearly 10 years since the last big release of our flagship
Plasma desktop environment, and the time has come again. KDE is making
available today the Alpha version of all the software we will include in
a megarelease scheduled for the end of February 2024.

Announcement: <a href="https://kde.org/announcements/megarelease/6/alpha/">https://kde.org/announcements/megarelease/6/alpha/</a>
Obtained from:	<a href="https://github.com/tcberner/kde6-overlay/">https://github.com/tcberner/kde6-overlay/</a>

Further ports specific changes:
 * multimedia/phonon: is now flavored for Qt5 and Qt6</pre>
</blockquote>

<span class="element-details"><a href="https://cgit.freebsd.org/ports/commit/?id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/git.png" alt="commit hash: 633534bf76831ac5b3e0d6afa47923d621a4f8f5" title="commit hash: 633534bf76831ac5b3e0d6afa47923d621a4f8f5" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commit/633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/codeberg.svg" alt="commit hash: 633534bf76831ac5b3e0d6afa47923d621a4f8f5" title="commit hash: 633534bf76831ac5b3e0d6afa47923d621a4f8f5" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commit/633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/github.svg" alt="commit hash: 633534bf76831ac5b3e0d6afa47923d621a4f8f5" title="commit hash: 633534bf76831ac5b3e0d6afa47923d621a4f8f5" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/commit/633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/gitlab.svg" alt="commit hash: 633534bf76831ac5b3e0d6afa47923d621a4f8f5" title="commit hash: 633534bf76831ac5b3e0d6afa47923d621a4f8f5" width="22" height="22"></a>&nbsp;<a href="https://cgit.freebsd.org/ports/commit/?id=633534bf76831ac5b3e0d6afa47923d621a4f8f5" class="hash">633534b</a></span>

<div class="details" style="display:none;">

<p>Details:</p><ul class="element-list">
<li><span class="element-details"><a href="https://cgit.freebsd.org/ports/log/archivers/kf6-karchive"><img class="icon" src="/images/git.png" alt="commit log for: archivers/kf6-karchive" title="commit log for: archivers/kf6-karchive" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commits/branch/main/archivers/kf6-karchive"><img class="icon" src="/images/codeberg.svg" alt="commit log for: archivers/kf6-karchive" title="commit log for: archivers/kf6-karchive" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commits/main/archivers/kf6-karchive"><img class="icon" src="/images/github.svg" alt="commit log for: archivers/kf6-karchive" title="commit log for: archivers/kf6-karchive" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/-/commits/main/archivers/kf6-karchive"><img class="icon" src="/images/gitlab.svg" alt="commit log for: archivers/kf6-karchive" title="commit log for: archivers/kf6-karchive" width="22" height="22"></a>&nbsp;<a href="/archivers/kf6-karchive/">archivers/kf6-karchive</a></span>
<img class="icon" src="/images/new.gif" alt="new!" title="new!" width="28" height="11">
<a href="/commit.php?category=archivers&amp;port=kf6-karchive&amp;files=yes&amp;message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/logs.gif" alt="files touched by this commit" title="files touched by this commit" width="17" height="20"></a>&nbsp;<a href="https://portsfallout.com/fallout?port=archivers%2Fkf6-karchive%24" rel="noopener noreferrer"><img class="icon fallout" src="/images/fallout.svg" alt="pkg-fallout" title="pkg-fallout" width="16" height="16"></a>&nbsp;</li>
<li><span class="element-details"><a href="https://cgit.freebsd.org/ports/log/deskutils/kf6-kstatusnotifieritem"><img class="icon" src="/images/git.png" alt="commit log for: deskutils/kf6-kstatusnotifieritem" title="commit log for: deskutils/kf6-kstatusnotifieritem" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commits/branch/main/deskutils/kf6-kstatusnotifieritem"><img class="icon" src="/images/codeberg.svg" alt="commit log for: deskutils/kf6-kstatusnotifieritem" title="commit log for: deskutils/kf6-kstatusnotifieritem" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commits/main/deskutils/kf6-kstatusnotifieritem"><img class="icon" src="/images/github.svg" alt="commit log for: deskutils/kf6-kstatusnotifieritem" title="commit log for: deskutils/kf6-kstatusnotifieritem" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/-/commits/main/deskutils/kf6-kstatusnotifieritem"><img class="icon" src="/images/gitlab.svg" alt="commit log for: deskutils/kf6-kstatusnotifieritem" title="commit log for: deskutils/kf6-kstatusnotifieritem" width="22" height="22"></a>&nbsp;<a href="/deskutils/kf6-kstatusnotifieritem/">deskutils/kf6-kstatusnotifieritem</a></span>
<img class="icon" src="/images/new.gif" alt="new!" title="new!" width="28" height="11">
<a href="/commit.php?category=deskutils&amp;port=kf6-kstatusnotifieritem&amp;files=yes&amp;message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/logs.gif" alt="files touched by this commit" title="files touched by this commit" width="17" height="20"></a>&nbsp;<a href="https://portsfallout.com/fallout?port=deskutils%2Fkf6-kstatusnotifieritem%24" rel="noopener noreferrer"><img class="icon fallout" src="/images/fallout.svg" alt="pkg-fallout" title="pkg-fallout" width="16" height="16"></a>&nbsp;</li>
<li><span class="element-details"><a href="https://cgit.freebsd.org/ports/log/devel/kf6-extra-cmake-modules"><img class="icon" src="/images/git.png" alt="commit log for: devel/kf6-extra-cmake-modules" title="commit log for: devel/kf6-extra-cmake-modules" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commits/branch/main/devel/kf6-extra-cmake-modules"><img class="icon" src="/images/codeberg.svg" alt="commit log for: devel/kf6-extra-cmake-modules" title="commit log for: devel/kf6-extra-cmake-modules" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commits/main/devel/kf6-extra-cmake-modules"><img class="icon" src="/images/github.svg" alt="commit log for: devel/kf6-extra-cmake-modules" title="commit log for: devel/kf6-extra-cmake-modules" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/-/commits/main/devel/kf6-extra-cmake-modules"><img class="icon" src="/images/gitlab.svg" alt="commit log for: devel/kf6-extra-cmake-modules" title="commit log for: devel/kf6-extra-cmake-modules" width="22" height="22"></a>&nbsp;<a href="/devel/kf6-extra-cmake-modules/">devel/kf6-extra-cmake-modules</a></span>
<img class="icon" src="/images/new.gif" alt="new!" title="new!" width="28" height="11">
<a href="/commit.php?category=devel&amp;port=kf6-extra-cmake-modules&amp;files=yes&amp;message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/logs.gif" alt="files touched by this commit" title="files touched by this commit" width="17" height="20"></a>&nbsp;<a href="https://portsfallout.com/fallout?port=devel%2Fkf6-extra-cmake-modules%24" rel="noopener noreferrer"><img class="icon fallout" src="/images/fallout.svg" alt="pkg-fallout" title="pkg-fallout" width="16" height="16"></a>&nbsp;</li>
<li><span class="element-details"><a href="https://cgit.freebsd.org/ports/log/devel/kf6-kapidox"><img class="icon" src="/images/git.png" alt="commit log for: devel/kf6-kapidox" title="commit log for: devel/kf6-kapidox" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commits/branch/main/devel/kf6-kapidox"><img class="icon" src="/images/codeberg.svg" alt="commit log for: devel/kf6-kapidox" title="commit log for: devel/kf6-kapidox" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commits/main/devel/kf6-kapidox"><img class="icon" src="/images/github.svg" alt="commit log for: devel/kf6-kapidox" title="commit log for: devel/kf6-kapidox" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/-/commits/main/devel/kf6-kapidox"><img class="icon" src="/images/gitlab.svg" alt="commit log for: devel/kf6-kapidox" title="commit log for: devel/kf6-kapidox" width="22" height="22"></a>&nbsp;<a href="/devel/kf6-kapidox/">devel/kf6-kapidox</a></span>
<img class="icon" src="/images/new.gif" alt="new!" title="new!" width="28" height="11">
<a href="/commit.php?category=devel&amp;port=kf6-kapidox&amp;files=yes&amp;message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/logs.gif" alt="files touched by this commit" title="files touched by this commit" width="17" height="20"></a>&nbsp;<a href="https://portsfallout.com/fallout?port=devel%2Fkf6-kapidox%24" rel="noopener noreferrer"><img class="icon fallout" src="/images/fallout.svg" alt="pkg-fallout" title="pkg-fallout" width="16" height="16"></a>&nbsp;</li>
<li><span class="element-details"><a href="https://cgit.freebsd.org/ports/log/devel/kf6-kauth"><img class="icon" src="/images/git.png" alt="commit log for: devel/kf6-kauth" title="commit log for: devel/kf6-kauth" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commits/branch/main/devel/kf6-kauth"><img class="icon" src="/images/codeberg.svg" alt="commit log for: devel/kf6-kauth" title="commit log for: devel/kf6-kauth" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commits/main/devel/kf6-kauth"><img class="icon" src="/images/github.svg" alt="commit log for: devel/kf6-kauth" title="commit log for: devel/kf6-kauth" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/-/commits/main/devel/kf6-kauth"><img class="icon" src="/images/gitlab.svg" alt="commit log for: devel/kf6-kauth" title="commit log for: devel/kf6-kauth" width="22" height="22"></a>&nbsp;<a href="/devel/kf6-kauth/">devel/kf6-kauth</a></span>
<img class="icon" src="/images/new.gif" alt="new!" title="new!" width="28" height="11">
<a href="/commit.php?category=devel&amp;port=kf6-kauth&amp;files=yes&amp;message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/logs.gif" alt="files touched by this commit" title="files touched by this commit" width="17" height="20"></a>&nbsp;<a href="https://portsfallout.com/fallout?port=devel%2Fkf6-kauth%24" rel="noopener noreferrer"><img class="icon fallout" src="/images/fallout.svg" alt="pkg-fallout" title="pkg-fallout" width="16" height="16"></a>&nbsp;</li>
<li><span class="element-details"><a href="https://cgit.freebsd.org/ports/log/devel/kf6-kbookmarks"><img class="icon" src="/images/git.png" alt="commit log for: devel/kf6-kbookmarks" title="commit log for: devel/kf6-kbookmarks" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commits/branch/main/devel/kf6-kbookmarks"><img class="icon" src="/images/codeberg.svg" alt="commit log for: devel/kf6-kbookmarks" title="commit log for: devel/kf6-kbookmarks" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commits/main/devel/kf6-kbookmarks"><img class="icon" src="/images/github.svg" alt="commit log for: devel/kf6-kbookmarks" title="commit log for: devel/kf6-kbookmarks" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/-/commits/main/devel/kf6-kbookmarks"><img class="icon" src="/images/gitlab.svg" alt="commit log for: devel/kf6-kbookmarks" title="commit log for: devel/kf6-kbookmarks" width="22" height="22"></a>&nbsp;<a href="/devel/kf6-kbookmarks/">devel/kf6-kbookmarks</a></span>
<img class="icon" src="/images/new.gif" alt="new!" title="new!" width="28" height="11">
<a href="/commit.php?category=devel&amp;port=kf6-kbookmarks&amp;files=yes&amp;message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/logs.gif" alt="files touched by this commit" title="files touched by this commit" width="17" height="20"></a>&nbsp;<a href="https://portsfallout.com/fallout?port=devel%2Fkf6-kbookmarks%24" rel="noopener noreferrer"><img class="icon fallout" src="/images/fallout.svg" alt="pkg-fallout" title="pkg-fallout" width="16" height="16"></a>&nbsp;</li>
<li><span class="element-details"><a href="https://cgit.freebsd.org/ports/log/devel/kf6-kcmutils"><img class="icon" src="/images/git.png" alt="commit log for: devel/kf6-kcmutils" title="commit log for: devel/kf6-kcmutils" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commits/branch/main/devel/kf6-kcmutils"><img class="icon" src="/images/codeberg.svg" alt="commit log for: devel/kf6-kcmutils" title="commit log for: devel/kf6-kcmutils" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commits/main/devel/kf6-kcmutils"><img class="icon" src="/images/github.svg" alt="commit log for: devel/kf6-kcmutils" title="commit log for: devel/kf6-kcmutils" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/-/commits/main/devel/kf6-kcmutils"><img class="icon" src="/images/gitlab.svg" alt="commit log for: devel/kf6-kcmutils" title="commit log for: devel/kf6-kcmutils" width="22" height="22"></a>&nbsp;<a href="/devel/kf6-kcmutils/">devel/kf6-kcmutils</a></span>
<img class="icon" src="/images/new.gif" alt="new!" title="new!" width="28" height="11">
<a href="/commit.php?category=devel&amp;port=kf6-kcmutils&amp;files=yes&amp;message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/logs.gif" alt="files touched by this commit" title="files touched by this commit" width="17" height="20"></a>&nbsp;<a href="https://portsfallout.com/fallout?port=devel%2Fkf6-kcmutils%24" rel="noopener noreferrer"><img class="icon fallout" src="/images/fallout.svg" alt="pkg-fallout" title="pkg-fallout" width="16" height="16"></a>&nbsp;</li>
<li><span class="element-details"><a href="https://cgit.freebsd.org/ports/log/devel/kf6-kconfig"><img class="icon" src="/images/git.png" alt="commit log for: devel/kf6-kconfig" title="commit log for: devel/kf6-kconfig" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commits/branch/main/devel/kf6-kconfig"><img class="icon" src="/images/codeberg.svg" alt="commit log for: devel/kf6-kconfig" title="commit log for: devel/kf6-kconfig" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commits/main/devel/kf6-kconfig"><img class="icon" src="/images/github.svg" alt="commit log for: devel/kf6-kconfig" title="commit log for: devel/kf6-kconfig" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/-/commits/main/devel/kf6-kconfig"><img class="icon" src="/images/gitlab.svg" alt="commit log for: devel/kf6-kconfig" title="commit log for: devel/kf6-kconfig" width="22" height="22"></a>&nbsp;<a href="/devel/kf6-kconfig/">devel/kf6-kconfig</a></span>
<img class="icon" src="/images/new.gif" alt="new!" title="new!" width="28" height="11">
<a href="/commit.php?category=devel&amp;port=kf6-kconfig&amp;files=yes&amp;message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/logs.gif" alt="files touched by this commit" title="files touched by this commit" width="17" height="20"></a>&nbsp;<a href="https://portsfallout.com/fallout?port=devel%2Fkf6-kconfig%24" rel="noopener noreferrer"><img class="icon fallout" src="/images/fallout.svg" alt="pkg-fallout" title="pkg-fallout" width="16" height="16"></a>&nbsp;</li>
<li><span class="element-details"><a href="https://cgit.freebsd.org/ports/log/devel/kf6-kcoreaddons"><img class="icon" src="/images/git.png" alt="commit log for: devel/kf6-kcoreaddons" title="commit log for: devel/kf6-kcoreaddons" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commits/branch/main/devel/kf6-kcoreaddons"><img class="icon" src="/images/codeberg.svg" alt="commit log for: devel/kf6-kcoreaddons" title="commit log for: devel/kf6-kcoreaddons" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commits/main/devel/kf6-kcoreaddons"><img class="icon" src="/images/github.svg" alt="commit log for: devel/kf6-kcoreaddons" title="commit log for: devel/kf6-kcoreaddons" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/-/commits/main/devel/kf6-kcoreaddons"><img class="icon" src="/images/gitlab.svg" alt="commit log for: devel/kf6-kcoreaddons" title="commit log for: devel/kf6-kcoreaddons" width="22" height="22"></a>&nbsp;<a href="/devel/kf6-kcoreaddons/">devel/kf6-kcoreaddons</a></span>
<img class="icon" src="/images/new.gif" alt="new!" title="new!" width="28" height="11">
<a href="/commit.php?category=devel&amp;port=kf6-kcoreaddons&amp;files=yes&amp;message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/logs.gif" alt="files touched by this commit" title="files touched by this commit" width="17" height="20"></a>&nbsp;<a href="https://portsfallout.com/fallout?port=devel%2Fkf6-kcoreaddons%24" rel="noopener noreferrer"><img class="icon fallout" src="/images/fallout.svg" alt="pkg-fallout" title="pkg-fallout" width="16" height="16"></a>&nbsp;</li>
<li><span class="element-details"><a href="https://cgit.freebsd.org/ports/log/devel/kf6-kcrash"><img class="icon" src="/images/git.png" alt="commit log for: devel/kf6-kcrash" title="commit log for: devel/kf6-kcrash" width="22" height="22"></a>&nbsp;<a href="https://codeberg.org/FreeBSD/freebsd-ports/commits/branch/main/devel/kf6-kcrash"><img class="icon" src="/images/codeberg.svg" alt="commit log for: devel/kf6-kcrash" title="commit log for: devel/kf6-kcrash" width="22" height="22"></a>&nbsp;<a href="https://github.com/FreeBSD/freebsd-ports/commits/main/devel/kf6-kcrash"><img class="icon" src="/images/github.svg" alt="commit log for: devel/kf6-kcrash" title="commit log for: devel/kf6-kcrash" width="22" height="22"></a>&nbsp;<a href="https://gitlab.com/FreeBSD/freebsd-ports/-/commits/main/devel/kf6-kcrash"><img class="icon" src="/images/gitlab.svg" alt="commit log for: devel/kf6-kcrash" title="commit log for: devel/kf6-kcrash" width="22" height="22"></a>&nbsp;<a href="/devel/kf6-kcrash/">devel/kf6-kcrash</a></span>
<img class="icon" src="/images/new.gif" alt="new!" title="new!" width="28" height="11">
<a href="/commit.php?category=devel&amp;port=kf6-kcrash&amp;files=yes&amp;message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/logs.gif" alt="files touched by this commit" title="files touched by this commit" width="17" height="20"></a>&nbsp;<a href="https://portsfallout.com/fallout?port=devel%2Fkf6-kcrash%24" rel="noopener noreferrer"><img class="icon fallout" src="/images/fallout.svg" alt="pkg-fallout" title="pkg-fallout" width="16" height="16"></a>&nbsp;</li>
</ul>(Only the first 10 of 86 items in this commit are shown above. <a href="/commit.php?message_id=633534bf76831ac5b3e0d6afa47923d621a4f8f5"><img class="icon" src="/images/play.gif" alt="View all ports for this commit" title="View all ports for this commit" width="13" height="13"></a>)
</div>

<button onclick="toggleVisibility(this)">View Details</button>
</td>
</body>`

**Comment by dlangille** [comment]
> Links to the repos are all visible when you go to the individual port page, right? If so, the trade-off is having a less cluttered dashboard vs. having to click an extra link to get to that next link. I think the previous UX was better and trying to click on the right icon when there are so many, so close, suggests removing them is probably the best option.

I like the idea of reducing the icons on the front page. Just the name of the port (no category). Hovering over the port will display `category/ports - COMMENT value from Makefile (i.e. short description)`

**Comment by dlangille** [comment]
I've started down this track at https://dev.freshports.org - I'm working on it intermittently as I do other things.

**Comment by dlangille** [comment]
The hover text is there, yet incomplete. How's this so far?

**Comment by nsoci** [comment]
IMO the old web page of freshport was visualy much more friendly as is now and after those changes I am very rare on the site.  Sorry.

**Comment by dlangille** [comment]
> IMO the old web page of freshport was visualy much more friendly as is now and after those changes I am very rare on the site. Sorry.

Have you read through the changes proposed above?

Have you looked at https://dev.freshports.org/ - comments are requested.

**Comment by nsoci** [comment]
I did and I like [https://dev.freshports.org](url)but the other no.

**Comment by dlangille** [comment]
@damilgra  as the OP, how do you feel?

@grahamperrin you also have skin in this game.

**Comment by damilgra** [comment]
Ultimately I prefer the prefer how things were before the redesign because the following info is what I'm looking for when I scan the dashboard:

- Package name (minus category)
- Version,
- New tag if applicable or broken status, if applicable

I think a lot of the secondary info would be better served if it was just on the individual port page.

That said, I didn't follow what issues the redesign were trying to solve, so it's entirely possible I'm missing something; if that's the case I think the version in dev is an improvement over the current re-design.

**Comment by dlangille** [comment]
Unless further insights arrived, the changes on `dev` will be committed and promoted to production 'soon'.

**Comment by dlangille** [comment]
Sundays are good days for pushing new releases.

**Comment by dlangille** [comment]
NOTE: these change primarily affect:

* /
* /date.php
* /search.php

**Comment by dlangille** [comment]
See:

* New UI updates. See https://news.freshports.org/2023/12/17/recent-ui-changes/
* https://github.com/FreshPorts/freshports/releases/tag/2.8.7

**Comment by dlangille** [comment]
@damilgra How is production now?

* https://www.freshports.org/
* https://www.freshports.org/date.php

**Comment by damilgra** [comment]
Much cleaner, IMO. Thanks very much!

**Comment by dlangille** [comment]
@damilgra FYI, I am not opposed to moving the port names back to above the commit message and/or listing the port short description beside the port name.

**Comment by damilgra** [comment]
I would be in favour of both - having the port names in a more prominent position would make scanning easier and a short description is useful when learning about new ports (saves a click)

**Comment by dlangille** [comment]
@

> I would be in favour of both - having the port names in a more prominent position would make scanning easier and a short description is useful when learning about new ports (saves a click)

Please review:
* #526

**Comment by grahamperrin** [comment]
Sorry for not responding sooner, 

> * /
> 
> * /date.php
> 
> * /search.php

`/` and `/date.php` look much better in `stage` than in `www`. Thanks! 

----

Nit: at a glance, the grey horizontal bars (three pictured below) seem superfluous. 

![image](https://github.com/FreshPorts/freshports/assets/192271/f2d3cc66-75b1-4e1c-b02d-d0dcbe9f0c67)

**Comment by dlangille** [comment]
The grey bars may be horizontal scroll bars. They do not appear for me. I suspect CSS.
