### ISSUE TITLE
FreeBSD: cacti vs ntop: rrdtool dependency conflict

### ISSUE THREAD

**Issue by Z-Vladus** [FreshPorts/freshports#51]
Hello!
I've recently installed cacti-1.1.24 and it depends on rrdtool-1.7.0
While trying to install ntop 5.0.1_13 I've got an error, 

```
_ntop 5.0.1_13 depends on package: rrdtool 12>=1.2 not found
rrdtool12-1.2.30_7 conflicts with installed package(s):
rrdtool-1.7.0_
```
So now, I have to choose what to run - cacti+rrdtool-1.7 or ntop+rrdtool-1.2

I wonder if there's a way to build and use ntop with fresh rrdtool. 

Any help will be appreciated.

**Comment by dlangille** [comment]
Sorry, this is the wrong place.

This repository does not deal with ports, only the website itself.  I suggest: https://forums.freebsd.org/forums/5/
