### ISSUE TITLE
Compile a list of FAQ about packages

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#515]
This issue aims to compose an FAQ about Package versions and is related to #513 #514 and #511

First, start with `-` : What does that mean? It means no package was found for that ABI.

For example, this is `net/py-maxminddb:

![Screenshot 2023-12-14 at 10 28 08 AM](https://github.com/FreshPorts/freshports/assets/1626436/f98fb706-f645-49dc-95c3-4129e0be2537)

Here, we can see:

* the repo which FreshPorts found is dated `2012-12-10`.
* that repo was processed by FreshPorts on `2013-12-12`
* that repo was last checked (for a newer build date) on `2023-12-14`

The `repo date` is not specific to the package or to the port and can predate package/port creation.

From the same port, we also have:

![Screenshot 2023-12-14 at 10 31 11 AM](https://github.com/FreshPorts/freshports/assets/1626436/84f895ff-1ef3-4e52-8a72-c749432089bd)

This should be read as:

* FreshPorts has not found a repo for this ABI value - it may have been present in the past, but it was not found the last time it looked
* As such, the repo has never been imported
* FreshPorts last checked on 12023-12-14`

If you see an entry which says `never imported` but has a date for `repo build date` it indicates a problem. Please report that to us please.

**Comment by markmi** [comment]
FYI: various typos in dates that should have 2023 for the year:
. . .
> Here, we can see:
> 
> * the repo which FreshPorts found is dated `2012-12-10`.
> * that repo was processed by FreshPorts on `2013-12-12`
> * that repo was last checked (for a newer build date) on `2023-12-14`
> 
> From the same port, we also have:
> 
. . .
> * As such, the repo has never been imported
> * FreshPorts last checked on 12023-12-14`

**Comment by markmi** [comment]
Is something needed for having a repo build date but also "never imported"?

**Comment by dlangille** [comment]
Yes.  I've added something to the FAQ for that. With recent fixes, that should cease to happen now.

**Comment by dlangille** [comment]
now packaged.

Installed on test, dev, and stage.
