### ISSUE TITLE
php-composer runtime dependencies: mbstring

### ISSUE THREAD

**Issue by eqvvs** [FreshPorts/freshports#52]
Hey

I've installed the php-composer but it dosn't work. It throws an error that "mbstring" is missing. After installing the right mbstring it was fixed.

Maybe it can be helpfull to install it together with php-composer. Otherwise it can be usefull to give an post install notice like "Make sure that phpXX-mbstring is installed, if not install phpXX-mbstring. XX is the version of php you have installed."

Kind Regards

**Comment by dlangille** [comment]
This repo does not deal with FreeBSD ports, only the FreshPorts website, which reports upon the FreeBSD ports.

I suspect you should contact the [FreeBSD ports mailing list](https://lists.freebsd.org/mailman/listinfo/freebsd-ports) instead.

Best wishes.
