### ISSUE TITLE
dev: unexpected identifier "_short", expecting ")" in port-display.php on line 454

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#525]
`dev` <https://dev.freshports.org/x11/plasma6-plasma/>

> Parse error: syntax error, unexpected identifier "_short", expecting ")" in /usr/local/www/freshports/classes/port-display.php on line 454

----

`www` <https://www.freshports.org/x11/plasma6-plasma/> is OK.

**Comment by dlangille** [comment]
Fixed. Thanks.
