### ISSUE TITLE
x11/wlr-which-key/#packages misrepresented as new, and without its table of packages

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#546]
Maybe already fixed: 

- `dev` <https://dev.freshports.org/x11/wlr-which-key/#packages> does have a table
- `www` <https://www.freshports.org/x11/wlr-which-key/#packages> does not

> No package information for this port in our database
> 
> Sometimes this happens. Not all ports have packages. This is doubly so for new ports, like this one.

It's not a new port (there's no <https://www.freshports.org/images/new.gif> NEW! icon near the head of the page).

**Comment by dlangille** [comment]
This seems to have resolved itself. :)
