### ISSUE TITLE
Categories: Deprecated: Creation of dynamic property Categories::$dbh is deprecated in /usr/local/www/freshports/classes/category-listing.php on line 16

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#548]
At `www` <https://www.freshports.org/categories.php>: 

![image](https://github.com/FreshPorts/freshports/assets/192271/88773e15-2d36-49bb-96cb-822a2c835235)

Not at `dev` <https://dev.freshports.org/categories.php>.

**Comment by dlangille** [comment]
I saw it on dev:

<img width="923" alt="Screenshot 2024-03-03 at 9 12 41 AM" src="https://github.com/FreshPorts/freshports/assets/1626436/c8185d28-6ad7-49b6-8792-f80d3c6dfc15">

**Comment by dlangille** [comment]
Now in production.
