### ISSUE TITLE
Rotate the table for packages

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#551]
For example, at https://dev.freshports.org/graphics/xv, display this instead:

<img width="1212" alt="Screenshot 2024-03-10 at 11 18 39 AM" src="https://github.com/FreshPorts/freshports/assets/1626436/9013f687-f053-4277-af38-ac4324cca659">

**Comment by dlangille** [comment]
We may hit problems if not all ABI use the same set of archs.

**Comment by dlangille** [comment]
First draft:

![Screenshot 2024-03-10 at 3 02 01 PM](https://github.com/FreshPorts/freshports/assets/1626436/d9313928-3971-478d-ad55-5bd0893f65df)

**Comment by dlangille** [comment]
compare existing for https://www.freshports.org/devel/vc-intrinsics/

<img width="1367" alt="Screenshot 2024-03-10 at 3 23 33 PM" src="https://github.com/FreshPorts/freshports/assets/1626436/83c588e8-75e7-48c2-91f3-39159b224727">

**Comment by dlangille** [comment]
With the proposed update:

<img width="1502" alt="Screenshot 2024-03-10 at 3 41 05 PM" src="https://github.com/FreshPorts/freshports/assets/1626436/630ce242-d65c-4e9b-822f-4d56bc14bb20">

**Comment by dlangille** [comment]
> There is a possible regression for the code generating the table: when new archs are added or removed, some of the new table cells may be not a valid combination and should stay empty.

See `n/a` above for `FreeBSD:15` - this difference in architecture is not obvious in the original.

**Comment by dinoex** [comment]
Looks good from my side... I find it much easier to read and verify

**Comment by dlangille** [comment]
This work has been merged into `main`.
