### ISSUE TITLE
Do not display the quarterly branch for -CURRENT - that is never built

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#554]
Enhance: 

- https://github.com/FreshPorts/freshports/issues/551

:-)

**Comment by grahamperrin** [comment]
… has there _ever_ been quarterly for main (CURRENT)?

**Comment by dlangille** [comment]
`ABI` is maintained automagically: 

* #508

No quarterly for 15.

**Comment by grahamperrin** [comment]
Thanks, and for clarity (sorry) I think that the `FreeBSD:15:quarterly` row need not appear for as long as there will be no quarterly. 

<https://www.freshports.org/ports-mgmt/pkg/#packages>, for example: 

![image](https://github.com/FreshPorts/freshports/assets/192271/e12c0ea6-d5da-49d8-8eaa-5ec65a4bcfd1)

<https://pkg-status.freebsd.org/builds?type=package> _main_: 

![image](https://github.com/FreshPorts/freshports/assets/192271/d4dbe4e6-e9fc-46b3-a4d2-a0c7064d73ba)

**Comment by dlangille** [comment]
As you have discovered, the real issues have to be spelt out to me.

I'll investigate to see why `FreeBSD:15:quarterly` is not being removed by the ABI maintenance script.

**Comment by dlangille** [comment]
> As you have discovered, the real issues have to be spelt out to me.
> 
> I'll investigate to see why `FreeBSD:15:quarterly` is not being removed by the ABI maintenance script.

This explanation is not aimed at you. I should have realized the issue without must investigation. Today, as soon as I looked at the database, I realized.

```
freshports.dvl=# SELECT * FROM public.abi ORDER BY name ASC;
 id |          name          | active 
----+------------------------+--------
  2 | FreeBSD:13:aarch64     | t
 11 | FreeBSD:13:amd64       | t
 20 | FreeBSD:13:armv6       | t
 21 | FreeBSD:13:armv7       | t
 10 | FreeBSD:13:i386        | t
 58 | FreeBSD:13:powerpc     | t
 24 | FreeBSD:13:powerpc64   | t
 57 | FreeBSD:13:powerpc64le | t
 26 | FreeBSD:14:aarch64     | t
 27 | FreeBSD:14:amd64       | t
 28 | FreeBSD:14:armv6       | t
 29 | FreeBSD:14:armv7       | t
 30 | FreeBSD:14:i386        | t
 59 | FreeBSD:14:powerpc     | t
 33 | FreeBSD:14:powerpc64   | t
 56 | FreeBSD:14:powerpc64le | t
 54 | FreeBSD:15:aarch64     | t
 47 | FreeBSD:15:amd64       | t
 49 | FreeBSD:15:armv7       | t
 60 | FreeBSD:15:powerpc     | t
 52 | FreeBSD:15:powerpc64   | t
 55 | FreeBSD:15:powerpc64le | t
(22 rows)
```

`FreeBSD:15:quarterly` is not an ABI.

FreshPorts pulls ABI from https://pkg.freebsd.org/index.html (see #508 mentioned above).

For example, `FreeBSD:15:amd64` and `FreeBSD:15:aarch64` are ABI.

`quarterly` and `latest` are `package set`s (in FreshPorts terms; in FreeBSD terms they are are `branches`). At present, the `quarterly` branch is `2024Q1`.

Without treating `15` special, the quarterly branches for 15 will be displayed.

Code could be added: Is that the last ABI set? If so, don't display quarterly. Let's see how easy that is.

**Comment by dlangille** [comment]
Done at on my private website.

```
                                                $HTML .= '</tr>';
 
+                                               # Get the ABI (sort of) for the last row in this table.
+                                               # It will be something like FreeBSD:15:quarterly
+                                               # We don't display that row because historically, the quaterly branch is
+                                               # not build for -CURRENT.
+                                               #
+                                               $LastArrayPosition = array_key_last($package);
                                                foreach ($package as $ABI => $ABI_q_l) {
+                                                       #
+                                                       # re https://github.com/FreshPorts/freshports/issues/554
+                                                       # Try not to display the quarterly branch for the latest version.
+                                                       #
+                                                       if ($ABI === $LastArrayPosition) {
+                                                               continue;
+                                                       }
                                                        $HTML .= '<tr>';
 
                                                        $HTML .= '<td>' . $ABI . '</td>';
```

**Comment by dlangille** [comment]
See https://dev.freshports.org/multimedia/webcamd/#packages

![Screen Shot 2024-03-17 at 9 18 13 AM](https://github.com/FreshPorts/freshports/assets/1626436/bf9339e9-aebe-401d-9a4e-8ab0b29626ea)

**Comment by grahamperrin** [comment]
`dev` <https://dev.freshports.org/ports-mgmt/pkg/#packages> also looking good, thanks.

**Comment by dlangille** [comment]
We should add an FAQ re `CURRENT` and `quarterly`

**Comment by dlangille** [comment]
"NOTE: we do not display package for the quarterly branch on the latest CURRENT
   of FreeBSD. No pacakges are build for that ABI/package set combination."

see https://github.com/FreshPorts/freshports/commit/76bd60b89994633788b9f40eeca28b6df8f46727
