### ISSUE TITLE
Increase watch list limit?

### ISSUE THREAD

**Issue by rwv37** [FreshPorts/freshports#563]
There's currently a limit of five watch lists per user. Could this please be increased? Thanks.

**Comment by dlangille** [comment]
@rwv37 this was done - you should have access to 10 watch lists. If you'd like more, ask away. This first step is just to see if it gives you access to more.

```
freshports.org=> begin;
BEGIN
freshports.org=*> select max_number_watch_lists from users where name = '[redaacted]';
 max_number_watch_lists 
------------------------
                      5
(1 row)

freshports.org=*> begin; update users set max_number_watch_lists = 10 where name = '[redacted]';
WARNING:  there is already a transaction in progress
BEGIN
UPDATE 1
freshports.org=*> select max_number_watch_lists from users where name = '[redacted]';
 max_number_watch_lists 
------------------------
                     10
(1 row)

freshports.org=*> commit;
COMMIT
freshports.org=> 
```

**Comment by rwv37** [comment]
Great - thank you!

Everything I tried seemed to work fine:

- I successfully added up to a tenth watchlist;
- I got an appropriate error message when I attempted to add an eleventh;
- After I deleted one of the ten, it let me add a new tenth.

Unfortunately I am a bit swamped for the time being, so it will be a while before I have time to "really" use them the way I want, but I am looking forward to it. Thanks again!

**Comment by dlangille** [comment]
Production updated:

```
freshports.org=> begin;
BEGIN
freshports.org=*> alter table users alter column max_number_watch_lists set  default 10;
ALTER TABLE
freshports.org=*> update users set max_number_watch_lists = 10;
UPDATE 14673
freshports.org=*> commit;
COMMIT
freshports.org=> 
```
