### ISSUE TITLE
SSLH 2.1.2?

### ISSUE THREAD

**Issue by efaden** [FreshPorts/freshports#565]
Is it possible to get SSLH updated to 2.1.2 for both a vulnerability fix and UDP support?

**Comment by efaden** [comment]
Sorry.  Wrong place then.  Thanks for the info .

This is what I was looking at. 

https://www.cvedetails.com/vulnerability-list/vendor_id-29001/product_id-126792/Sslh-Project-Sslh.html

**Comment by dlangille** [comment]
That is exactly the information to include in a `security/vuxml` patch.  If you can submit that PR, it will happen faster.
