### ISSUE TITLE
Move new account captcha above the create account button

### ISSUE THREAD

**Issue by Obokkastar** [FreshPorts/freshports#569]
It makes sense to have the captcha Q&A above the create account button if it should be done first.  Unrelated, I failed my first try, likely due to O vs 0, but in the end I have an account after many years.

**Comment by Obokkastar** [comment]
Also had an issue with the 'server is busy' message being black text on dark background and initially just thought 'site is slow/unresponsive' until noticing the text. I am on Firefox with system theme and system is a dark kde theme. I had darkreader plugin enabled but turned off at the time I saw the hard to read text.

**Comment by dlangille** [comment]
> It makes sense to have the captcha Q&A above the create account button if it should be done first. Unrelated, I failed my first try, likely due to O vs 0, but in the end I have an account after many years.

I agree. I've done this, and I'll push that change to `dev` soon.

**Comment by dlangille** [comment]
> 

Might the message you saw have been: `Server too busy. Please try again later.  You should never see this message if you are logged in.`? It would have been displayed at the top of the page, plain text, nothing else on the page.

If so, I know the message you encountered.

**Comment by Obokkastar** [comment]
That would be the message and why I created the account. I many have hit it the day before and other times but not noticed the message due to text+background of similar color.

**Comment by dlangille** [comment]
This is now in production.
