### ISSUE TITLE
No package information for editors/vscode

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#570]
<https://www.freshports.org/editors/vscode/#packages> and `dev` <https://dev.freshports.org/editors/vscode/#packages>

> **No package information for this port in our database**
> 
> Sometimes this happens. Not all ports have packages.

Wayback Machine <https://web.archive.org/web/20240318093350/https://www.freshports.org/editors/vscode/#packages> reminds me that we usually do have a table of packages for this port.

**Comment by dlangille** [comment]
Based upon https://news.freshports.org/2020/04/12/packages-for-latest-and-quarterly/ I did this:

```
[11:36 empty dvl ~/tmp] % fetch https://pkg.freebsd.org/FreeBSD:14:amd64/quarterly/packagesite.txz
packagesite.txz                                       7112 kB   10 MBps    01s
[11:37 empty dvl ~/tmp] % unxz packagesite.txz                                                    
[11:37 empty dvl ~/tmp] % tar -xf packagesite.tar
[11:37 empty dvl ~/tmp] % jq -rc --arg ABI "FreeBSD:14:amd64" --arg BRANCH "quarterly" '[$ABI, $BRANCH, .origin, .name, .version] | @tsv' < ./packagesite.yaml > packagesite.csv
[11:38 empty dvl ~/tmp] % ls -l
total 37443
-rw-r--r--  1 dvl dvl  2402325 2024.06.14 11:38 packagesite.csv
-rw-r--r--  1 dvl dvl 53688320 2024.06.13 12:24 packagesite.tar
-rw-r--r--  1 dvl dvl 53684475 2024.06.13 12:23 packagesite.yaml
-rw-r--r--  1 dvl dvl      451 1970.01.01 00:00 packagesite.yaml.pub
-rw-r--r--  1 dvl dvl      256 1970.01.01 00:00 packagesite.yaml.sig
```

The downloaded data contains `vscode`:

`[11:38 empty dvl ~/tmp] % grep vscode packagesite.yaml
{"name":"py39-debugpy","origin":"devel/py-debugpy","version":"1.8.1","comment":"Implementation of the Debug Adapter Protocol for Python","maintainer":"sunpoet@FreeBSD.org","www":"https://github.com/microsoft/debugpy","abi":"FreeBSD:14:amd64","arch":"freebsd:14:x86:64","prefix":"/usr/local","sum":"9b030f7eae7b97b504df451d9bfea7c9c60dfa5f5215a4a2b28d8d9cb6d9daa1","flatsize":14871946,"path":"All/py39-debugpy-1.8.1.pkg","repopath":"All/py39-debugpy-1.8.1.pkg","licenselogic":"or","licenses":["EPL","MIT"],"pkgsize":1769361,"desc":"This debugger implements the Debug Adapter Protocol: debugProtocol.json [1].\n\n[1] https://github.com/microsoft/vscode-debugadapter-node/blob/main/debugProtocol.json","deps":{"python39":{"origin":"lang/python39","version":"3.9.18_2"}},"categories":["devel","python"],"annotations":{"build_timestamp":"2024-04-09T01:15:36+0000","ports_top_git_hash":"c5cd82114","ports_top_checkout_unclean":"no","port_git_hash":"b3aa1ea86","port_checkout_unclean":"no","built_by":"poudriere-git-3.4.1-1-g1e9f97d6","flavor":"py39","FreeBSD_version":"1400097"}}`

That data does not make it into the `csv` file:

```
[11:38 empty dvl ~/tmp] % grep vscode packagesite.csv 
[11:41 empty dvl ~/tmp] % 
```

**Comment by dlangille** [comment]
This is an extract from the `csv` file:

```
[11:44 empty dvl ~/tmp] % head -1 packagesite.csv
FreeBSD:14:amd64	quarterly	shells/zsh-syntax-highlighting	zsh-syntax-highlighting	0.8.0,1
```

**Comment by dlangille** [comment]
Clicking on the fallout icon at https://www.freshports.org/editors/vscode/ we get to:

https://portsfallout.com/fallout?port=editors%2Fvscode%24

<img width="1298" alt="Screenshot 2024-06-14 at 7 49 32 AM" src="https://github.com/FreshPorts/freshports/assets/1626436/36bb0648-edf1-4065-807e-81545c3f0273">

Seems it's failing to build.

**Comment by dlangille** [comment]
Now pulled into `dev`: https://dev.freshports.org/editors/vscode/#packages

**Comment by dlangille** [comment]
With this change comes Python 3.11 (good bye Python 3.9).

Installed on `dev`, `test`, and `stage` for a bit of testing before going to other locations.

**Comment by dlangille** [comment]
Now in production.

**Comment by grahamperrin** [comment]
> … That's why FreshPorts has nothing. It's not being built.

Thanks! 

FWIW, I'm 99% certain that repo-specific use of [pkg-search(8)](https://man.freebsd.org/cgi/man.cgi?query=pkg-search&sektion=8&manpath=freebsd-ports) **did** find _vscode_ when I opened this issue, which is why the apparent absence of _all_ packages seemed inconsistent. 

I can't be certain, I didn't keep notes. My bad. 

----

Now, for reference only: 

```text
% pkg info vscode | grep -A 10 Annotations
Annotations    :
        FreeBSD_version: 1500018
        build_timestamp: 2024-05-29T18:08:42+0000
        built_by       : poudriere-git-3.4.1-30-g79e3edcd
        port_checkout_unclean: no
        port_git_hash  : 83bca6ccdd3
        ports_top_checkout_unclean: no
        ports_top_git_hash: b6f9255af15
        repo_type      : binary
        repository     : FreeBSD-ports
Flat size      : 320MiB
% uname -KU
1500019 1500019
% pkg iinfo vscode
vscode-1.89.1_1
% 
```

**Comment by dlangille** [comment]
Right now:

```
[0:23 empty dvl /usr/local/etc/pkg/repos] % sudo pkg update
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
Updating local repository catalogue...
local repository is up to date.
All repositories are up to date.
[0:23 empty dvl /usr/local/etc/pkg/repos] % sudo pkg search vscode
[0:23 empty dvl /usr/local/etc/pkg/repos] % 


[0:23 empty dvl /usr/local/etc/pkg/repos] % pkg -vv | grep url
    url             : "pkg+http://pkg.FreeBSD.org/FreeBSD:14:amd64/quarterly",
    url             : "https://[redacted]/packages/FreeBSD:14:amd64",
[0:24 empty dvl /usr/local/etc/pkg/repos] % 
```

**Comment by grahamperrin** [comment]
Confirming: <https://www.freshports.org/editors/vscode/#packages> does have a table of packages. 

Thanks
