### ISSUE TITLE
New Account Confirmation: PHPMailer Fatal Error

### ISSUE THREAD

**Issue by mporembs** [FreshPorts/freshports#584]
I'm trying to create a new account but the site is unable to send me a confirmation email. The email address I used has a .ski TLD, if that matters. I keep receiving the following error:

```
Fatal error: Uncaught Error: Class "PHPMailer\PHPMailer\Exception" not found in /usr/local/share/phpmailer/PHPMailer.php:2063 Stack trace:
#0 /usr/local/share/phpmailer/PHPMailer.php(1689): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Fri, 2 Au...', 'Someone, perhap...')
#1 /usr/local/share/phpmailer/PHPMailer.php(1523): PHPMailer\PHPMailer\PHPMailer->postSend()
#2 /usr/local/www/freshports/include/freshports.php(2038): PHPMailer\PHPMailer\PHPMailer->send()
#3 /usr/local/www/freshports/www/login.php(138): freshports_UserSendToken('19778', Object(PgSql\Connection)
#4 {main} thrown in /usr/local/share/phpmailer/PHPMailer.php on line 2063
```

**Comment by dlangille** [comment]
Good news! I can reproduce this on prod and on my test host. :)

**Comment by dlangille** [comment]
I think I know why.

I moved from `postfix` to `dma` - and the website can't connect to it.

The fix may be a configuration file change, but it might also need code to do `auth`.

**Comment by dlangille** [comment]
@mporembs please try again. I have re-enabled `postfix` - my test worked.

**Comment by mporembs** [comment]
Works now. Thanks so much!
