### ISSUE TITLE
Imports of FreeBSD:15:i386

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#594]
Via <https://portsfallout.com/server> I found a `main-i386-default` build environment on beefy17. 

At the time of writing: 

- <https://pkg-status.freebsd.org/beefy17/build.html?mastername=main-i386-default&build=pa760f6876277_s5cbb98c8259> is running – status is _parallel_build:_
- via <https://github.com/FreshPorts/freshports/issues/593#issuecomment-2307952080>, <https://dev.freshports.org/--/package-imports.php> has no row for `FreeBSD:15:i386`

**Comment by dlangille** [comment]
I am not following the connections here.  Please tell me precisely what it is you think the website / page is missing.

Please do not let me interpret the information you have supplied. I will most certainly reach the wrong conclusion.

**Comment by dlangille** [comment]
OH. I think you're saying the website should be displaying something for `FreeBSD:15:i386`.

FreshPorts only follows ABI published by the project.

```
[15:25 dvl-ingress01 dvl ~/scripts] % cat ./current-list-of-valid-abi.sh
#!/bin/sh

fetch -qo - https://pkg.freebsd.org/index.html | \
  grep FreeBSD: | sed -e 's@.*\(FreeBSD:[^ <]*\).*@\1@' | sort
[15:25 dvl-ingress01 dvl ~/scripts] % 
````

**Comment by dlangille** [comment]
This prompted me to create https://dev.freshports.org/faq.php#abi because I couldn't find it documented anywhere.

**Comment by dlangille** [comment]
@grahamperrin I think this is covered, but if not, please reopen.

**Comment by grahamperrin** [comment]
Point of reference (from related discussion in FreeBSD Discord): 

- <https://www.freshports.org/faq.php#abi>
