### ISSUE TITLE
qemu port  crashes freshports

### ISSUE THREAD

**Issue by rblayzor** [FreshPorts/freshports#599]
https://www.freshports.org/emulators/qemu

Fatal error: Uncaught TypeError: array_key_last(): Argument #1 ($array) must be of type array, null given in /usr/local/www/freshports/classes/port-display.php:1572 Stack trace: #0 /usr/local/www/freshports/classes/port-display.php(1572): array_key_last(NULL) #1 /usr/local/www/freshports/rewrite/missing-port.php(930): port_display->Display() #2 /usr/local/www/freshports/rewrite/new-url-parsing.php(263): freshports_PortDisplayNew(Object(PgSql\Connection), Object(Port), 'emulators', 'qemu', Array, 'head', true) #3 /usr/local/www/freshports/rewrite/new-url-parsing.php(154): Try_Displaying_Port(Object(PgSql\Connection), Array, Array, 'head') #4 /usr/local/www/freshports/www/--/new-url-parsing.php(175): freshports_Parse404URI('https://www.fre...', Object(PgSql\Connection)) #5 {main} thrown in /usr/local/www/freshports/classes/port-display.php on line 1572

**Comment by dlangille** [comment]
Well. That's not polite!

This should be easily fixed. As soon as the grandkids nap.

**Comment by dlangille** [comment]
relates to #568

**Comment by dlangille** [comment]
@rblayzor now fixed in prod. Thank you for reporting this one.
