### ISSUE TITLE
clear out old distfiles

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/freshports#603]
From https://bsd.network/web/@dvl/113401885013085573

Courtesy of https://bsd.network/@piero

```
# cut -d \| -f 2 ${PORTSDIR}/INDEX* | while read d; do cd $d && make -V ALLFILES | tr " " "\n" | grep -v '^$' || : ; done > current-distfiles
# find ${DISTDIR} -type f | grep -v -f current-distfiles | xargs rm
```

Compile a list of the distfiles from INDEX, then delete everything not on that list.

The default command seems to use all the CPUs. Might want to try specifying `-j` - yeah, that works:

```
[0:38 mydev dvl /usr/ports] % time sudo make -j 36 index
```

Interesting, with 72 or 36, it's the same elapsed time: 13 minutes.

**Comment by smyru** [comment]
There is no need to generate the INDEX locally, INDEX file are generated by the project and can be fetched from within the ports tree by command `make fetchindex`. See /usr/ports/Makefile for the target internals.

**Comment by dlangille** [comment]
See draft blog post at https://news.freshports.org

**Comment by dlangille** [comment]
The time has come to test this out.

`ZFS POOL ALARM: POOL data01 usage is WARNING (80%)`

**Comment by dlangille** [comment]
See https://news.freshports.org/2024/12/24/moving-distfiles-to-a-new-filesystem/
