### ISSUE TITLE
UI: Main pages right-hand menu partially hidden in resolution with a width less than 1366px

### ISSUE THREAD

**Issue by Savagedlight** [FreshPorts/freshports#63]
Symptom: The right-hand menu becomes partially hidden and a horizontal scroll bar appears when browser width is less than 1366px. Example scenario: Sticking browser to the right half of a 1440p screen, giving 1237px width.

This seems to happen on main page (https://www.freshports.org/) but not when viewing details about specific ports.

I would make a suggestion on how to fix this, but I don't remember the table-layout hacks any more. ;)

**Comment by dlangille** [comment]
Yeah, that's because there is a particularly wide commit today: 

https://www.freshports.org/commit.php?category=science&port=py-tensorflow&files=yes&message_id=201711051643.vA5GhUUx062059@repo.freebsd.org

We could put that in a fixed size box which you have to scroll.

I bet you don't see that issue on this date: https://www.freshports.org/date.php?date=2017/11/4

**Comment by dlangille** [comment]
see also #35

**Comment by dlangille** [comment]
This is still a problem?

**Comment by Savagedlight** [comment]
![image](https://user-images.githubusercontent.com/752131/46425458-0aebf080-c73c-11e8-927b-8fe33d263aca.png)
Yes, it's still a problem. This is viewing the example in the second comment in this issue.

**Comment by dlangille** [comment]
See also #98

**Comment by dlangille** [comment]
@Savagedlight have a look at https://dev.freshports.org/x11/alacritty/ please

**Comment by dlangille** [comment]
I think we got a fix from @scott-ad-riley

```
[dan@dev-nginx01:~/www/www/css] $ git diff freshports.css 
diff --git a/www/css/freshports.css b/www/css/freshports.css
index a5295567..ba6b07c6 100644
--- a/www/css/freshports.css
+++ b/www/css/freshports.css
@@ -6,7 +6,7 @@ BODY, TD, TR, P, UL, OL, LI, INPUT, SELECT, DL, DD, DT, FONT
 IMG#fp-logo { max-width: 100%; height: auto }
 
 CODE.code { color: #461b7e}
-PRE.code {  color: #461b7e; white-space: pre-wrap}
+PRE.code {  color: #461b7e; white-space: pre-wrap; word-break: break-word; }
 
 .like-pre {
   color: #461b7e;
[dan@dev-nginx01:~/www/www/css] $ 

```

**Comment by dlangille** [comment]
This fixes all the above mentioned issues.

**Comment by dlangille** [comment]
@Savagedlight you're the OP. Looking good for you now?

**Comment by dlangille** [comment]
Now in production.
