### ISSUE TITLE
rss branch special case 'quarterly'

### ISSUE THREAD

**Issue by ronaldklop** [FreshPorts/freshports#79]
I think it would be nice to special case the branch name 'quarterly' to automaticly translate to the current quarter of the year.
This matches how you specify this in /etc/pkg/FreeBSD.conf:
url: "pkg+http://pkg.FreeBSD.org/${ABI}/quarterly"

I wrote 3 lines of code to implement it.

**Comment by dlangille** [comment]
Where's that code? Look in the repo for branch

**Comment by ronaldklop** [comment]
Oh, I see I opened a new issue by doing a pull request. Sorry. Getting used to the github way.

**Comment by dlangille** [comment]
I was so used to this on RSS that I expected it to work on the website.  e.g. https://www.freshports.org/devel/php73-intl/?branch=quarterly

**Comment by dlangille** [comment]
The reference in the commit is mistaken.

fixed by a72b4a9746a876b1f86da33bc6163f80bf088585
