### ISSUE TITLE
Database schema 

### ISSUE THREAD

**Issue by mheppner** [FreshPorts/freshports#8]
I'm planning on forking this repository and modernizing the codebase a bit. This will mostly be as a learning experience on my part, but if you like the direction I'm going, I would love to merge it back at some point.

In order to allow others to work on this project, it would be nice to have a copy of the database schema. A lot of it can be inferred from existing queries scattered throughout, but it would be easier to have a single place to view everything. A few rows of sample data would be wonderful too. `pg_dump` with the `-s` flag can export schema only, which would provide a great starting point.

I'm not too familiar with Postgres, but [the POSTGRESQL.sql file](https://github.com/FreshPorts/freshports/blob/master/configuration/POSTGRESQL.sql) looks it sets up permissions on existing tables, right?

**Comment by pstef** [comment]
@dlangille a full dump wouldn't be necessary, but perhaps just the schema?

**Comment by dlangille** [comment]
That should go into git. BRB.

**Comment by dlangille** [comment]
Actually doing a diff on test, stage, and prod would be nice. :)

**Comment by dlangille** [comment]
See https://github.com/FreshPorts/databases

**Comment by dlangille** [comment]
@pstef / @mheppner - I'm guessing all good. Closing this after nothing for 3+ years. Thanks.
