### ISSUE TITLE
Add support for CONFLICTS

### ISSUE THREAD

**Issue by zi0r** [FreshPorts/freshports#84]
It would be neat to see the conflicts for ports and be able to follow links to ports that match the expression.

You would want to support parsing:

[CONFLICTS, CONFLICTS_INSTALL and CONFLICTS_BUILD](https://www.freebsd.org/doc/en/books/porters-handbook/conflicts.html)

**Comment by dlangille** [comment]
I really like this idea.  My first reading is that CONFLICTS contains the PKG_NAME value, which is already stored in the database.  Should be very straight forward to do this.

I think it's a great idea.

**Comment by zi0r** [comment]
Plot twist: CONFLICTS variables can contain wildcards and regexy-type things.

Example:
`[0-9]*`

**Comment by dlangille** [comment]
From https://svnweb.freebsd.org/ports/head/Mk/bsd.port.mk?view=markup#l436

```
# CONFLICTS             - A list of package name patterns that the port conflicts
#                                 with, separated by blanks.  The names may include shell
#                                 pattern meta-characters "*", "?", "[", "]", and "!".
#                                 Example: apache*-1.2* apache*-1.3.[012345] apache-*+ssl_*

**Comment by dlangille** [comment]
Your task: find out if the field contains a regex or not.  Using php.

**Comment by dlangille** [comment]
Linking to the discussions on the mailing lists:

https://lists.freebsd.org/pipermail/freebsd-ports/2018-August/114084.html

**Comment by dlangille** [comment]
I see conflicts listed at https://www.freshports.org/sysutils/bacula9-server/

See also #103

**Comment by grahamperrin** [comment]
Done? Or still work in progress?

**Comment by dlangille** [comment]
Done. Example: https://dev.freshports.org/sysutils/bacula13-server/#conflicts and I added a tag for it.

I also added in a new tag: https://dev.freshports.org/sysutils/bacula13-server/#pkg-plist
