### ISSUE TITLE
Auto-render/display a Makefile dependency line

### ISSUE THREAD

**Issue by zi0r** [FreshPorts/freshports#99]
I often use Freshports when hunting down dependencies for ports.  It might be handy to have copy/pastable dependency lines to add to a Makefile.  For example:

For devel/p5-strictures, you could display:

`p5-strictures>0:devel/p5-strictures`

**Comment by dlangille** [comment]
see https://dev.freshports.org/devel/p5-strictures

**Comment by zi0r** [comment]
Awesome!
